ARCHITECTURE.md

The helm chats link was pointing to https://github.com/GaloyMoney/galoy-mobile even though the code for the charts has been moved to the new repository.

Fix link to helm charts in ARCHITECTURE.md

---

src/config.ts
src/text.ts

so that if the custom yaml override some property but not all property of a nested object, the missing property would be fetch from the default.yaml config file

do recursive merging for the config file. 

---

.envrc

The dev setup wasn't working consistently on Arch Linux.
Hopefully this workaround resolves the issue.
@krtk6160 can you please see if it works seamlessly now and merge if so?

Retry copying macaroon for integration tests

---

Dockerfile

While this solves the build issue, I think the better solution would be to not run `yarn build` in Docker at all and instead run it locally prior to docker build, and then COPY `lib` instead of `src`. Let me know if you want me to update the PR for that (note that'll require changing where `docker build` is run so that `yarn build` is run before it)

Use dev dependencies to run yarn build for Docker

---

DEV.md
Makefile

@bodymindarts Actually I realized I do use the "non-clean slate" integration command a lot. For example sometimes I want to re-run an idempotent test file multiple times while building a feature and having the `make integration` command do `reset-deps` made my dev workflow much slower.

Add restart-integration command

---

docker-compose.yml

Fixes https://github.com/GaloyMoney/galoy/issues/296
cc @sebastienverreault

Run mongodb as replicaset in docker-compose

---

default.yaml
src/entrypoint/graphql.ts
src/utils.ts

(Fixes GaloyMoney/galoy#130)
> on the ip stuff, would be good to have a way to 1/ deactive ip logging 2/ deactive proxy checking (from the yaml)
- Added new config (ipRecording)
- Nest proxyChecking in the new configuration
- Added new validations in context and updateIPDetails
- Refactor ipinfo updates (remove double try/catch)
this PR replace https://github.com/GaloyMoney/galoy/pull/270 (the rebase created an overhead)

Config enable/disable the ip and proxy log information (Fixes GaloyMoney/galoy#130)

---

src/Lightning.ts

after an invoice expired we want to delete the associated InvoiceUser entry in mongodb. we were not deleting the InvoiceUser correctly previously
there is no test on that because there were a related bug on lnd (https://github.com/lightningnetwork/lnd/issues/4587) where the invoice was not deleted immediately after it has expired but this bug should be fixed so a test would also be nice on this @dolcalmi

fix typo regarding the non-deletion of the InvoiceUser entry

---

initLocalTest.sh

We have `Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress` in every testnet_deploy job we've had for the past week at least. 
This is causing lnd1 to not get upgraded, and is also clear when looking at the age of the lnd1 and lnd2 pods, where lnd2's age is always less than lnd1's.

Switch to installing LNDs serially

---

initLocalTest.sh

It's now part of the rtl subchart within lnd so is no longer needed to be injected manually

Remove RTL-Config.json from deployment script

---

src/SpecterWallet.ts
src/config.ts
src/entrypoint/cron.ts
src/types.ts
test/integration/specter-wallet.spec.ts
test/unit/specter-wallet.spec.ts

This PR refactors the `SpecterWallet` class to have the config defined and explicitly passed via its constructor instead of having config values called directly from global state (`yamlConfig`).
The global state is instead used to create the config that gets injected explicitly at `SpecterWallet` instantiation.

(`SpecterWallet`) Inject config via constructor

---

src/config.ts
src/types.ts
src/walletFactory.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

This is a cleanup PR from some of the work introduced in #321 to bring that work more in line with patterns introduced in #344. Specifically this PR:
- moves the `UserWalletConfig` into a getter function in the `config` module (similar to `SpecterWalletConfig`)
- creates a new `ITransactionLimits` interface to help remove a circular dependency between the `config.ts` and `types.ts` files. This helps to start establishing a **"`types.ts` -> `config.ts` -> `other modules`"** (DAG-like) hierarchy.

Refactor 'UserWallet' types/config placement

---

default.yaml
src/OnChain.ts
src/SpecterWallet.ts
src/debug/export_accounts_to_csv.ts
src/entrypoint/exporter.ts
src/entrypoint/trigger.ts
src/ledger/balanceSheet.ts
src/ledger/ledger.ts
src/ledger/transaction.ts
src/lndUtils.ts
src/migrations/20210726211641-simplify-accounting.ts
src/schema.ts
src/userWallet.ts
test/integration/01-setup/01-funds-bitcoind-lnds.spec.ts
test/integration/01-setup/01-lightning-channels.spec.ts
test/integration/entrypoint/graphql.spec.ts
test/integration/lnd-utils.spec.ts
test/integration/notifications/notification.spec.ts
test/integration/schema.spec.ts
test/mocks/phone-provider.ts

**make liabilities more compact in the db**
the liabilities will only exist for a particular account. so the intermediary "Account" in "Liabilities:Account:uid" is superflous, and make the index bigger/slower. 
**some definition**
for this issue, I'll use wallet as: a set of transactions and a balance that are represented within midici with `Liabilities:${uid}`
and an account: the representation of 1 or n wallets.
**refactor the revenue/fees of the bank account**
first read: first section "A Bank’s Balance Sheet" in 
https://courses.lumenlearning.com/wm-macroeconomics/chapter/banking-profits-and-losses-name/
The first (naive) implementation was to have the "NetWorth" account at the same level of the other wallets. NetWorth of the bank would have been equal to the fees minus the expenses. …

improve accounting structure

---

src/entrypoint/trigger.ts
src/ledger/ledger.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/unit/ledger/ledger.spec.ts

- Add liabilitiesMainAccount path to ledger
- Add new way to resolve account id (user id) from account path
- Add new unit tests to account id resolver
- Add additional user id validation in onchain "sends a successful payment" test (this prevents future errors)
Ref: [PR 377 - improve accounting structure](https://github.com/GaloyMoney/galoy/pull/377)

Fix onchain notification issue with new account structure

---

Makefile

**Fixes https://github.com/GaloyMoney/galoy/issues/399**
For more details on the problem and solution see: https://github.com/TypeStrong/ts-node#help-my-types-are-missing
These specific error messages would only pop up if you ran `$ yarn install` locally after we [switched](https://github.com/GaloyMoney/galoy/commit/6df62a4598d35d8a8f6e6b6fde89f7472a9ed514#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L6) from `node` to `ts-node` in the Makefile. It didn't get picked up in tests/checks because we still use `tsc` there I believe.

Fix 'tsnd' skipping files by adding explicit --files flag, and use tsconfig-paths for TS paths

---

src/core/balance-sheet.ts
src/core/utils.ts
src/servers/cron.ts

- Refactor runInParallel code
- Add workers to onchain receipt
- Reorganize execution to allow to run the other jobs (this is temporal while we push the onchain PR)
```js
await deleteExpiredInvoiceUser()
await deleteFailedPaymentsAllLnds()
await specterWallet.tentativelyRebalance()
await updateRoutingFees()
```

Re-organize cron jobs order

---

src/config/app.ts
src/core/error.ts
src/core/lightning/index.ts
src/core/on-chain/index.ts
src/core/types.d.ts
src/servers/graphql-main-server.ts
src/services/lnd/utils.ts
src/services/mongoose/schema.ts
test/integration/02-user-wallet/02-index.spec.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/services/lnd/utils.spec.ts
test/unit/config.spec.ts

This PR refactors the `TransactionLimits` class to instead be a function where the entire limits config is set up on function call instead of on individual method calls. It also splits off a `UserLimits` class to handle _level-specific_ limits. This split was done because there are places in the codebase where properties like `oldEnoughForWithdrawal` from the `TransactionLimits` object are called without needing a `level` value.
These changes are used to remove limits-related `yamlConfig` references from the `schema.ts` & `graphql-core-server.ts` files.
**_Edit 1:_**
_To round off this PR, configs were also created for `yamlConfig.fees` values so the the `yamlConfig` import could be removed entirely from `schema.ts` & `graphql-core-server.ts`._
---

Refactor 'TransactionLimits' types/config

---

.github/workflows/integration-test.yml

Saw an integration test running for over an hour and [stopped](https://github.com/jotapea/galoy/actions/runs/1114999219) it manually. This adds an overall timeout for the integration test to avoid wasting pipeline minutes.

Add timeout to github actions integration-test

---

src/domain/bitcoin/onchain/errors.ts
src/domain/bitcoin/onchain/index.types.d.ts
src/domain/bitcoin/onchain/tx-filter.ts
src/domain/wallets/tx-history.ts
src/services/lnd/onchain-service.ts
test/unit/domain/bitcoin/onchain/tx-filter.spec.ts
test/unit/domain/wallets/tx-history.spec.ts
test/unit/services/lnd/onchain-service.spec.ts

The `createdAt` field was not being set correctly due to usage of casting.
This has triggered me to:
- remove all unused fields of SubmittedTransaction
- add unit tests around the conversion

Safer translation of lnds returned tx objects to SubmittedTransaction

---

src/app/wallets/add-invoice-for-wallet.ts
src/app/wallets/index.types.d.ts
src/domain/errors.ts
src/domain/ledger/index.types.d.ts
src/domain/primitives/index.types.d.ts
src/domain/users/index.ts
src/domain/users/index.types.d.ts
src/domain/wallets/index.ts
src/domain/wallets/index.types.d.ts
src/domain/wallets/tx-history.ts
src/domain/wallets/tx-methods.ts
src/services/ledger/index.ts
src/services/mongoose/schema.ts
src/services/mongoose/users.ts
src/services/mongoose/wallets.ts
test/integration/02-user-wallet/02-invoice.spec.ts
test/unit/domain/wallets/checked-to-username.spec.ts
test/unit/domain/wallets/tx-history.spec.ts

We will be moving the naming reference from the user level to the wallet level. This PR is to switch all references of `username` to `walletname` in the new code, but to leave the old code intact for now so that now functionality changes or migrations are needed.
_**Note:** I didnt remove the `Username` type and `username` property our `User` type because that one goes all the way through to the new graphql schema._

Switch username to walletname in new code

---

src/app/users/index.ts
src/servers/graphql-server.ts

- this validation `ips && ips.length` is also true for strings (so we were assigning the first number as ip)
-  before deploy to prod, please do a `requestPhoneCode` query, search for `RequestPhoneCode called` in the log and check the ip param

Fix ip array validation

---

src/app/lightning/payment-status-checker.ts
src/domain/ledger/index.types.d.ts
src/services/ledger/index.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts

fixes https://github.com/GaloyMoney/galoy/issues/503
`PaymentStatusChecker` was checking `WalletInvoice` but this is not the point of reference to see if something has been paid or not. It is the ledger!

PaymentStatusChecker must check ledger

---

src/app/wallets/get-balance-for-wallet.ts
src/app/wallets/index.ts
src/core/lightning/index.ts
src/core/on-chain/index.ts
src/core/user-wallet.ts
src/domain/ledger/index.types.d.ts
src/domain/wallets/index.types.d.ts
src/graphql/types/object/btc-wallet.ts
src/servers/exporter.ts
src/servers/graphql-old-server.ts
src/services/ledger/index.ts
test/helpers/index.ts
test/helpers/wallet.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-receive-rewards.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/servers/trigger.spec.ts

This PR adds the re-implemented `getBalanceForWallet` method to take the place of the old `getBalances` method.
The re-implementation only focuses on BTC balances. There are two outstanding places where USD balances are used, so the old `getBalances` method hasn't been removed as yet:
- `wallet2` endpoint in `graphql-old-server.ts` file
- `rebalancePortfolio` method in `src/services/ledger/transaction.ts` (with related integration tests)

Add new 'get balances' use case

---

src/graphql/root/mutation/twofa-generate.ts

schema.graphql has
`type TwoFAGeneratePayload {
errors: [Error!]!
twoFASecret: TwoFASecret
}`

Fix twoFAGenerate resolver

---

src/migrations/20210922002129-add-wallet-public-id.ts
src/migrations/migrate-mongo-config.js
src/services/mongoose/schema.ts

- Add walletPublicId Migration
- Add walletPublicId to user schema
- Update migration config to support current folder structure
1. Comment schema update 
```js
// walletPublicId: {
//   type: String,
//   index: true,
//   unique: true,
//   required: true,
//   default: () => crypto.randomUUID(),
// }
```
2. Run tests `TEST="01|02" make reset-integration`
3. Check documents in `users` collection (should not have walletPublicId)
4. Run migrations
```bash
$ cd src/migrations/
$ npx migrate-mongo up # if this fail you must comment up function content in 20210726211641-simplify-accounting
```
5. Check documents in `users` collection (should have walletPublicId)
6. Restore user schema (uncomment code from item 1)
7. Run tests `TEST="01|02" make reset-integration`
8. Check documents in …

Add wallet public id

---

src/graphql/root/query/btc-price-list.ts

For any price list whose rangeStart was after the first price returned in getHourlyPrice, the loop would break early and not push any of the dates after rangeStart into prices array.

Reverse btc price list loop to prevent early break

---

src/app/wallets/index.ts
src/app/wallets/reimburse-fee.ts
src/app/wallets/update-pending-payments.ts

This PR removes a level of indentation in the `reimburseFee` method by adding an early return for a conditional check in the method. It also moves the method to its own module to be re-used by the upcoming `send-payment` use-case.

Refactor reimburseFee method nested control flow

---

src/domain/errors.ts
src/domain/wallet-invoices/index.ts
src/domain/wallet-invoices/index.types.d.ts
src/domain/wallet-invoices/wallet-invoice-validator.ts
test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts

This PR adds a `walletInvoiceValidator` to check wallet invoices for lightning initiated payments that will be settled intraledger.
_**Note:** This was not swapped into any parts of the existing codebase because the logic implemented here is strung out across multiple `if` blocks and relies on objects that are poorly typed. We will have to be mindful of capturing the existing errors when using this in the new `send-payment` use-case._

Wallet invoice validator

---

src/app/wallets/reimburse-fee.ts
src/app/wallets/update-on-chain-receipt.ts
src/app/wallets/update-pending-invoices.ts
src/core/lightning/index.ts
src/core/on-chain/index.ts
src/domain/ledger/index.types.d.ts
src/services/ledger/index.ts
src/services/ledger/index.types.d.ts
test/integration/services/ledger/transaction.spec.ts

Add new ledger service methods:
- `sendLnTx` to replace `addLnPayment`
- `sendIntraledgerTx` to replace `addOnUsPayment`

Add new `send...Tx` methods to Ledger service

---

src/core/lightning/index.ts
src/core/on-chain/index.ts
src/domain/lock/index.types.d.ts
src/services/lock/index.ts

This PR adds a new `extendLock` method to our Lock service to wrap the `lockExtendOrThrow` method in a safe way for our new code style.

Add new `extendLock` method to Lock service

---

src/servers/cron.ts
src/services/lnd/index.ts
src/services/lnd/utils.ts

fix #573 (at least the failed htlc). 
we might want to dive more into the use of the `deletefailedpayments` (instead of `deleteFailedPayAttempts`), because it's possible we need the data about failed payments for support purpose. ie: when we need to do a refund.
the htlc part are safe to delete, and would likely already free the database significantly.

activate failed htlc payment pruning

---

src/app/accounts/get-limits-checker.ts
src/config/app.ts
src/core/accounts/helpers.ts
src/core/lightning/index.ts
src/core/on-chain/index.ts
src/core/types.d.ts
src/domain/accounts/index.ts
src/domain/accounts/index.types.d.ts
src/domain/accounts/limits-checker.ts
src/domain/errors.ts
src/domain/errors.types.d.ts
src/domain/ledger/index.types.d.ts
src/domain/primitives/index.types.d.ts
src/domain/twoFA/errors.ts
src/domain/twoFA/index.ts
src/domain/twoFA/index.types.d.ts
src/domain/users/index.types.d.ts
src/services/ledger/index.ts
src/services/mongoose/accounts.ts
src/services/mongoose/schema.types.d.ts
src/services/mongoose/users.ts
test/unit/domain/accounts/limits-checker.spec.ts

This PR adds a `LimitChecker` to aggregate and replace the various limit checks we run in the existing code. It also implements a new `txVolumeFor` method in the Ledger service that can be used to fetch the TxVolume input for the checker methods.
Old methods being replaced:
- `remainingWithdrawalLimit`
- `remainingOnUsLimit`
- `remainingTwoFALimit`

Add `LimitsChecker` object

---

src/domain/users/index.types.d.ts
src/services/mongoose/users.ts

The `UserDetails` object in graphql expects a `createdAt` property which currently isn't being translated from the user database object into our model. It results in things like the `userContactUpdateAlias` breaking in PR #602 if `createdAt` is included in the query.
This PR addresses that.

Add expected createdAt property to User model

---

package.json

I was having difficulties setting up my environment. One of the reasons was having the exact version of node working in the terminal at the time of installing packages and running the `make` commands.
I have updated the `package.json` to enforce this a little better to save the next person from some trouble!
Unsure if this engine should have an upper bound.

Enforce more specific node version

---

default.yaml
src/app/errors.ts
src/app/wallets/add-invoice-for-wallet.ts
src/config/app.ts
src/core/types.d.ts
src/core/wallets.ts
src/domain/rate-limit/errors.ts
src/domain/rate-limit/index.ts
src/domain/rate-limit/index.types.d.ts
src/graphql/error-map.ts
src/graphql/root/mutation/ln-invoice-create-on-behalf-of-recipient.ts
src/graphql/root/mutation/ln-invoice-create.ts
src/graphql/root/mutation/ln-noamount-invoice-create-on-behalf-of-recipient.ts
src/graphql/root/mutation/ln-noamount-invoice-create.ts
src/servers/graphql-old-server.ts
src/services/rate-limit/index.ts
test/helpers/rate-limit.ts
test/helpers/redis.ts
test/integration/02-user-wallet/02-invoice.spec.ts
test/integration/02-user-wallet/02-receive-rewards.spec.ts
test/integration/servers/graphql-main-server/auth-requests.spec.ts

Adds a redis rate limiter check for the `addInvoice` and `addInvoiceNoAmount` methods used by both old and new graphql endpoints.

Add new RateLimit service & implement invoice rate limits

---

src/app/users/get-user.ts
src/app/wallets/ln-send-payment.ts
src/graphql/root/mutation/ln-invoice-payment-send.ts
src/graphql/root/query/me.ts
src/servers/graphql-old-server.ts
src/servers/graphql-server.ts
src/services/tracing.ts

This PR begins to add some app-specific tracing.
In particular instrumentation is added to the pay-via-lightning use cases using helpers exposed in the `services/tracing.ts` module.
The diff is much smaller than it seems. Mostly code has just been indented und runs under a callback (similar like in the redis lock pattern we already have).
EDIT - a bit more context:
there are 2 _different_ helpers that 'wrap' functions - one sets attributes that should be added to _all_ child spans like:
```
addAttributesToCurrentSpanAndPropagate(
{
[SemanticAttributes.ENDUSER_ID]: domainUser?.id,
[ENDUSER_ALIAS]: domainUser?.username,
[SemanticAttributes.HTTP_CLIENT_IP]: ip,
},
```
This doesn't create its own span - it just makes sure it populates some context for all children to pick up. It should be …

App tracing

---

test/integration/servers/trigger.spec.ts

avoid lock in wallet id when same onchain block event is triggered multiple times

Validate block subscription height

---

dev/otel-agent-config.yaml
docker-compose.yml

By setting the following keys:
```
export HONEYCOMB_API_KEY=<api-key>
export HONEYCOMB_DATASET=<your-dataset>
```
in the terminal you run `make reset-deps` in you will get local traces in honeycomb.io

Add honeycomb config to local dev environment

---

src/app/wallets/ln-send-payment.ts
src/app/wallets/update-on-chain-receipt.ts
src/app/wallets/update-pending-invoices.ts
src/domain/notifications/index.ts
src/domain/notifications/index.types.d.ts
src/servers/trigger.ts
src/services/notifications/index.ts
src/services/notifications/payment.ts
src/services/notifications/payment.types.d.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/servers/trigger.spec.ts

Reviewing https://github.com/GaloyMoney/galoy/pull/662 and pairing with Arvin, we decided to split it in different PRs
- The main purpose of this PR is remove getCurrentPrice from transactionNotification
- Remove direct calls to transactionNotification
- Although we have some tests for notifications, we need to do final tests in staging

Remove getCurrentPrice from transactionNotification

---

DEV.md

jq is not installed by default on linux.
Adding it in the tool list could be useful for people setting up their development environment.

Add jq in DEV.md

---

docker-compose.yml

There is an issue rolling out the MongoDB upgrade to production (see https://github.com/GaloyMoney/charts/pull/192 to reproduce the issue locally).
Until we are able to roll this out to production we should keep the local dev env in sync with what we are currently running!

Revert "upgrade last mongodb version docker-compose"

---

src/core/on-chain/index.ts
src/core/on-chain/index.types.d.ts
src/graphql/main/schema.graphql
src/graphql/root/mutation/onchain-payment-send-all.ts
src/graphql/root/mutation/onchain-payment-send.ts
src/servers/graphql-old-server.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts

The main purpose of this PR is to add targetConfirmations for OnChainPaymentSend in V2
this is not a use case refactor but "fix" consistency between OnChainPaymentSend mutation and OnChainTxFee query

Add target confirmations to onChainPay

---

src/app/lightning/lookup-invoice-by-hash.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/graphql/admin/root/query/lightning-invoice.ts
src/services/lnd/index.ts

this is different for payments.
note: there are a aside case for payment not covered here
if we were to have 2 lnd, and the payment would have been sent through the first lnd, and failed. then send again with the second lnd and succeed.
we may only show the failed payment where in fact the payment would have succeed.
I think we should rely on medici also for the payments

no need for looping through invoices for admin panel

---

package.json

This PR fix testflight issue.
How to reproduce it
- pull `main`
- run `yarn build`
- run old or new server from generated code  `. ./.envrc && node lib/servers/graphql-old-server.js` (this returns error in current main)
if you run these cmds in this branch should run the server successfully

Fix price proto path

---

src/graphql/root/mutation/on-chain-address-create.ts
src/servers/graphql-main-server.ts
src/servers/graphql-middlewares/wallet-id.ts

Add walledId middleware. 
- This PR only includes refactor for `onChainAddressCreate` mutation
- Once this is approved will be added to other related payment mutations
How to test:
**Query**
```
mutation OnChainAddressCreate($input: OnChainAddressCreateInput!) {
onChainAddressCreate(input: $input) {
errors {
message
}
address
}
}
```
**Variables** 
```
// please test changing walletId to other existing wallet (from db)
{ 
"input": { "walletId": "31bfa4ac-fff9-43e3-ad73-dcd3834aa2c5" } 
}
```

Add walletId middleware

---

src/graphql/error-map.ts
src/graphql/main/schema.graphql
src/graphql/root/mutation/on-chain-address-current.ts
src/graphql/root/mutation/onchain-payment-send-all.ts
src/graphql/root/mutation/onchain-payment-send.ts
src/graphql/root/query/on-chain-tx-fee-query.ts
src/servers/graphql-middlewares/wallet-id.ts
src/services/mongoose/accounts.ts

- Does not include on chain pay use case migration for `onChainPaymentSend` and `onChainPaymentSendAll`
- Fix `onChainAddressCurrent` mutation and `onChainTxFee` query logic
- Includes `onChainAddressCurrent`, `onChainPaymentSend` and `onChainPaymentSendAll` in walletId middleware
- Fix empty error message for old app errors

Add on chain payment mutations/query to walletId middleware

---

src/app/wallets/index.ts
src/graphql/main/schema.graphql
src/graphql/root/mutation/intraledger-payment-send.ts
src/servers/graphql-middlewares/wallet-id.ts

- Add walletId to intraLedgerPaymentSend
- Fix error mapping 
- The use case was not changed to use wallet public id because this will need to be updated when we implement the new authorization system.

Add intraLedgerPaymentSend mutation to walletId middleware

---

src/graphql/main/schema.graphql
src/graphql/root/mutation/ln-invoice-fee-probe.ts
src/graphql/root/mutation/ln-noamount-invoice-fee-probe.ts
src/servers/graphql-middlewares/wallet-id.ts
test/integration/servers/graphql-main-server/auth-requests.spec.ts

- Does not include use case clean up.
- Wallet id is only used to validate ownership but after use case migration balance check validation should be added

Add ln fee probe to wallet id middleware

---

src/graphql/types/scalar/on-chain-address.ts

The new API currently lowercases all addresses which invalidates any non-Segwit address since those are case sensitive. This PR adds new regexes to more tightly check for different address formats and removes the 'toLowerCase' step that invalidates non-Segwit addresses.
Sources for formatting:
- https://regexland.com/regex-bitcoin-addresses/
- https://allprivatekeys.com/bitcoin-address-format

Fix onchain-address graphql validation

---

src/core/text.ts

Fix default values not saved in first login.
- Is not a problem in staging or production
- Only happens in local environment or when twilio credentials are not setup 
Problem
- https://stackoverflow.com/questions/26865357/default-value-not-set-while-using-update-with-upsert-as-true
- Here https://github.com/GaloyMoney/galoy/blob/main/src/core/text.ts#L181 user is only created with phone number and id (in db) but the user in memory has the default values generated by mongoose
- if twilio attr is not setup then we get carrier info and save the whole user https://github.com/GaloyMoney/galoy/blob/main/src/core/text.ts#L195 (including the default values generated in line 181)
- `getCarrier` can throw an exception (in local env is because twilio env variables are not setup) and if that happen …

Add user default values in first insert to collection

---

default.yaml
src/app/users/request-phone-code.ts
src/config/app.ts
src/domain/rate-limit/index.ts
src/domain/rate-limit/index.types.d.ts

I thought msBeforeNext was part of the API when calling the rate limit, but it's actually part of the response instead.
so adding a new rate limit to make the relevant effect

fix rate limit for min interval for phone code

---

src/domain/wallets/tx-history.ts

We have a "legacy" type for onchain transaction where the 'address' property wasn't previously recorded in the database. This means that at the graphql level this property can't be non-null until we either figure out a way to backfill this data or place a non-null placeholder value in there instead.
_**Note:** We have similar issues with `counterPartyWalletId` and `paymentSecret` properties where these have also been made non-null for now until we migrate the db, see #759._

Convert 'address' in graphql to allow null

---

ci/pipeline.yml

Changes the integration testing on Concourse worker with tag: `staging` -> `galoy-staging`

ci: Update staging worker tag

---

default.yaml
src/app/wallets/get-transactions-for-wallet.ts
src/app/wallets/update-on-chain-receipt.ts
src/config/app.ts
src/core/on-chain/index.ts
src/core/specter-wallet.ts
src/debug/update-on-chain-receipt.ts
src/domain/bitcoin/onchain/errors.ts
src/domain/bitcoin/onchain/index.ts
src/domain/bitcoin/onchain/index.types.d.ts
src/domain/errors.ts
src/graphql/error-map.ts
src/services/lnd/onchain-service.ts
src/services/lnd/utils.ts
test/unit/services/lnd/onchain-service.spec.ts

this is the 1st split of the on-chain pay use case refactor
Includes:
- Removes getOnchainReceipt
- Replace getOnChainTransactions
- Renames getIncomingTransactions to match repos standard (list prefix)

refactor: replace getOnChainTransactions dependency

---

src/graphql/playground.ts
src/servers/graphql-server.ts

To address #757.
Tested locally and worked fine.
Placeholder query is currently `btcPriceList` since it doesn't require authentication. This query also uses a variable, which may be useful for people to see. But let me know if you would prefer a different query.

docs: add placeholder query to playground

---

test/integration/services/mongoose/wallet-invoices.spec.ts

although this is only used in test, doing this to remove the warning

github complain that Math.random is not secure for a hash

---

src/servers/graphql-server.ts

I'm not sure if this change could affect anything else, but I just lost a lot of time debugging a `"Not authenticated"` error to realize that it was because my header was `{"Authorization": "Bearer <token>"}` and not `{"authorization": "Bearer <token>"}`.

fix: accommodate capitalized authorization header property

---

Makefile
src/servers/graphql-main-server.ts
src/services/mongodb/index.ts

- Allow re-indexing only in main server 
- Remove index sync by default in setupMongoConnection (it was done in admin, old server, exporter, cron, trigger, and daily balance notification) 
- Fix writeSDLFile open handle

fix: remove index sync by default in setupMongoConnection

---

src/app/lightning/payment-status-checker.ts

the error types didn't had any overlap
note: I'm a bit loss still about the way we're created the error. sometime the error extends directly from Error, sometime from RepositoryError.

fix: the error check was not checking anything

---

src/services/lnd/index.ts
test/integration/services/lnd/parse-errors.spec.ts

An attempt at describing the object that gets thrown from the `lightning` library we use, based on the request in [this comment](https://github.com/GaloyMoney/galoy/pull/786#discussion_r762862086).
It wasn't possible (afaik) to define as a usual Typescript type since the object was an array with specific values expected at specific indices. I instead included a rough description as a multi-line comment above the method we've implemented to parse these errors.

docs(lightning): add a rough description of the lib's error type

---

.github/workflows/integration-test.yml
Makefile

- Add an additional task to integration test to run cron and try to detect configuration issues
- Is necessary to run cron after integration test because DbMetadata needs to be initialized
- This is not a final solution because config can be updated in staging or prod (CI tasks need to be updated) but will help developers to avoid issues with cron job
Example

chore: add cron run to github integration job

---

src/domain/bitcoin/lightning/ln-invoice.ts

Routes hints from ln invoices were not being translated to our domain properly and so were returning `undefined` values when converted back to pass into the `lightning` library's `payViaPaymentDetails` method.
The end result of this bug was that we weren't able to pay any invoices where there were route hints and the final destination was a private node/channel.

fix: broken route translation for ln invoices to domain

---

src/graphql/types/object/graphql-user.ts
src/servers/graphql-server.ts
src/servers/index.files.d.ts

@nicolasburtey we can define the context for all resolvers this way

chore: define GraphQLContext and use it for the GraphQL User type

---

src/app/accounts/index.ts
src/domain/accounts/index.types.d.ts
src/services/mongoose/accounts.ts

managing user that could have several accounts is a very complex use case, that we should not try to cover for the time being (and probably for some time). most financial product from fintech that I have used in the recent past didn't offer this capability for this same reason

chore: one user should only connect to one account

---

src/app/users/index.ts
src/app/wallets/index.types.d.ts
src/app/wallets/intraledger-send-payment.ts
src/app/wallets/ln-send-payment.ts
src/core/lightning/wallet.ts
src/core/on-chain/index.ts
src/domain/ledger/index.types.d.ts
src/domain/notifications/index.types.d.ts
src/graphql/admin/types/object/account.ts
src/graphql/admin/types/object/user.ts
src/graphql/root/mutation/intraledger-payment-send.ts
src/graphql/root/mutation/ln-invoice-payment-send.ts
src/graphql/root/mutation/ln-noamount-invoice-payment-send.ts
src/servers/graphql-old-server.ts
src/servers/graphql-server.ts
src/services/ledger/index.ts
src/services/ledger/index.types.d.ts
src/services/mongoose/schema.ts
src/services/notifications/index.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/services/ledger/transaction.spec.ts

this mostly include nome renaming from payerWalletId and walletId to senderWallerId. there are more renaming from payer to sender to do on the codebase, but I just had extract the one I had encounter doing the add_earn use case refactoring

chore: extracting another part from `add_earn` refactoring

---

src/app/accounts/send-balance-to-accounts.ts
src/app/wallets/get-lightning-fee.ts
src/app/wallets/intraledger-send-payment.ts
src/app/wallets/ln-send-payment.ts
src/core/on-chain/index.ts
src/graphql/root/mutation/ln-invoice-fee-probe.ts
src/graphql/root/mutation/ln-noamount-invoice-fee-probe.ts
src/servers/graphql-old-server.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

- We only need to update pending invoices and payments when user request the balance
- the use of getBalanceForWallet is not necessary in internal methods

fix: use getBalanceForWalletId instead of getBalanceForWallet for internal queries

---

src/services/ledger/schema.ts

Transaction volume query is taking more than 6 seconds in production.
This is difficult to test but you can check index stats after run `TEST="01|02" make reset-integration` and you will notice that is the most used index (this is only a good indication that we need this index)
How to check index stats:
- Access db as a root
- Run `db.medici_transactions.aggregate([{ $indexStats: {} }])`
- Check `accesses.ops` value

chore: add index for volume query

---

.envrc
src/config/app.ts
src/services/twilio.ts

Twilio Sub-Accounts get an `Auth Token` and `Account SID` by default. 
I couldn't find a way to access a Sub-Account using API Keys and only found ways to create a Sub-Account by using the Main Account API Keys.
For us to use multiple environments, wherein each environment runs on a seperate Twilio Sub-Account, the Galoy codebase needs to use the Twilio Sub-Account credential, or `Auth Token` + `Account SID` approach.

chore!: modify twilio to use auth token

---

src/servers/graphql-old-server.ts

Return array instead of single value for old api `earnCompleted` endpoint

fix: return array for 'earnCompleted' old gql endpoint

---

src/debug/delete-failed-payment.ts

we'll need to run this sooner than later because of the issues we have with lnd. probably related to the fact a lot of payment has been failing over the last month following the lack of route hint. this has bloated lnd and make it slow/unstable

chore: update payment cleanup script

---

src/graphql/error-map.ts

the fact our balance is too low for a payment should not be exposed to the user (IMO)

fix: this is an internal error

---

src/servers/exporter.ts
src/servers/graphql-server.ts
src/servers/healthz-handler.ts
src/servers/trigger.ts
src/services/lnd/health.ts
src/services/redis/index.ts

Add mongo, redis and lnds status validation to trigger healthz endpoint
How to test:
- Run `TEST="01|02" make reset-integration`
- Run `make trigger`
- GET `http://localhost:8888/healthz` (should receive 200 after trigger initialization)
- Run `docker ps` to get container ids 
- Run `docker stop <galoy-backend-lnd2-1 container id>`
- GET `http://localhost:8888/healthz` (should receive 503)
- Run `docker start <galoy-backend-lnd2-1 container id>` 
- GET `http://localhost:8888/healthz` (should receive 200)
ps: you can use the same procedure with redis and mongo

fix: trigger health check

---

src/app/wallets/get-on-chain-fee.ts
src/core/on-chain/index.ts
src/domain/bitcoin/onchain/index.ts
src/domain/bitcoin/onchain/index.types.d.ts
src/domain/errors.ts
src/graphql/error-map.ts
src/graphql/types/scalar/on-chain-address.ts
src/services/lnd/onchain-service.ts
test/unit/domain/bitcoin/onchain/checked-to-on-chain-address.spec.ts

this is the 2nd split of the on-chain pay use case refactor
- Move on-chain address validator to domain
- Add payToAddress and getBalance to onchain service
- Update error parsing in on-chain service
- Update getOnChainFeeEstimate with 1 param policy

refactor: add payToAddress and getBalance to on-chain service

---

src/servers/cron.ts
src/servers/exporter.ts
src/servers/graphql-admin-server.ts
src/servers/trigger.ts
src/services/lnd/auth.ts
src/services/lnd/health.ts
src/services/lnd/unauth.ts
test/jest.setup.js

Fix lnd active param issue for servers. It should start inactive (false) and then updated the status with `activateLndHealthCheck` 
- Add `activateLndHealthCheck` to admin, exporter and cron
- Add integration test mocks to remove hacky workaround to udpate lnds statuses 
- Add PORT env config to trigger `healthz`

fix: lnd status update in servers and integration test

---

src/servers/graphql-old-server.ts
src/services/mongoose/accounts.ts

Fix a production issue that is crashing the app in the map view.
We should investigate a bit more about why we have some users with null values in title and/or coordinates

fix: remove null values from business map query

---

default.yaml
src/core/types.d.ts
src/servers/graphql-server.ts

In client environments that expose the playground the url is pointing to our staging instead of the environment its deployed too.

feat: make playgroundUrl configurable

---

src/domain/phone-provider/errors.ts
src/graphql/error-map.ts
src/services/twilio.ts

Currently the response when requesting a phone code for a bad phone number is:
```
{
"errors": [
{
"message": "Unknown error occurred (code: UnknownPhoneProviderServiceError)",
"code": "UNKNOWN_CLIENT_ERROR"
}
],
"data": null
}
```
from the log output I can see that twilio is returning a useful error message:
```
"err":{"type":"RestException","message":"The 'To' number +123456 is not a valid phone number."
```
So I've added some translation to return this to the user.

chore: better user feedback when providing a bad phone number

---

src/domain/wallets/tx-history.ts
test/integration/02-user-wallet/02-receive-rewards.spec.ts

This includes a fix to exclude onboarding earn memos from our memo filter.
I had originally tried to implement this using "approved walletIds" (like the `funder`) that would be excluded from the filter, but it turned out that it wasn't easy to get the sender's walletId for an intraledger transaction with the info we have on any given medici transaction record without going back to the journal.

fix: add earn memos as valid to the memo filter

---

src/services/tracing.ts

This fixes the extraction of errors from graphql query returns with `200 OK` status. It gets the `errors` object from the right layer of nesting and adds the ability to iterate over multiple sub-queries in a single query.
To observe changes:
- trace before: [https://ui.honeycom...47f8](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/sS6itB7yKfX/trace/d11y3EqoxDT?span=48c9af5f7c6a47f8)
- trace after: [https://ui.honeycom...eba8](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/y8881esnLSw/trace/cYbzQcFe2jS?span=020cbc96d4fdeba8)

fix: graphql errors parsing from returned object for traces

---

src/services/tracing.ts

This fix is to re-add the top-level `data.errors` handling that was removed in #897.
This issue here would be that the `error: true` property would still be set in the trace from the `non-200` code that graphql would return, but we would lose visibility on the details of the error at the `graphql.execute` level.
- **Trace with details missing:** [https://ui.honeycom...bb46](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/7ZjrhY9MsrG/trace/8QgcATwWYK?span=27868dbcb140bb46)
- **Fixed trace:** [https://ui.honeycom...627a](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/7ZjrhY9MsrG/trace/J2WX1JnDS2H?span=7831cba684a1627a)
_(**Performance sidenote:** The parsing seems to add about 50ms in latency from my repeated testing)_
---
_**Note:** PR #897 will likely also require a …

fix(tracing): missing top-level 'errors' handling in responses

---

src/domain/bitcoin/index.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/domain/bitcoin/lightning/ln-invoice.ts
src/domain/wallets/index.types.d.ts
src/domain/wallets/tx-history.ts
src/graphql/admin/schema.graphql
src/graphql/main/schema.graphql
src/graphql/types/abstract/settlement-via.ts
src/graphql/types/scalar/ln-payment-preimage.ts
src/graphql/types/scalar/ln-payment-secret.ts
src/graphql/types/scalar/onchain-tx-hash.ts
src/graphql/types/scalar/payment-hash.ts
src/services/lnd/index.ts
test/unit/domain/wallet-invoices/wallet-invoice-factory.spec.ts
test/unit/domain/wallets/tx-history.spec.ts

This PR is to fix two wrongly conflated concepts into the single `PaymentSecret` type.
There are two types of secrets associated with payment requests:
- payment identifying secret (included in encoded request)
- preimage (stored locally in lnd db)
We need to decide how to name these within our domain, and how to handle some considerations around the preimage.
In the simplest use-case, a preimage is either generated if we are the recipient or received against payment if we are the sender.
- for preimages that we generate, this should never be shared/revealed in our domain code before the given invoice it is associated with is paid
- for preimages that we receive, this can be revealed since it acts as a proof-of-payment for the payment sent
1. ~[Two new …

refactor: separate PaymentSecret type into 3 types

---

src/app/accounts/add-earn.ts
src/domain/errors.ts
src/domain/users/index.types.d.ts
src/domain/users/phone-metadata-validator.ts
src/graphql/error-map.ts
src/graphql/root/mutation/user-quiz-question-update-completed.ts
src/servers/graphql-old-server.ts

This PR adds types to the `addEarn` use-case method and refactors the return type from that method. It also refactors some of the error types and handling in the method.
Marking as **draft** until we can figure out why this doesn't break in the currently deployed app (cc @daviroo). It's also curious that we haven't been able to observe the `Cannot read properties of undefined (reading 'id')` in honeycomb as yet anywhere.
This is the response we get back when we call `userQuizQuestionUpdateCompleted` right now directly from something like Postman on both prod and dev:
```ts
{
"data": {
"userQuizQuestionUpdateCompleted": {
"userQuizQuestion": null,
"errors": [
{
"message": "Cannot read properties of undefined (reading 'id')"
}
]
}
}
}
```

fix: addEarn method return handling in new graphql endpoint

---

src/config/app.ts
src/graphql/main/schema.graphql
src/graphql/root/subscription/my-updates.ts
src/services/notifications/index.ts

make subscription updates from the accountId, instead of the walletId, so that a subscription get all the updates from the same account with a single sub

chore: make subscription updates from the accountId

---

src/servers/cron.ts
src/services/tracing.ts

This is to flush all the spans before the process completes

fix: graceful shutdown of tracing in cron

---

.github/workflows/integration-test.yml
Dockerfile-migrate
Makefile
ci/pipeline.yml
docker-compose.yml

For our next db migration we would like to have at least some level of
automation. Here we are adding an image to execute the migrations and
test-run them as part of the `integration-in-ci` make task.
Next step will be to add a job to the chart that can be used to execute the migration using this image.
Note I have used
```
FROM nodejs:16-alpine
```
for the image instead of a distroless one because `mongodb-migrate` depends on `/bin/sh` which isn't present in distroless. I haven't investigated wether or not there is a good alternative to alpine for this.

feat: dedicated migration image

---

src/app/wallets/get-balance-for-wallet.ts
src/app/wallets/update-on-chain-receipt.ts
src/app/wallets/update-pending-invoices.ts
src/app/wallets/update-pending-payments.ts
src/core/balance-sheet.ts
src/core/user-wallet.ts
src/domain/ledger/index.types.d.ts
src/servers/cron.ts
src/services/ledger/index.ts
src/services/ledger/query.ts
test/helpers/index.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

1st PR to remove `balance-sheet` from `core`
- Move `updatePendingLightningInvoices` and `updatePendingLightningPayments` to app layer
- Move `listWalletIdsWithPendingPayments` to main ledger service
- Update cron server with updated methods

refactor: invoices and payments updates in cron

---

src/migrations/migrate-mongo-config.js

Hopefully this fixes the current error on staging:
```
$ k -n galoy-testflight-af1d92a logs galoy-mongodb-migrate-1-zt6vn
ERROR: directConnection option requires exactly one host MongoParseError: directConnection option requires exactly one host
at parseConnectionString (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/core/uri_parser.js:711:21)
at connect (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/operations/connect.js:283:3)
at /app/node_modules/migrate-mongo/node_modules/mongodb/lib/mongo_client.js:284:5
at maybePromise (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/utils.js:692:3)
at MongoClient.connect (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/mongo_client.js:280:10)
at Function.MongoClient.connect …
```

fix: remove directConnection option from migrate config

---

src/config/app.ts
src/servers/graphql-admin-server.ts
src/servers/graphql-main-server.ts

Add env PORT configs to allow port update in api and admin servers (this is not an issue in our infra but may be useful in dev environments)
reported by @fiatjaf

feat: add env port config to v2 and admin servers

---

test/integration/02-user-wallet/02-invoice.spec.ts

if we simply return on error for test, the tests will exit succesfully and not execute what is after the `return error`
to make the test fails if something happen, it's necessary to throw instead of return
I came around this issue working on the fiat integration. I have not in other tests whether this issue is other places.

fix: throw, not return, for tests

---

src/graphql/error-map.ts
test/integration/servers/graphql-main-server/no-auth-requests.spec.ts

Improvement from changes in #932 to explicitly include errors type checks in rate limit tests.

test: make rate limit checks less self-referential

---

src/app/accounts/add-earn.ts
src/app/accounts/index.ts
src/app/accounts/update-default-walletid.ts
src/app/users/create-user.ts
src/app/wallets/intraledger-send-payment.ts
src/app/wallets/ln-send-payment.ts
test/integration/app/multiple-wallet-account.spec.ts

When removing bootstrap related code from `addWallet` it collapses simply to a `WalletsRepository.persistNew` so I have deleted that use case completely.
Also renamed `setDefaultWalletId` to `updateDefaultWalletId` as it can be changed more than 1 time.

refactor: bootstrap default wallet in createUser

---

Makefile

Fixes #951
The issue was that anytime we ran `make start-deps` after the initialization our dbs would be migrated with old migrations which would end up mutating the dev setup from the intialization.
This puts us back to just running `integration-deps` when starting the local dependencies.

fix: skip running migrations for local dev deps

---

src/graphql/admin/schema.graphql
src/graphql/admin/types/object/lightning-invoice.ts
src/graphql/admin/types/object/lightning-payment.ts

Builds on #953
This PR is to also re-assign the correct type to the `secretPreImage` and `revealedPreImage` properties in admin graphql schema.

refactor: re-assign admin gql secretPreImage type

---

src/config/app.ts
src/graphql/main/schema.graphql
src/graphql/root/query/globals.ts
src/graphql/types/object/build-information.ts
src/graphql/types/object/globals.ts

Add build information to global query
```
query {
globals {
nodesIds
buildInformation {
commitHash
buildTime
helmRevision
}
}
}
```
you have to setup `COMMITHASH`, `BUILDTIME` and `HELMREVISION` as env variables

feat: add build information to global query

---

Makefile
test/helpers/index.ts
test/helpers/integration-server.ts
test/integration/servers/graphql-main-server/auth-requests.spec.ts
test/integration/servers/graphql-main-server/galoy-pay-testing.spec.ts
test/integration/servers/graphql-main-server/no-auth-requests.spec.ts

- Removes trigger from background and from spawn process. Issue similar to https://github.com/GaloyMoney/galoy/issues/951#issuecomment-1013223870
- Change kill to use `SIGKILL`
- Helpers should not keep state of `pid`, moved to test files
- Add `yarn build` at the begining of `integration-in-ci` so `start-api-ci` does not have to do it (faster execution)
Please notice that we will need to test in CI env.

fix: integration test open handles

---

src/servers/trigger.ts

Add timestamp to backup filename to avoid conflicts reported by honeycomb alerts

fix: warning about filename conflict for channel backups

---

.envrc
src/core/user-wallet.ts
src/core/user-wallet.types.d.ts
src/domain/errors.ts
src/graphql/error-map.ts
src/migrations/20220111173334-separate-wallet-collection.ts
src/migrations/migrate-mongo-config.js
src/servers/graphql-main-server.ts
src/servers/graphql-server.ts
src/services/ledger/transaction.ts
src/services/ledger/transaction.types.d.ts
src/services/mongoose/accounts.ts
src/services/mongoose/rewards.ts
src/services/mongoose/schema.ts
src/services/mongoose/schema.types.d.ts
src/services/mongoose/users-ips.ts
src/services/mongoose/users.ts
src/services/mongoose/wallets.ts
src/services/notifications/index.ts
test/helpers/user.ts
test/integration/02-user-wallet/02-index.spec.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-receive-rewards.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/graphql/admin/mutations.spec.ts
test/integration/servers/trigger.spec.ts

- There was a mix between ObjectId and String in the domain code.
when using `collection._id` from mongoose, the value being returned is an ObjectId. 
when using `collection.id` from mongoose, by default, the value being returned is a string, casted from ObjectId
but MongoDb is not compatible between ObjectId and String. If you do a Colleciton.find({ accountId }), and this is saved as a string within mongodb, then the result is empty. (and vice et versa, if this is saved as a string but the query is with a ObjectId)
so this collection aimed at fixing this with:
- disabling the default .id on User with `{ id: false }` to avoid future confusion
- migration is removing the cast on String (will need to run again on staging)
- making sure the boundary for the core domain are respected, so that …

fix: mongoose type and migration

---

src/app/lightning/update-ln-payments.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/services/lnd/index.ts

Builds on #848
This PR simplifies the logic for the `updateLnPayments` method by getting rid of some of the complexity around parallelizing across multiple lnd instances (see [this thread](https://github.com/GaloyMoney/galoy/pull/848#discussion_r786639296)).

refactor: simplify updateLnPayments use-case method

---

src/graphql/admin/types/object/lightning-invoice.ts
src/graphql/admin/types/object/lightning-payment.ts

Builds on changes introduced in #848
This PR adds the missing resolvers after the domain type changes, for the `LnInvoice` and `LnPayment` objects in the admin graphql schema.

fix: add resolvers for admin gql Invoice/Payment selections

---

src/app/accounts/send-default-wallet-balance-to-users.ts
src/app/wallets/get-balance-for-wallet.ts
src/app/wallets/get-lightning-fee.ts
src/app/wallets/get-on-chain-fee.ts
src/app/wallets/intraledger-send-payment.ts
src/app/wallets/ln-send-payment.ts
src/app/wallets/pay-on-chain.ts
src/servers/exporter.ts
test/helpers/bitcoin-core.ts
test/integration/01-setup/01-funds-bitcoind-lnds.spec.ts

The use case `getBalanceForWalletId` was exported but never used from GQL layer - so there is no reason to export it as a top level use case.
For app layer internal usage it is also not necessary as it is simply wrapping 1 line.

refactor: Remove redundant use-case

---

src/services/lnd/schema.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

Adding back after thinking some more about [this comment](https://github.com/GaloyMoney/galoy/pull/848#discussion_r786650986).
Adding for easy debug purposes in the case where we'd like to know how long a payment has been sitting as "incomplete" in the db.
**Note:**
- objects _**always**_ get the `createdAt` property populated from lnd on settlement or failure when we persist the rest of the object and mark it as `isCompleteRecord: true`. The `createdAt` value will be overwritten at that point with whatever exists in `lnd`
- in the case of pending payments not persisted fully as yet, we can also always retrieve the actual `createdAt` value by querying lnd

refactor: add default 'createdAt' value for lnPayment objects in db

---

default.yaml
src/app/admin/backup.ts
src/config/yaml.ts

This PR takes the LND SCB backup GCS bucket name and extracts it to a yaml config variable. This allows each instance to set the backup bucket name as needed, as bucket names are globally unique across GCS.

feat: convert LND SCB backup GCS bucket name to yaml config variable

---

src/app/wallets/index.types.d.ts
src/app/wallets/pay-on-chain.ts
src/domain/wallets/index.ts
src/domain/wallets/index.types.d.ts
src/domain/wallets/payment-input-validator.ts
src/graphql/root/mutation/onchain-payment-send-all.ts
src/graphql/root/mutation/onchain-payment-send.ts
src/servers/graphql-old-server.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/unit/domain/wallets/payment-input-validator.spec.ts

This PR introduces a (unit-tested) `PaymentInputValidator` to take care of some common validation that must happen for all payment use cases.
Its currently only introduced into OnChainPay (as it is the simplest place to introduce it) but will be introduced in the other use cases in subsequent PRs.

refactor: payment input validation

---

src/app/wallets/intraledger-send-payment.ts
src/app/wallets/ln-send-payment.ts
src/app/wallets/pay-on-chain.ts
src/domain/ledger/index.types.d.ts
src/services/ledger/index.ts

Passing the `domainAccount` to the on chain pay use cases as a result of https://github.com/GaloyMoney/galoy/pull/998 means we don't have to reload the account to lookup the username.

refactor: rename payer to sender in ledger and perf improvement

---

src/app/lightning/update-ln-payments.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/services/lnd/index.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

When testing on our prod lnd payments set, I noticed that the `token` returned by the `getPayments` vs the `getFailedPayments` calls to lnd were not always consistent for the same start token as previously assumed. Because of this, we won't be able to paginate those two methods together, and so this PR is to separate the calling of the joined `listSettledAndFailedPayments` into two separate calls wherever it is currently used.
For context, this is the reason that both methods paginate differently on bigger databases with selectively cleaned payments already removed: [`getPayments`](https://github.com/alexbosworth/lightning/blob/3eaa5541e8f542ebd15e7d2da5e685aba6ea99f1/lnd_methods/offchain/get_payments.js#L135) vs. [`getFailedPayments`](https://github.com/alexbosworth/lightning/blob/3eaa554 …

refactor: separate 'listSettledAndFailed' method

---

src/app/wallets/check-limit-helpers.ts
src/domain/accounts/limits-checker.ts
src/utils/index.ts

Limits are denominated in cents now, so wallet volumes must be converted (in addition to payment amount) before doing limit checks.
Before this, the defined cents limit would be counted as sats for any payments (a much lower threshold).

fix: convert wallet volume to cents before comparing

---

CONTRIBUTING.md
src/app/users/request-phone-code.ts
src/domain/accounts/errors.ts
src/domain/bitcoin/lightning/errors.ts
src/domain/bitcoin/onchain/errors.ts
src/domain/cache/errors.ts
src/domain/captcha/error.ts
src/domain/cold-storage/errors.ts
src/domain/dealer-price/errors.ts
src/domain/errors.ts
src/domain/errors.types.d.ts
src/domain/ipfetcher/errors.ts
src/domain/ledger/errors.ts
src/domain/lock/errors.ts
src/domain/notifications/errors.ts
src/domain/phone-provider/errors.ts
src/domain/phone-provider/index.types.d.ts
src/domain/price/errors.ts
src/domain/rate-limit/errors.ts
src/domain/twoFA/errors.ts
src/graphql/error-map.ts
src/services/cold-storage/index.ts
src/services/tracing.ts

- Update error structure, now all domain errors extends `DomainError`
- Add error level to `DomainError` (default to Info and Critical for Unknown extended errors)
- Update tracing service to support error level.
- All catch (throws) are recorded as `critical`
- Add first example on how to handle an exception with `isWithdrawalTransaction` (500 error from bitcoind)

chore: update error structure

---

src/app/lightning/route-validator.ts
src/domain/routes/index.types.d.ts

This fixes the validation for routes.
For a 1234 sats invoice, the `rawRoute` object looks like this:
```
{
confidence: 857375,
fee: 2,
fee_mtokens: '2002',
hops: [
{
channel: '1970341x11x0',
channel_capacity: 344646,
fee: 1,
fee_mtokens: '1001',
forward: 1235,
forward_mtokens: '1235001',
public_key: '028ec70462207b57e3d4d9332d9e0aee676c92d89b7c9fb0850fc2a24814d4d83c',
timeout: 2163503
},
{
channel: '1970331x22x0',
channel_capacity: 344646,
fee: 1,
fee_mtokens: '1001',
forward: 1234,
forward_mtokens: '1234000',
public_key: '02eadbd9e7557375161df8b646776a547c5cbc2e95b3071ec81553f8ec2cea3b8c',
timeout: 2163463
},
{
channel: '2100720x63x0',
channel_capacity: 1234,
fee: 0,
fee_mtokens: '0',
forward: 1234,
forward_mtokens: '1234000',
public_key: …
```

fix: change tokens value we compare for route validation

---

src/domain/phone-provider/errors.ts
src/graphql/error-map.ts
src/services/twilio.ts

fix false alert when recipient has opted out of receiving messages
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/ikLL52B3Hdn/trace/hghBVTWmUAb?span=fec6edd473d42101
https://www.twilio.com/docs/api/errors/21610#:~:text=Attempt%20to%20send%20to%20unsubscribed,one%20of%20your%20previous%20messages.

fix: unsubscribed recipient error from twilio

---

src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts

fix false alert with timed outs payment attempts https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/rabLPua7kGP/trace/nkzpNpCdkw7?span=f25d4846b5090929
this was validated with Alex
```
you can check on trackpayment but should be not pending
pathfinding is try route a, try route b, etc until timeout hits, then ignore route c
so it should fire this error after route b attempt was tried and conclusively failed
```

fix: payment attempts timed out

---

src/domain/errors.ts
src/graphql/error-map.ts
src/graphql/main/queries.ts
src/graphql/main/schema.graphql
src/graphql/root/query/account-default-wallet.ts
src/graphql/types/abstract/public-wallet.ts

This PR adds a new query to:
1. return the wallet currency for a user's `defaultWalletId`
2. return the `defaultWalletId(ByCurrency)` based on an optional specified currency
We need this to know what type of wallet we are working with in places like for our `galoy-pay` repo. Right now, galoy-pay breaks if the user's default wallet is `USD` and they try to set an amount in the interface because the `lnInvoiceSendOnBehalfOfRecipient` mutation does not support USD wallets. We would need to know the wallet type to be able to switch on:
- `lnInvoiceSendOnBehalfOfRecipient`
- `lnUsdInvoiceSendOnBehalfOfRecipient`

feat: add new default-wallet-id query to support wallet currencies

---

src/app/wallets/get-lightning-fee.ts

We've noticed that we get [this dealer error](https://ui.honeycomb.io/galoy/datasets/galoy-hack/result/CMXV2Fnj8FY/trace/8nPgLTPFKQ4?span=e8bc65978cbe0d3c) for wallets with a non-rounded-integer balance.
This is an attempt to fix this.

fix: round cents down if not rounded int

---

src/graphql/root/mutation/user-update-username.ts
src/graphql/types/object/graphql-user.ts

Improve the responses from the `UserUpdateUsername` mutation:
- on success, includes the username instead of `null` in the response
- on "is immutable" edge case, still returns a user object as feedback (didn't before this)

chore: improve UserUpdateUsername returns

---

src/domain/bitcoin/lightning/errors.ts
src/domain/bitcoin/onchain/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts
src/services/lnd/onchain-service.ts

- Fix false alert on lightning fee probing https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/J3QUuxve9dm/trace/xR9YhiDopQs?span=4919e42e210b3266
- Add custom error for insufficient funds available for on-chain transactions https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/jKzXBzcPvjQ/trace/mN9h85vZ8Bn?span=774e3069e1e455d4

fix: onChain/offChain fee estimation error handling

---

default.yaml
src/config/yaml.ts
src/core/types.d.ts
src/servers/cron.ts

This PR modifies the cron job to disable rebalancing in environments which have the `rebalanceEnabled` flag set to false.
Related PR in galoy-deployments to add the new variable: https://github.com/GaloyMoney/galoy-deployments/pull/1241

feat: Add cron config

---

test/integration/01-setup/01-price-history.spec.ts
test/integration/services/price.spec.ts

**Context for the `HOURS_IN_YEAR` change**

fix: adjust price tick counts down to account for Feb

---

default.yaml
src/app/wallets/send-on-chain.ts
src/config/schema.ts
src/config/yaml.ts
src/core/types.d.ts

There is an edge-case where onchain fee estimation can be lower than the actual fee used for an onchain txn in the case where the fee environment is very volatile.
In these cases, it is possible for our balance check to be bypassed by a small amount which amounts to the difference the fee estimate is off by in sats. The highest we've seen this be off by so far is 3586 sats.
To help address this two measures are proposed in this PR:
1. Bring the estimate check closer to the actual send to reduce the effects from fee volatility
1. **(Feature change!)** Add a fee buffer when doing the balance check to help mitigate from the edge instances where the fee can still differ
This 2nd measure effectively means that a user would not be able to empty their wallet via onchain, but can still do so over …

fix: minimize chance of small negative user balance from fee estimation

---

src/graphql/main/mutations.ts
src/graphql/main/queries.ts
src/graphql/root/mutation/ln-invoice-payment-send.ts
src/graphql/root/query/me.ts

This PR adds properties like `enduser.id` to all mutations and queries. Sparked from exploring the balance bug from PR #1153.

chore: add top-level attributes to all queries/mutations

---

test/integration/02-user-wallet/02-send-onchain.spec.ts

There's been a consistent `core dump` error that I've only been able to observe locally when running tests for some time now. 
```
/home/arvin/.nodenv/versions/16.1.0/bin/node[212027]: ../src/node_http2.cc:450:void node::http2::Http2Session::CheckAllocatedSize(size_t) const: Assertion `(current_nghttp2_memory_) >= (previous_size)' failed.
1: 0xb12b40 node::Abort() [/home/arvin/.nodenv/versions/16.1.0/bin/node]
2: 0xb12bbe  [/home/arvin/.nodenv/versions/16.1.0/bin/node]
3: 0xb4c37d node::mem::NgLibMemoryManager<node::http2::Http2Session, nghttp2_mem>::ReallocImpl(void*, unsigned long, void*) [/home/arvin/.nodenv/versions/16.1.0/bin/node]
4: 0xb4c4e3 node::mem::NgLibMemoryManager<node::http2::Http2Session, nghttp2_mem>::FreeImpl(void*, void*) [/home/arvin/.nodenv/versions/16.1.0/bin/node] …
```

fix: add delay as workaround to core dump error

---

src/servers/cron.ts

We noticed all `lnpayment` objects with `failed` status in the `lnpayments` collection had empty arrays for their `attempts` property. This is to fix that by persisting first before deleting attempts.

chore: persist lnpayments before deleting failed attempts in cron

---

src/domain/cache/index.ts
src/domain/cache/index.types.d.ts
src/services/cache/index.ts
src/services/lnd/index.ts

add additional validation to resolve payment status.
If payment is pending:
- Check payment timeout against current block height
- If transaction has expired then check that all the output channels (in paths) are closed

fix: htlc stuck after output channel close

---

src/domain/users-ips/index.ts
src/servers/graphql-server.ts
test/unit/domain/users-ips/parse-ips.spec.ts

- Add support for ips string array
- Add `x-forwarded-for` fallback (required when galoy instance is not behind a balancer)

fix: update parse ip to support ip string array

---

src/app/wallets/send-intraledger.ts
src/app/wallets/send-lightning.ts
src/app/wallets/send-on-chain.ts
src/domain/ledger/index.ts
src/domain/ledger/index.types.d.ts
src/domain/shared/calculator.ts
src/domain/shared/index.types.d.ts
src/domain/shared/primitives.ts
src/services/ledger/admin-legacy.ts
src/services/ledger/domain/accounts.ts
src/services/ledger/domain/entry-builder.ts
src/services/ledger/domain/errors.ts
src/services/ledger/domain/index.ts
src/services/ledger/domain/index.types.d.ts
src/services/ledger/domain/legacy-entry-builder.ts
src/services/ledger/facade.ts
src/services/ledger/helpers.ts
src/services/ledger/index.types.d.ts
src/services/ledger/intraledger.ts
src/services/ledger/receive.ts
src/services/ledger/send.ts
src/services/ledger/tx-metadata.ts
test/integration/services/ledger/facade.spec.ts
test/unit/services/ledger/domain/entry-builder.spec.ts
test/unit/services/ledger/domain/legacy-entry-builder.spec.ts
test/unit/services/ledger/domain/tx-metadata.spec.ts

Continues the work of PR #1170:
- add ledger facade
- rewrite ledger entry-builder to work with expected PaymentFlow updates

refactor: add LedgerFacade with new entry builder

---

src/services/ledger/volume.ts

These events make a lot of noise in the trace (eg https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/g6MxroZzscW/trace/Bm73uNu3nD1?span=b7b20f1ed4cce353) which makes it harder to visually identify the parts of the trace containing errors.
Also they don't add information as the query span (`monbodb.command`) already tells us how long the aggregation takes.

fix: remove noisy events

---

src/services/mongoose/users.ts

We have had a few alerts because mongoDB has returned a duplicate key error on login. This is expected behaviour and shouldn't be treated as a critical error.

fix: duplicate key is not a critical error

---

src/migrations/20220203152515-bootstrap_accounts.ts
src/services/lnd/index.ts
src/services/tracing.ts
yarn.lock

Fix yarn lock issues. We need to find a way to avoid this, it is probably a merge issue.
This error was found after rebase https://github.com/GaloyMoney/galoy/pull/1178 (it is throwing some errors only updating yarn.lock)
How to test:
- checkout main branch
- remove yarn.lock and node_modules
- run `yarn install`
- try to run `make check-code` or unit tests

fix: yarn lock update issues

---

src/services/notifications/index.ts

Prior to this commit, a bug in `notificationsService.intraLedgerPaid` resulted in the
`NotificationType.IntraLedgerPayment` being published to the sender twice. Now the
notification is published to the sender, and then the recipeint, correcting this
unintended behavior.
Resolves #934 and #1220.

fix: ensure recipients of intraledger payments receive notifications via gql subscription

---

.github/workflows/audit.yml
Makefile
ci/pipeline.yml
ci/tasks/audit.sh

FYI, this will block the pipeline now because there are already 5 critical severity vulnerabilities which should be fixed asap:
https://ci.galoy.io/teams/dev/pipelines/galoy-app/jobs/audit/builds/2#L62309a8a:5

ci: run audit step

---

src/services/lnd/index.ts

Stringify errors for `UnknownLightningServiceError` to avoid error messages like `503,TemporaryChannelFailure,[object Object]`

fix: stringify unknown lightning errors

---

src/graphql/root/subscription/ln-invoice-payment-status.ts

Testing https://github.com/GaloyMoney/galoy/pull/1246 in staging found that we were getting an error without correct parsing
```
{
"error": {
"message": "Subscription field must return Async Iterable. Received: { errors: [[Object]] }."
}
}
```
this change returns the proper error
```
{
"errors": [
{
"message": "Invalid value for LnPaymentRequest",
"locations": [{ "line": 2, "column": 3 }],
"path": ["lnInvoicePaymentStatus"],
"extensions": { "code": "INVALID_INPUT" }
}
]
}
```
please notice that error handled in line 40 is different because this is an input validation error (should be handled in the same way than queries)

fix: return a valid error for empty paymentRequest

---

src/services/tracing.ts
yarn.lock

`SimpleSpanProcessor` changed its interface to 
```
export declare class SimpleSpanProcessor implements SpanProcessor {
private readonly _exporter;
private _shutdownOnce;
constructor(_exporter: SpanExporter);
forceFlush(): Promise<void>;
onStart(_span: Span, _parentContext: Context): void;
onEnd(span: ReadableSpan): void;
shutdown(): Promise<void>;
private _shutdown;
}
```
this PR updates tracing service to support the new interface (this is related to yarn.lock issue)

fix: update SimpleSpanProcessor onStart override

---

src/config/yaml.ts
src/services/notifications/index.ts
src/services/notifications/payment.ts
test/e2e/servers/trigger.spec.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts

Rename so as to not confuse with an external service call to get the display currency.

refactor: rename getDisplayCurrency to getDisplayCurrencyConfig

---

src/domain/bitcoin/lightning/ln-invoice.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

Fix issue with msats invoices (probe and payment) updating decode invoice to use safe tokens
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/sooTn7xzKfk/trace/tTvXGtnMP39?span=8418714adec94963

fix: update decode invoice to use safe tokens

---

src/app/wallets/reimburse-fee.ts
src/app/wallets/send-lightning.ts
src/app/wallets/update-pending-payments.ts
src/config/yaml.ts
src/domain/bitcoin/index.ts
src/domain/fiat/index.ts
src/domain/fiat/index.types.d.ts
src/domain/ledger/index.types.d.ts
src/services/ledger/index.types.d.ts
src/services/ledger/receive.ts
src/services/ledger/schema.ts
src/services/ledger/send.ts
src/services/ledger/tx-metadata.ts
test/integration/services/ledger/facade.spec.ts

This PR adds a new amount-related properties to Lightning send payments to support the in-review payments-refactor work in #1237.

feat: add new amounts properties to transaction persist layer

---

src/migrations/20220427130214-add-sats-amount-prop-to-payments.ts

**_Note:_** _Converted to draft until #1281 is merged_
This PR migrates new amount-related properties to past Lightning send payments records.
- `git checkout` to `main` branch and run `TEST="01|02-a|02-r|02-s.*l" make reset-integration` to initialize pre-migrated database
- `git checkout` to this branch and edit `Ln 3` in `src/migrations/migrate-mongo-config.js`:
```ts
const address = process.env.MONGODB_ADDRESS ?? "localhost:27017"
```
- check mongo pre-migration to make sure `satsAmount` property does not exist in `medici_transactions` collection
- run `node_modules/.bin/migrate-mongo up -f src/migrations/migrate-mongo-config.js`
- check mongo post-migration with `{$or: [{type: "payment"}, {type: "fee_reimbursement"}]}` query to make sure all records returned have a value set for …

chore: migrate new amount-related properties to old entries

---

src/app/payments/send-lightning.ts
src/services/ledger/index.types.d.ts
src/services/ledger/tx-metadata.ts
src/services/payment-flow/index.ts
src/utils/index.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/services/ledger/facade.spec.ts
test/unit/services/ledger/domain/tx-metadata.spec.ts
test/unit/utils.spec.ts

This PR:
- adds a new elapsedTime method + unit test
- fixes the metadata for the new Ln Intraledger logic

fix: badly calculated `usd` ln intraledger property

---

src/app/payments/send-lightning.ts
src/app/wallets/reimburse-fee.ts
src/app/wallets/update-pending-payments.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

The metadata amounts added to `fee_reimbursement` transactions reflected the original `payment` transaction's amounts but this won't work for the display purpose these will be used for.
This PR corrects the active `usd` property (which is already correct on `main`) to reflect the reimbursement amount instead of the original payment amount from the related `payment` transaction entry.
We will need a follow up PR to correct the following currently-unused properties for `fee_reimbursement` transactions:
```
{
satsAmount: feeSats,
satsFee: 0,
centsAmount: feeCents,
centsFee: 0,
displayAmount: feeCents,
displayFee: 0
}
```

fix: fee_reimbursement transactions 'usd' property value

---

default.yaml
src/app/payments/send-lightning.ts
src/domain/errors.ts
src/domain/payments/index.types.d.ts
src/domain/payments/payment-flow.ts
src/graphql/error-map.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/unit/payments/payment-flow.spec.ts

This PR corrects the comparison amount to include the fee as part of the check. It also moves this logic into a `PaymentFlow`  method and adds unit tests for it.

fix: correct amount for send-lightning balance check

---

src/servers/graphql-main-server.ts
src/services/mongodb/index.ts

from mongoose doc: 
https://mongoosejs.com/docs/guide.html#indexes
> When your application starts up, Mongoose automatically calls createIndex for each defined index in your schema. Mongoose will call createIndex for each index sequentially, and emit an 'index' event on the model when all the createIndex calls succeeded or when there was an error. While nice for development, it is recommended this behavior be disabled in production
I checked the behavior enabling debug `mongoose.set("debug", true)` and that was happening (so index creation is being executed in every pod restart, every time we send balance notifications, cron execution, ...) so `syncIndexes` were only executing twice the createIndex.
Finally I enabled sync indexes in graphql main server because previously was done by the …

fix: disable mongoose auto index

---

src/app/cold-storage/get-balances.ts
src/core/balance-sheet.ts
src/domain/cold-storage/index.types.d.ts
src/servers/exporter.ts
src/services/cache/index.ts
src/services/cold-storage/index.ts
src/services/tracing.ts

- Refactor exporter server
- gauge creation now use collect (parallelizes get metrics)
- gauge creation now adds tracing wrapper by default
- improves performance for AssetsLiabilitiesDifference and BookingVersusRealWorldAssets
- Add cache to galoy wallets balance (use a race condition similar to payInvoice). Does not fix db issue with funder wallet but avoid data gaps in grafana for other metrics 
- Add tracing to cache service
- Fix issue assigning function name in tracing service
New tracing example (dev): https://ui.honeycomb.io/galoy/datasets/jp-dev/result/J1Q1XDR2gBD/trace/5EgXYXu97Du?span=61f3eaa054836caf

refactor: exporter server

---

src/domain/payments/payment-flow-builder.ts
test/unit/payments/payment-flow-builder.spec.ts

Fix for the issue where we were able to get `"withSenderWallet impossible"` error with the following variables for `intraledgerUsdPaymentSend` mutation (see [trace](https://ui.honeycomb.io/galoy/datasets/galoy-hack/result/wNdPskAo26S/trace/G6Rb4PfWdcg?span=dc63a3d8226675fd))
```
{
"input": {
"walletId": "{{walletIdUsd}}",
"amount": 0.0229,
"recipientWalletId": "{{walletIdBtc}}"
}
}
```

fix: uncheckedAmount check to handle '0' value

---

src/domain/wallets/tx-history.ts

This fixes the `Infinity` error we see for transactions selection on `base` property in our gql query.
I wasn't able to replicate the root cause for the 0-amount transaction, but I was able to reproduce the error by manually editing the database locally.

fix: division by 0 error when calculating settlementPrice

---

src/graphql/main/schema.graphql
src/graphql/types/abstract/account.ts
src/graphql/types/object/business-account.ts
src/graphql/types/object/consumer-account.ts
test/e2e/servers/graphql-main-server/auth-requests.spec.ts
test/e2e/servers/graphql-main-server/queries/transactions-by-wallet-ids.gql

With the last commit (https://github.com/GaloyMoney/galoy/pull/1325/commits/bd00fbd45f351dafcf66d5156f2d43769adc5739) that allowed the walletIds to be optional, this query behaves more like a 'transaction for account' query with an optional walletIds filter.
Given this, a better naming for this selection could simply be 'transactions' under an Account.

refactor: rename 'transactionsByWalletId' to 'transactions'

---

test/e2e/servers/graphql-main-server/auth-requests.spec.ts

Adds a missing test case for new `transactions` selection.

test: add case for non-owned walletId passed to transactions mutation

---

src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts

Adds a new error type to handle lnd internal error when a payment is re-attempted and is still in transition.
Traces: [Link](https://ui.honeycomb.io/galoy/datasets/galoy-bbw?query=%7B%22start_time%22%3A1653504789%2C%22end_time%22%3A1653504872%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22code.function%22%2C%22error.name%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22payment.request.hash%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22127500243a9de3d6bcc811f90bcc70cdfa7aab1bd6f52aa6cd1e8c9a5bcda50d%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D)

feat: add new 'PaymentInTransition' lnd error handling

---

src/app/payments/helpers.ts
src/app/payments/update-pending-payments.ts
src/domain/ledger/index.ts
src/domain/ledger/index.types.d.ts
src/domain/payments/index.ts
src/domain/payments/index.types.d.ts
src/domain/payments/ln-fees.ts
src/domain/payments/price-ratio.ts
src/domain/shared/errors.ts
src/domain/shared/index.types.d.ts
src/domain/shared/primitives.ts
src/domain/shared/safe.ts
src/graphql/error-map.ts
src/services/dealer-price/dealer-price.ts
src/services/ledger/facade.ts
src/services/ledger/index.ts
src/services/ledger/volume.ts
src/services/payment-flow/index.ts

This PR does 2 things, which can be treated separately (via commits) depending on which changes we find appropriate
- moves most calls to `BigInt` into single calling functions
- adds a `safeBigInt` wrapper and swaps it into some places where `BigInt` is called
- I had to remove some of the generic type signatures from certain functions because I couldn't get around a Typescript error with them (see commit https://github.com/GaloyMoney/galoy/pull/1304/commits/8354197459f3c13c189399a14f79921230aca3f7). 
**The Typescript error is scoped out [here](https://www.typescriptlang.org/play#code/PTAEGUFEBUFUAUBQiAuBPADgU1AdQIYA2hWKAwgK4BOVWAdgMZqgC8oARAELRnugA+HWOAAi7ANyIGAezoBnFHiIly1Wo2ZsA3olB7QnFAwBcHbrwA0u-bDkATU+2FjEAX1D45oGfJTJ02ErEpCJYcgxUAJYYKNJUADwioFgAHij0dl4Ewao09EwAfKygOvqgkQ6gClF0AObWeg …

refactor: consolidate BigInt calls & add safe big int

---

src/app/payments/send-lightning.ts
src/app/payments/update-pending-payments.ts
src/app/wallets/reimburse-fee.ts
src/migrations/20220601191441-fix-reimburse-amounts.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

This PR corrects the amounts properties being added to `fee_reimbursement` transactions. In the initial changeset, these properties were originally pointed at the original transaction's amount which is incorrect. This PR changes it so that the amounts correspond to the actual transaction they live on.
This migration behaves the same for both pre-change and post-change txns in the db since it reads off existing properties (`debit` & `usd`) from the transaction and makes changes based on that. Also we are only writing the new amounts properties and are not reading from them as yet for any business logic or api returns so these changes should not need any other refactors in the codebase.

fix: correct amounts for fee_reimbursement txns in db

---

src/app/lightning/update-ln-payments.ts
src/app/payments/helpers.ts
src/app/users/get-user.ts
src/debug/migrate-ln-payments-listpayments.ts
src/debug/migrate-ln-payments-trackpaymentsv2.ts
src/servers/trigger.ts
src/services/tracing.ts

This is a proposed fix for [this issue](https://github.com/GaloyMoney/galoy/issues/1344).
It changes the attributes arguments to SpanOptions on the asyncRunInSpan function.
This means when we call it we can optionally set the span to be the root of the trace.
I have called in that way inside the trigger.ts for onchainBlockEventhandler as example.
The main change made:
https://github.com/GaloyMoney/galoy/blob/71f697ba18636b45ab4a6a9ae0a8d2b40a405e07/src/services/tracing.ts#L230-L239
How to set a span to be root with this:
https://github.com/GaloyMoney/galoy/blob/71f697ba18636b45ab4a6a9ae0a8d2b40a405e07/src/servers/trigger.ts#L177-L193

fix: invalid tracing context set as root in trigger

---

src/graphql/error-map.ts
src/graphql/error.ts

This PR adds a user-facing message for the error that pops up when all our onchain funds are swapped out and no funds are available in the hot wallet for sending by users (this is usually remedied by a looping out offchain funds back onchain).
We would like to communicate to the end-user in a concise way that:
- our liquidity is currently imbalanced
- it will be re-balanced again soon
We would like to avoid:
- signalling that we somehow don't have enough funds available to fulfill a user request
- implying that we somehow run a fractional reserve system (we don't)

refactor: add friendly message for insufficient funds error

---

src/app/payments/get-protocol-fee.ts
src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/graphql/root/mutation/ln-invoice-fee-probe.ts
src/graphql/root/mutation/ln-noamount-invoice-fee-probe.ts
src/graphql/root/mutation/ln-noamount-usd-invoice-fee-probe.ts
src/graphql/root/mutation/ln-usd-invoice-fee-probe.ts
test/e2e/servers/graphql-main-server/auth-requests.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

This PR changes the feeProbe use-case method to return `PartialResult` objects to accommodate being able to return a max fee alongside an error if the probe fails.

refactor: return max fee where possible when probe errors

---

src/app/payments/update-pending-payments.ts
src/domain/payments/index.types.d.ts
src/services/payment-flow/index.ts
src/services/payment-flow/schema.types.d.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

Change the redundant update method to be purpose-specific 'mark not pending' method for `IPaymentFlowRepository` interface.

refactor: make redundant flow update method more specific

---

src/app/wallets/get-transactions-for-wallet.ts

Clean unnecessary on-chain tx filter span. https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/GnhD3nav6zC/trace/eVvnLBXzAJ4?fields[]=name&fields[]=service.name&span=802d4c4bb3cade56 (the span does not provide parameteres nor return errors just true/false)
note: this run in get transaction (main query) so represent ~38363 events per day (only in bbw env)

chore: remove unnecessary on-chain tx filter span

---

src/app/payments/helpers.ts
src/app/payments/send-lightning.ts

This is a simple refactor PR to separate `paymentFlow` fetching/creating logic from the `validate...` methods in the `send-lightning` use-cases. This will make the layout of this logic consistent with `send-intraledger`.

refactor: separate paymentFlow from validation logic

---

src/domain/ledger/fee-reimbursement.ts
src/domain/payments/index.types.d.ts
src/domain/payments/price-ratio.ts
src/domain/shared/calculator.ts
src/domain/shared/index.types.d.ts
test/unit/domain/ledger/fee-reimbursement.spec.ts
test/unit/domain/payments/price-ratio.spec.ts
test/unit/domain/shared/amount-calculator.spec.ts

This PR ensures that for reimbursements if there is a non-zero sat fee we should always round down the usd amount that we reimburse.

fix: round down USD amounts when reimbursing fees

---

src/domain/payments/index.types.d.ts
src/domain/payments/payment-flow-builder.ts
src/domain/payments/price-ratio.ts
src/domain/shared/calculator.ts
src/domain/shared/index.types.d.ts
test/mocks/dealer-price/index.ts
test/unit/domain/payments/price-ratio.spec.ts
test/unit/domain/shared/amount-calculator.spec.ts
test/unit/payments/payment-flow-builder.spec.ts

This PR is to round up the routing fees when converting to `usdProtocolFee` when building a payment flow.
The bulk of this PR was:
🛠️  refactoring the payment-flow-builder unit tests with more realistic ratios and appropriate amounts ([here](https://github.com/GaloyMoney/galoy/pull/1359/commits/0359f5b9f357af68af97a5a520cc9767aff1733a))
🛠️  to be able to isolate a failing test ([here](https://github.com/GaloyMoney/galoy/pull/1359/commits/489089e0ad4cb62d8af90ec50578ac746c6b47c0))
✅  to be able to fix with the changes to the fee calculations ([here](https://github.com/GaloyMoney/galoy/pull/1359/commits/90eff7cb32848f6e6eb3d3dbeef239c02efcb768))

refactor: round up usd send fees in payment flow builder

---

src/domain/payments/payment-flow-builder.ts
test/unit/domain/ledger/fee-reimbursement.spec.ts
test/unit/payments/payment-flow-builder.spec.ts

This PR is to round up the remaining places in the payment-flow-builder where usd fees are calculated from a max btc fee.
It also spills over into reimbursement fee calculations, where before this rounding up was happening we would still get instances where the full usd amount would be reimbursed even though a non-zero amount of sats fees were spent.

refactor: round up all max usd fee calcs in payment flow

---

src/services/ledger/domain/entry-builder.ts
src/services/ledger/domain/index.types.d.ts
src/services/ledger/domain/legacy-entry-builder.ts
test/unit/services/ledger/domain/entry-builder.spec.ts
test/unit/services/ledger/domain/legacy-entry-builder.spec.ts

This PR is to exclude unnecessary zero-amount entries to the ledger when receiving transactions. This is to target txns for USD wallets where:
- low-sat-amount reimbursements which result in zero-amount usd ledger entries
- no-amount usd invoice receives where the sats received don't cross 1 cent and result in a zero-amount entry
In both cases, the user will now no longer see any transactions in their transactions list for these events.

refactor: omit zero amount txns from ledger entries

---

src/app/payments/send-lightning.ts
src/domain/payments/errors.ts
src/graphql/error-map.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

Fix issue reported here https://galoymoney-workspace.slack.com/archives/C025NSXHME3/p1655319587559629
- User sends a payment but it is hold (returns pending)
- User didn't notice the pending payment and try to do a second payment to the same invoice
- Payment fail but only 1 tx is voided (this fix does not include trigger update but avoids the double spending)

fix: add double spending restriction for a pending payment

---

src/domain/wallets/index.types.d.ts
src/domain/wallets/tx-history.ts
src/graphql/types/object/transaction.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/unit/domain/wallets/tx-history.spec.ts

`Transaction` objects now need to reference both `BTC` and `USD` settlement types.
This is a proposed change to the `Transaction` object to allow that. The `settlementAmount` property has been made generic since the currency information for the transaction is carried in the `settlementCurrency` property on the object (similar to how we encode this in the `PaymentAmount` type [in the domain](https://github.com/GaloyMoney/galoy/blob/16c76100cb7ed6241ae7a87982477346e460c175/src/domain/shared/index.types.d.ts#L12))
_**Tbd:** does this break the API?_

refactor: change 'Transaction' gql object amounts type/descriptions

---

package.json
src/app/admin/backup.ts
src/config/process.ts
src/servers/trigger.ts
yarn.lock

This pull request adds a nextcloud destination for the static channel backups.
The corresponding pull request for the charts can be found [here](https://github.com/GaloyMoney/charts/pull/978). However this can be merged without changes to the helm charts. If the nextcloud environment variables are not set it will simply skip it.
Additionally it replaces the dropbox dependency with axios.
Since Nextcloud uses a Webdav interface where the filepath is contained inside the url. The NEXTCLOUD_URL environment variable thus takes the whole url for example `https://myserver.com/remote.php/dav/files/myuser/backupfolder`.
Please see the [official documentation here](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#uploading-files).
I have added a check in the …

feat: add nextcloud static channel backups

---

src/config/process.ts
src/domain/bitcoin/index.ts
src/domain/bitcoin/onchain/index.ts
src/graphql/docs/galoy-dev.postman_environment.json
src/graphql/docs/galoy-staging.postman_environment.json
test/unit/domain/bitcoin/onchain/checked-to-on-chain-address.spec.ts

Introducing signet support for the api related to: https://github.com/GaloyMoney/charts/issues/1123
The changes are fairly straightforward as the address format is the same as on testnet. Simply reused the same addresses for signet for the checks.
See for example the same address being used on both signet end testnet displayed by a for of the Blockstream Esplora block explorer:
Signet:
https://explorer.bc-2.jp/address/tb1ql7w62elx9ucw4pj5lgw4l028hmuw80sndtntxt
Testnet: 
https://blockstream.info/testnet/address/tb1ql7w62elx9ucw4pj5lgw4l028hmuw80sndtntxt

feat: add signet support

---

package.json
src/services/bitcoind/bitcoin-core.types.d.ts
src/services/bitcoind/index.ts
src/services/cold-storage/index.ts
test/helpers/bitcoin-core.ts
yarn.lock

replace unmaintained bitcoin-core with bitcoin-core-ts ([fork](https://github.com/sapio-lang/bitcoin-core-ts)) from https://github.com/sapio-lang.
- It supports signet https://github.com/sapio-lang/bitcoin-core-ts/blob/master/src/index.ts#L21
- They began to add TS support

chore: replace bitcoin-core with bitcoin-core-ts

---

yarn.lock

this seems to be helpful for medici 5 for some reasons. creating this PR to make the diff smaller for #1046

chore: delete and recreate yarn.lock to get last dependancies

---

src/domain/ledger/index.types.d.ts
src/domain/wallets/index.types.d.ts
src/domain/wallets/tx-history.ts
test/unit/domain/wallets/tx-history.spec.ts

This PR separates `LedgerTransaction` and `WalletTransaction` types to have 2nd variants with metadata included.
The reason for this is we decided that there are cases where we wouldn't go to the 2nd `transaction_metadata` collection in our db for performance reasons and these types reflect the separate cases where we query that additional collection vs. when we do not.
These types will eventually move all the way to a new `TransactionWithMetatadata` object at the graphql level in a follow-up PR.
After this PR is merged, the changes will be incorporated into PR #1077 to help handle the new metadata changes there.

refactor: separate transaction types to accommodate metadata

---

src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts

This is to add a timeout to fee probes to allow getting back the "max fee" at the api level after the fixed max time (currently 45s).

feat: add timeout to route probe

---

src/servers/cron.ts

Fix async execution of `deleteLndPaymentsBefore2Months`. It was similar in how notifications work but in this case we need to wait to prevent the process from ending before the task completes.

fix: delete lnd payments async execution

---

src/services/redis/index.ts

I believe this code was part of the old local-k8s dev environment and is no longer used.

chore: delete redis config code from legacy dev setup

---

src/app/payments/send-intraledger.ts
src/domain/payments/index.types.d.ts

For unknown reasons the typescript compiler didn't flag a difference
between type definition and implementation which allowed a `null` value
to be passed where none was assumed in the downstream code.

fix: inconsistency between type definition and implementation

---

src/app/wallets/index.ts
src/domain/errors.ts
src/domain/wallets/index.types.d.ts
src/graphql/admin/queries.ts
src/graphql/admin/root/query/all-walletids.ts
src/graphql/admin/root/query/wallet.ts
src/graphql/admin/schema.graphql
src/graphql/error-map.ts
src/servers/graphql-admin-server.ts
src/services/mongoose/wallets.ts

This PR adds two new endpoints in the admin Graphql query. An `allWalletIds` query that returns a list of all the wallet id's and a `wallet` query that returns an individual wallet based on the `walletId` passed.

feat: add graphql endpoints to fetch all wallet id's and wallet

---

src/app/wallets/get-balance-for-wallet.ts
src/app/wallets/update-pending-invoices.ts
src/domain/bitcoin/lightning/errors.ts
src/domain/bitcoin/lightning/index.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/domain/wallet-invoices/errors.ts
src/domain/wallet-invoices/index.types.d.ts
src/domain/wallet-invoices/wallet-invoice-builder.ts
src/graphql/error-map.ts
src/servers/cron.ts
src/servers/trigger.ts
src/services/lnd/index.ts
src/services/mongoose/schema.ts
src/services/mongoose/schema.types.d.ts
src/services/mongoose/wallet-invoices.ts
test/e2e/servers/trigger.spec.ts
test/helpers/bitcoin-core.ts
test/helpers/check-is-balanced.ts
test/helpers/lightning.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts
test/integration/services/mongoose/wallet-invoices.spec.ts
test/jest-e2e.setup.js
test/unit/domain/wallet-invoices/wallet-invoice-builder.spec.ts
test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts
test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts

**_This reverts commit 91dd5f1c66578a442b44b21f45d2f14d6ac1001f._**
There's the continued issue where `subscribeInvoices` does not receive `ACCEPT` or `CANCEL` events for hodl invoices. The solution for now appears to be to create individual subscriptions for held invoices and manage these (see https://github.com/lightningnetwork/lnd/issues/3120#issuecomment-1160732579).
This PR reverts changes for now to unblock pipeline and continue working locally.

Revert "feat: hodl invoice (on WalletInvoiceBuilder) (#1395)"

---

src/domain/payments/payment-flow-builder.ts

Along the lines for trying to stick to the `async/await` convention wherever possible and to not introduce promise callbacks, this is a refactor to remove some callbacks from the LPFB.

refactor: convert '.then' to async/await in LPFB

---

src/app/lightning/delete-ln-payments.ts
src/domain/errors.ts

One of the payment deletions from lnd failed because the payment wasn't persisted in our `lnPayments` collection in staging. This should never happen, and looking through honeycomb it has never happened on bbw and has only happened for one hash on staging (see [trace](https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/tkf74TrugwD/trace/bW2JwSc5wJs?fields[]=c_name&fields[]=c_service.name&span=7ff71de4869e39f4)).
Given how infrequently this happens I made two changes:
- add any missing hashes from deletion code to lnPayment as incomplete payments to be picked up by the usual update-incomplete code
- escalated that particular `CouldNotFindLnPaymentFromHashError` error to critical
It turns out that this can happen if we do operations directly on the node like loop-outs. We had paused …

fix: handle 'CouldNotFindLnPaymentFromHashError' errors

---

src/app/lightning/delete-ln-payments.ts

The code should not return the `CouldNotFindLnPaymentFromHashError` error after it has been handled. These critical error traces [here](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/GJmWs9kTJDf/trace/jR9FGYEZZEP?fields[]=c_name&fields[]=c_service.name&span=477badc093345d10) should not have been added to these spans for example.
This change fixes that.

fix: return false for handled error in 'checkAndDeletePaymentForHash'

---

default.yaml
src/app/payments/get-protocol-fee.ts
src/app/payments/helpers.ts
src/app/payments/send-intraledger.ts
src/app/payments/translations.ts
src/config/schema.ts
src/config/schema.types.d.ts
src/config/utils.ts
src/config/yaml.ts
src/domain/bitcoin/lightning/index.ts
src/domain/payments/errors.ts
src/domain/payments/index.types.d.ts
src/domain/payments/payment-flow-builder.ts
src/graphql/error-map.ts
src/services/payment-flow/index.ts
src/services/payment-flow/schema.types.d.ts
src/utils/index.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/unit/payments/payment-flow-builder.spec.ts
test/unit/payments/payment-flow.spec.ts

This PR fixes an issue where some services will always fail the fee probe whether there is a route or not (e.g. Muun). This is an issue because the attempt is logged in lnd's mission-control and it blocks any real payments attempts that are tried soon after the probe.
This PR allows us to configure flagged destinations that will fail and to skip the probe and simply return a max fee for these routes.

feat: skip fee probe for flagged destinations

---

Makefile
package.json
yarn.lock

This supports changes in PR #1484
There is another issue here where one of the new dependencies is causing heap allocation errors in our CI at the 2048 bytes memory level. Options to fix are:
- bump the memory in CI tests (done here)
- to find the bad dependency version and roll it back one
---
**Taken from [this test run](https://github.com/GaloyMoney/galoy/runs/7634630719?check_suite_focus=true):**

chore: bump lightning version to get subscription fixes

---

package.json
yarn.lock

Fix CVE-2022-2564 in mongoose package.
There is more follow up required in https://github.com/flash-oss/medici to complete patching this CVE.  See the PR here for more information https://github.com/flash-oss/medici/pull/74

chore: fix CVE-2022-2564 in mongoose package

---

package.json
yarn.lock

Revert "chore: fix CVE-2022-2564 in mongoose package"

---

src/graphql/error-map.ts
src/services/lnd/index.ts

This PR cleans up our error handling at the boundary between the application service and the graphql api (adapter). It was prompted by [this error message](https://chat.galoy.io/galoy/pl/huh38waxjfga5gb8fknsy8g7uy) below that was leaked through to the frontend.
We also standardise the error message that gets added to `UnknownLightningServiceError` in this PR.
---

refactor: fix exposed error messages via API

---

default.yaml
src/app/wallets/get-balance-for-wallet.ts
src/app/wallets/update-pending-invoices.ts
src/domain/bitcoin/lightning/errors.ts
src/domain/bitcoin/lightning/index.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/domain/wallet-invoices/errors.ts
src/domain/wallet-invoices/index.types.d.ts
src/domain/wallet-invoices/wallet-invoice-builder.ts
src/graphql/error-map.ts
src/servers/cron.ts
src/servers/trigger.ts
src/services/lnd/index.ts
src/services/mongoose/schema.ts
src/services/mongoose/schema.types.d.ts
src/services/mongoose/wallet-invoices.ts
test/e2e/trigger.spec.ts
test/helpers/bitcoin-core.ts
test/helpers/check-is-balanced.ts
test/helpers/lightning.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts
test/integration/services/mongoose/wallet-invoices.spec.ts
test/jest-e2e.setup.js
test/unit/domain/wallet-invoices/wallet-invoice-builder.spec.ts
test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts
test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts

_New changes diff: https://github.com/GaloyMoney/galoy/compare/3703545...hodl-add-single-subscribe_
This is a continuation from #1395 where we need to fix the trigger code for subscribing to hodl invoice `ACCEPT`/`CANCEL` events that don't come through the usual `subscribeInvoices` listener (see [here](https://github.com/lightningnetwork/lnd/issues/3120#issuecomment-1160732579)).
This PR will be to bring back in the #1395 changes and to add the subscribe-to-single-invoice code on top of it to get this feature working.
1. ~New implementation: is there a possibility that we end up with single-invoice subscriptions that don't close (if we somehow skip one of the `removeAllListeners` calls)?~
2. ~Previous implementation: how does the `subscribeInvoices` listener get restarted if it errors and …

feat: switch invoice generation to hodl invoices & external preimages

---

src/app/wallets/get-transactions-by-addresses.ts

Remnant from prior implementation (#1511), `set` is redundant because `getOrSet` handles setting the value just above.

chore: remove redundant redis set

---

src/app/wallets/update-pending-invoices.ts
src/servers/trigger.ts

This PR is to wrap the handle-invoice sub functions in their own spans so that we can collect function-level attributes for each invoice processed.
We are now switching away from `asyncRunInSpan` to `wrapAsyncToRunInSpan` to be able to standardise how we name/namespace things more easily and to be able to flag if a span is a `root` span (doesn't get nested under other spans).
If we import a module like:
-  `import * as Wallets from "@app/wallets"` there is no wrapping
-  `import { Wallets } from "@app"` there is auto wrapping
For this PR, I mixed the two by importing Wallets twice and renaming the one with wrapping at the import level. This was to not doubly wrap `declineHeldInvoices` but also to apply missing wrapping to the other `Wallets` methods in `trigger.ts`.

feat: add spans to update-invoices sub-functions

---

src/app/payments/get-protocol-fee.ts

Once we have a complete `PaymentFlow` object in the fee-estimation use-case we should always be able to return some fee (either calculated or max).

refactor: return partial with fee if PaymentFlow persist fails

---

test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts

Change in stablesats dependency surfaced this, `4` was part of the invoice amount.

fix(test): payment request validation in e2e test

---

src/graphql/main/queries.ts
src/graphql/main/schema.graphql
src/graphql/root/query/ln-invoice-payment-status.ts
src/graphql/root/subscription/ln-invoice-payment-status.ts
src/graphql/types/object/ln-invoice-payment-status-input.ts
test/e2e/servers/graphql-main-server/galoy-pay-testing.spec.ts
test/e2e/servers/graphql-main-server/queries/ln-invoice-payment-status.gql
test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts

Add `lnInvoicePaymentStatus` public query (same behavior and name as its subscription). This will avoid the use of fee probe for status validation (-_-) 
```graphql
query LnInvoicePaymentStatus($input: LnInvoicePaymentStatusInput!) {
status: lnInvoicePaymentStatus(input: $input)
}
```
```grapqhl
{ "input": { "paymentRequest": "lnbcrt500u...k8n2p" } }
```

feat: add invoice payment status query

---

src/app/payments/update-pending-payments.ts
src/app/wallets/index.ts
src/app/wallets/reimburse-failed-usd.ts
src/domain/errors.ts
src/domain/ledger/index.ts
src/domain/ledger/index.types.d.ts
src/domain/shared/index.ts
src/graphql/error-map.ts
src/services/ledger/caching.ts
src/services/ledger/index.ts
src/services/ledger/index.types.d.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/mocks/dealer-price/index.ts
test/unit/payments/payment-flow.spec.ts

_Diff for new changes: https://github.com/GaloyMoney/galoy/compare/e5e7b318d3b4f9d7b83313fa00b03477bf495bc2...reimburse-failed-usd-2_
Retrying the changeset from #1535 (reverted in #1541) with improved tracing to help debug issues.

refactor: reimburse sats on failed USD payment (2)

---

src/app/payments/update-pending-payments.ts
src/app/wallets/reimburse-failed-usd.ts
src/domain/errors.ts
src/domain/ledger/index.types.d.ts
src/graphql/error-map.ts
src/services/ledger/index.ts

This PR fixes the issue that came from the assumption that we would only pass end-user walletIds to the `updatePendingPayment` method. The changes here instead pull the relevant btc wallet reimbursement info from the PaymentFlow created for a given payment hash.

fix: reimburse-usd-payment being dependent on input walletId

---

ci/tasks/test-e2e.sh
ci/tasks/test-integration.sh

fixing only the non vendored files which are used here

fix: all rsync exclude local-regtest-lnd-data

---

src/graphql/main/schema.graphql
src/graphql/root/query/ln-invoice-payment-status.ts
test/e2e/servers/graphql-main-server/galoy-pay-testing.spec.ts
test/e2e/servers/graphql-main-server/queries/ln-invoice-payment-status.gql

update `lnInvoicePaymentStatus` response to enable future updates on response without creating a breaking change

fix: lnInvoicePaymentStatus response

---

src/app/payments/update-pending-payments.ts
src/app/wallets/reimburse-failed-usd.ts
src/domain/shared/errors.types.d.ts
src/domain/shared/index.ts

This PR fixes an issue where the error was being recorded twice from `updatePendingPayment` txn reversals, and the second instance of it (from the return statement) was overwriting the `critical` error level from the first instance in the span attributes.
- [Pre-fix trace](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/tsieg7hWCGz/trace/3D9Ja83hgKA?fields[]=c_name&fields[]=c_service.name&span=954e8400b489147b)
- [Post-fix trace](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/9YihCh4Vrp5/trace/E8jYox5g8mn?fields[]=c_name&fields[]=c_service.name&span=949d04fd9e79953a)

fix: 'critical' status suppressed from reversal transactions

---

src/graphql/error.ts
src/servers/graphql-server.ts

Fix issue where tracing was not getting a graphql error code for shield errors (see after and before here: [traces](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/s2kdND25mhT))
_Found from this query for errors with missing error codes that could become an alert: [query](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/pvvg6LLveDD)_

chore: return error in graphql-shield instead of string

---

src/services/lnd/index.ts
src/services/lnd/onchain-service.ts

Handle `Unknown..` service error that was forwarded to users (see [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/bT7dHGfgeCT)). This is in prep for a new alert.

chore: handle "unknown" lnd connection error

---

src/app/users/login.ts

Reward failed login attempt per phone limit
In testing stablesats' galoy client on staging, we discovered that login attempts (with phone number and authentication code) are rate limited. This PR adds the reward on successful phone+code login.

fix(login): reward failed login attempt per phone limit

---

src/graphql/root/subscription/my-updates.ts
src/graphql/root/subscription/price.ts

This PR is an attempt to find somewhere in the graphql layer where `errors` property is being read from an `undefined` object. Looking at the code, these changes seem like a good first attempt at finding this issue.
Relevant traces: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/xj4WGXgcjpj
_Found from this query for errors with missing error codes that could become an alert: [query](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/pvvg6LLveDD)_

chore(tracing): add check to catch undefined gql 'source'

---

src/app/wallets/get-on-chain-txs.ts
src/app/wallets/get-pending-onchain-balance-for-wallet.ts
src/app/wallets/get-transactions-by-addresses.ts
src/app/wallets/get-transactions-for-wallet.ts
src/app/wallets/index.ts
src/domain/bitcoin/onchain/incoming-tx-handler.ts
src/domain/bitcoin/onchain/index.types.d.ts
src/graphql/admin/schema.graphql
src/graphql/helpers.ts
src/graphql/main/schema.graphql
src/graphql/types/abstract/wallet.ts
src/graphql/types/object/btc-wallet.ts
src/graphql/types/object/usd-wallet.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/unit/domain/bitcoin/onchain/incoming-tx-handler.spec.ts

There is a subset of transactions that is currently not added to our ledger or accounted for in our balances. These are the incoming onchain transactions for a user that haven't met the required number of confirmations onchain as yet.
This PR is to calculate the sum of these pending transactions for a user and expose this balance via a new selection.
If an API user would like to retrieve the pending incoming balance (unconfirmed onchain txns) for a wallet, their only option right now would be to use the `transactions` selection and:
- **paginate until their very 1st transaction**
Because transactions can have different fees at different times, there's no guarantee that a confirmed transaction does not have prior unconfirmed transactions for that wallet still pending before it
- **filter …

feat: add gql selection incoming pending onchain balance

---

src/app/wallets/update-pending-invoices.ts
src/domain/errors.ts
src/graphql/error-map.ts

This is to remove temporary transition code originally added [here](https://github.com/GaloyMoney/galoy/pull/1484/commits/ab09b400de6b03e86ae8066e528c5836ffd014c8) to handle any non-hodl invoices generated by the prior version of the code that needed to be settled with the new version of the code.
I opted to add an error message to detect if non-hodl invoice somehow come into our system instead of removing the check entirely. I'm not sure what circumstances this could happen under (value is [never false](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/6VyrRQbWNwy)), so I'm also ok with removing the check entirely.

chore: replace hodl invoice transition code

---

src/services/tracing.ts

Errors that came back as part of the `data` object in a graphql response weren't being added to the top-level `graphql.error.<attr>` attributes that some of our alerts depend on, but were instead being added to `graphql.<operation>.error.<attr>`. This PR changes this so that:
- data errors are more consistently added under the path `graphql.data.error.<attr>`
- a new `graphql.data.error.<index>.operation.name` was added to persist the `<operation>` sub-path I removed when switching to the new sub-path format here
This PR would also feed into a trigger update ([query](https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/JHgCvW6Gs1q)) for [`unknown-error-code`](https://ui.honeycomb.io/galoy/datasets/galoy-staging/triggers/ArnJY6qQjsC) alert.
Traces:
- [Pre-fix …

chore: fix missing gql attributes in spans

---

src/debug/clean-pending-payments-for-dead-node.ts

Script to clean pending payments leftover from nodes that have been permanently removed for a given environment. Will fix traces like these: https://ui.honeycomb.io/galoy/datasets/galoy-hack/result/defJvEY2iuA

debug: add script to clean pending payments for dead lnd nodes

---

src/domain/bitcoin/index.ts
src/domain/payments/index.ts
src/domain/shared/errors.ts
src/domain/shared/primitives.ts
src/graphql/error-map.ts
src/graphql/types/scalar/cent-amount.ts
src/graphql/types/scalar/sat-amount.ts
test/unit/domain/bitcoin/checked-to-sats.spec.ts
test/unit/domain/payments/index.spec.ts

This PR adds checks in validation methods to make sure values are no greater than a defined max amount. The max amount used was `100,000` BTC since this is the max value that lnd would let you create an invoice for.
These changes were prompted by 2 error message types observed from lnd for the `createHodlInvoice` method with the following amount inputs ([examples traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/6xBE7yPk9wp)):
- (1) `10_000_000_000_001`
`'invoice amount 100000.00000001 BTC is too large, max is 100000 BTC'`
- (2) `1_064_138_827_560_000_000`
`'payments of negative value are not allowed, value is -5772328715153993728'`
- (2) `476_057_064_138_827_560_000_000`
`'payments of negative value are not allowed, value is -1000'`

feat: add max amounts validation for sats/cents inputs

---

src/services/lnd/index.ts
src/services/lnd/onchain-service.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts

Change `KnownErrorDetails` error handling switch from string-based to regex-based matching.
This was prompted by error messages [like these](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/A6XwimZhYiz/trace/dSXA1gVcjan?fields[]=c_name&fields[]=c_service.name&span=400a514d90c78a34) that contain variable details within them. The error to match in this case looked like:
```
"unmatched backend error: -26: too-long-mempool-chain, too many descendants for tx 5a1514156a45546cdda2a0309b6787bfabd13e789e3dc6ea313e51636ecc4d7c [limit: 25]"
```

refactor: change 'KnownErrorDetails' check to a regex

---

src/domain/bitcoin/lightning/index.types.d.ts
src/servers/trigger.ts
src/services/lnd/index.ts

There was an issue where trigger would open new subscriptions for every settled or held invoice and then cancel the subscription if the invoice is settled already. This PR checks for the invoice status before opening the subscription.
Note, lnd automatically deletes canceled invoices with [these settings](https://github.com/GaloyMoney/charts/blob/cd01038b09d99c58bb374b79609d206d4f00148d/charts/lnd/values.yaml#L87) (h/t @openoms):
```
; If true, we'll attempt to garbage collect canceled invoices upon start.
; gc-canceled-invoices-on-startup=true
; If true, we'll delete newly canceled invoices on the fly.
; gc-canceled-invoices-on-the-fly=true 
```
_Honeycomb query showing problem: [link](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/8F2VG9fMbtD)_

fix: trigger firing too many hodl invoice listeners

---

src/domain/ledger/index.types.d.ts
src/services/ledger/index.types.d.ts
src/services/ledger/volume.ts
test/integration/services/ledger/facade.spec.ts
test/integration/services/ledger/helpers.ts
test/integration/services/ledger/service.spec.ts

This PR establishes a baseline to ensure all volumes we have in our codebase are tested for expected behaviour against all our LedgerTransactionType types.
This is partially a cleanup task, and partially in prep for excluding internal "Trade" type transactions from our intraledger volume checks.

test: add ledger volume tests

---

src/app/lightning/get-balances.ts
src/app/wallets/private/get-on-chain-txs.ts
src/domain/bitcoin/onchain/index.ts
src/domain/bitcoin/onchain/index.types.d.ts
src/domain/cache/index.types.d.ts
src/servers/exporter.ts
src/services/cache/local-cache.ts
src/services/cache/redis-cache.ts
src/services/lnd/index.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/services/cache/index.spec.ts

This is a first draft for the fix for issues: #1399, #1528, https://github.com/GaloyMoney/galoy-mobile/issues/548
The issue is that the full `IncomingOnChainTransaction` type isn't persisted in redis, but our code assumes this full type comes back via `get`. There needs to be a translation method somewhere to convert from redis persistence back to our domain type.
This is a first draft demonstrating the fix, but this fix may also be executed via a new repository that is specifically an `IncomingOnChainTransactionsRepository` function.
- Type notes: https://github.com/GaloyMoney/galoy/pull/1529#issuecomment-1239522635
Original object:
```ts
{
confirmations: 0,
rawTx: {
txHash: '688b2092df3c9f451b65d9b0b55515d8c8311559052542b50b4b953755539354',
outs: [Array]
},
fee: 0,
createdAt: …
```

fix: translate OnChainTxns retrieved from cache

---

src/domain/cache/index.types.d.ts
src/domain/index.types.d.ts
src/services/cache/local-cache.ts
src/services/cache/redis-cache.ts

We recently had an issue (see #1662) where an unexpected object was somehow being read out of redis caching. On diving in further into this, I found that the root cause is because the redis `setCache` method can actually cache an `Error` object by just caching its readable properties, and when this is read back out from cache it comes out as a non-Error type object that looks like:
```ts
{ name: "OnChainServiceError", level: "critical" }
```
The fix here is to include a new `NonError` type as part of the `set` method's args signature, and to fix places where this lint breaks.

fix: skip writing errors as serialized objects to cache

---

Makefile
docker-compose.override.yml

I don't think `docker compose up` will return the exit code from the container it's starting.

chore: Fix mongodb migration test return code

---

src/domain/phone-provider/errors.ts
src/graphql/error-map.ts
src/graphql/error.ts
src/services/twilio.ts

Add an error classification for when we can't connect to the phone provider. Was triggered today by Twilio's SMS service (https://status.twilio.com) being down.
Relevant traces: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/CDg5iQEg86M

chore: add PhoneProvider case for connection issues

---

src/graphql/types/scalar/safe-int.ts

Map safe-int validation errors to `ValidationInternalError` to get the proper `code` attribute in tracing and in API returns, see [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/tk5E1i8uuva/a/hWwDryEwE7n) from [`galoy-bbw-missing-error-code`](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/triggers/xcLG5xU5eLm) alert.

fix: map safe-int errors to apollo error

---

src/services/lnd/index.ts

Maps an `UnknownLightningServiceError` ([traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/2PuFyJ4mcdC)) for canceling already settled invoices (will be application no-op).

chore: add 'invoice already settled' lnd error

---

src/domain/errors.ts
src/graphql/error-map.ts
src/services/mongoose/utils.ts

Maps all except "cursor id" errors in [these traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/5zSEGbD2au4?hideMarkers).

chore: map new mongo connection errors

---

src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts
src/services/lnd/onchain-service.ts

- Maps "insufficient balance" errors ([trace](https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/otZJhTGR9xs/trace/cVyR9K87qvu?fields[]=c_name&fields[]=c_service.name&span=c737e4c5a92b93d1))
I didn't set a level for this because we'd likely get a rebalance alert well before this might trigger. I only discovered it while testing on staging with very large amounts.
- Maps "no connection established" error ([traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/rQaiT3siacA))

feat: map new unknown lnd errors

---

src/servers/graphql-server.ts

following log provided by apollo server:
Persisted queries are enabled and are using an unbounded cache. Your server is vulnerable to denial of service attacks via memory exhaustion. Set `cache: "bounded"` or `persistedQueries: false` in your ApolloServer constructor, or see https://go.apollo.dev/s/cache-backends for other alternatives.

chore: bounded cache

---

src/servers/middlewares/auth-router.ts

note: this `/validatetoken` function will only exist during the transition to kratos. once we stopped accepting the `legacyJwt`, this function will disappear. which is why I think the current hacky approach is better suited than adding express opentelemetry collector. the later option would otherwise generated many spans.

chore: instrumenting validationtoken

---

src/servers/graphql-server.ts
src/servers/index.files.d.ts

previously, a 500 Error was thrown without given indication of what the issue was
after this PR, a `UnauthorizedError: No authorization token was found` will be returned if no JWT is been passsed to the server.

chore: improve error message when no token is present

---

.github/workflows/audit.yml
.github/workflows/codeql-analysis.yml
.github/workflows/e2e-test.yml
.github/workflows/generate-graphql-docs.yml
.github/workflows/integration-test.yml
.github/workflows/mongodb-migrate.yml
.github/workflows/nodejs-check-code.yml
.github/workflows/spelling.yml
.github/workflows/unit-test.yml
Dockerfile
Dockerfile-debug
Dockerfile-migrate
Makefile
docker-compose.yml
package.json
test/helpers/apollo-client.ts
yarn.lock

need to be merged before: https://github.com/GaloyMoney/concourse-shared/pull/14

chore: upgrade to note18

---

docker-compose.yml

preceding the change in the charts: https://github.com/GaloyMoney/charts/pull/1846
There are no breaking changes, but a few Taproot related bugs are fixed: https://github.com/lightningnetwork/lnd/blob/v0-15-3-branch/docs/release-notes/release-notes-0.15.3.md

chore: update lnd docker images to v0.15.3-beta

---

docker-compose.yml

On my local machine both stablesats and the integration-deps runner was starting up before mongodb had actually started.  Allowing them to restart on failure gives enough time for mongodb to start.

chore: Fixed integration tests on m1 mac

---

src/app/payments/get-protocol-fee.ts
src/app/payments/helpers.ts
src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/domain/payments/index.types.d.ts
src/domain/payments/payment-flow-builder.ts
test/unit/payments/payment-flow-builder.spec.ts

We've discovered a new dimension of conversion method selection where the decision to use a `buy` or `sell` method is dependent on the sender wallet currency. Our initial fix was to do this switching in the app layer. This PR is to move this selection logic to the LPFB and to unit test these new pathways.

refactor: move conversion fn selection logic from app layer to domain

---

src/services/lnd/index.ts

Update `getClosingChannelsBalance` to include waiting, pending closing and pending force.
@nicolasburtey do you remember why you used `getClosedChannels`?

fix: update closing channel balance to include force closed

---

src/graphql/main/mutations.ts
src/graphql/main/queries.ts
src/graphql/main/subscriptions.ts
src/servers/graphql-server.ts

- moves session context logic out of ApolloServer and into middleware so that all graphql spans will be descendants that inherit session context attributes
- add session attributes to top level subscription fields because they do not execute as children of the express middleware spans

chore: add global attributes to spans

---

src/app/payments/get-protocol-fee.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

This is to not return the `SkipProbeForPubkeyError` error if it pops up from the use-case since it is only being used to switch on logic internally to the use-case (is not actually an error).

refactor: skip return partial error if error is SkipProbeForPubkeyError

---

src/servers/cron.ts

Issue https://github.com/alexbosworth/ln-sync/issues/5 needs resolving before we can use `balanceofsatoshi` on signet - until then the simplest workaround is to disable it.

chore: disable internal channel rebalance on signet

---

src/app/payments/send-intraledger.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

I found that your own account is added as a contact when you do a conversion from USD -> BTC or vice versa.
This change will prevent that from happening in the future.

fix: Prevent adding self as contact

---

src/migrations/2022110622030802-users-to-account.ts
src/services/mongoose/schema.ts

TODO before #1861
now that we're separating `users` and `accounts`, and will introduce a new `user` collection in #1861, it's a good time to remove potential confusion and rename the current `user` collection to `account`

chore!: migrate users collection to account

---

src/graphql/main/schema.graphql
src/services/twilio.ts

the issue came from the fact twilio have an _version property that was creating issue for mongoose who also have a _version property on it's object.
this was creating an infinite loop
recreating the PhoneMetadata object with just the necessary property avoid the issue.
a good reason for the proper boundaries between services

fix: staging, following kratos refactoring PR

---

src/domain/bitcoin/onchain/errors.ts
src/graphql/error-map.ts
src/services/lnd/onchain-service.ts

Adds a new error type for lnd dust error (see [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw?query=%7B%22time_range%22%3A7200%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22service.name%22%2C%22name%22%2C%22error.name%22%2C%22error.message%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22error%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3Atrue%7D%2C%7B%22column%22%3A%22error.level%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22critical%22%7D%2C%7B%22column%22%3A%22service.name%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3A%22galoy-bbw-dealer%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D))

chore: add lnd dust error to parser

---

src/domain/payments/index.types.d.ts
src/domain/payments/onchain-payment-flow-builder.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/unit/payments/onchain-payment-flow-builder.spec.ts

This PR adds the dust check to other parts of the OPFBWithConversion step where btcPaymentAmounts are accessed.

fix: apply dust check for fee estimates as well

---

package.json
yarn.lock

note: maybe we should fork it to limit potential supply chain attack

chore: get an updated version of tscpaths that can silenced output

---

docker-compose.yml

This will downgrade mongodb in dev to v5. This is required because the galoy chart is not able to fit in with the latest mongodb chart (`13.6.1`) and will require some debugging to figure out what values need to be changed.

chore(deps): downgrade mongodb in compose to v5

---

galoy.yaml
src/app/accounts/update-account-ip.ts
src/app/auth/request-phone-code.ts
src/config/schema.ts
src/config/yaml.ts
src/services/ipfetcher/index.ts

axios had a regression that made proxycheck call failed: https://github.com/axios/axios/pull/5306
this prior PR fixes the proxycheck issue: https://github.com/GaloyMoney/galoy/commit/eca59ab0833c09d6d53d3aa3600ce162d683944a
now most `IPType` are not populated with the correct info, so as a result the rewards are not working.
this PR will make a call back to proxychecker if the relevant info is not present.
also, it adds proper open telemetry info

fix: ip check fallback following axios regression

---

src/app/wallets/update-pending-invoices.ts

For no-amount invoices, 0 is a valid amount if the invoice isn't held or settled as yet. This change checks for the invoice status first before validating the sats amount to avoid wrongly erroring for an unpaid/unheld 0-amount invoice.

fix: validate sats amount after checking status of pending invoice

---

src/graphql/connections.ts

This should address the `missing-error-code` alerts we've been seeing: https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/pg2YmhUo27V

fix: use CustomApolloError for checkedConnection fn

---

src/app/auth/request-phone-code.ts
src/domain/phone-provider/index.ts
src/domain/phone-provider/index.types.d.ts
src/domain/users/index.types.d.ts
src/graphql/admin/schema.graphql
src/graphql/main/schema.graphql
src/graphql/root/mutation/captcha-request-auth-code.ts
src/graphql/root/mutation/user-request-auth-code.ts
src/graphql/types/scalar/phone-code-channel-type.ts
src/services/twilio.ts

a new optional channel argument has been added to UserRequestAuthCodeInput and UserRequestAuthCodeInput
when channel is not set, it defaulted to SMS, otherwise WHATSAPP can be used and set. 
~~there are now 2 different mutations:~~
~~- `captchaRequestAuthViaSmsCode`~~
~~- `captchaRequestAuthViaWhatsappCode`~~
~~`captchaRequestAuthCode` is still available but deprecated~~
~~as `userRequestAuthCode` is only used for dev (bypassing captcha), I didn't created two endpoints for this one, as it's also meant to bypass the twilio integration with the use of test codes.~~

feat: whatsapp as an alternative way of receiving code

---

Makefile
dev/stablesats.yml
test/e2e/integration-services/stablesats.spec.ts
test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts
test/helpers/redis.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts
test/integration/02-user-wallet/02-send-lightning-limits.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/app/wallets/invoice.spec.ts
test/integration/services/dealer/hedge-price.spec.ts
test/integration/services/dealer/mid-price.spec.ts
test/mocks/okex-server.ts

This PR is to configure stablesats to use its new in-memory price feed (mocked) and to remove unused redis price publish mock functions.

test: remove okex redis mock & use stablesats in-memory internal mock

---

src/app/wallets/get-on-chain-fee.ts
src/app/wallets/send-on-chain.ts
src/domain/payments/onchain-payment-flow-builder.ts
src/graphql/error.ts
src/graphql/helpers.ts
src/graphql/main/mutations.ts
src/graphql/main/queries.ts
src/graphql/main/schema.graphql
src/graphql/root/mutation/onchain-payment-send-all.ts
src/graphql/root/mutation/onchain-usd-payment-send.ts
src/graphql/root/query/on-chain-tx-fee-query.ts
src/graphql/root/query/on-chain-usd-tx-fee-query.ts
src/graphql/types/object/onchain-usd-tx-fee.ts
src/servers/graphql-main-server.ts
src/servers/middlewares/wallet-id.ts
src/servers/trigger.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/02-user-wallet/02-tx-onchain-fees.spec.ts

This PR builds on the work already done in #1408.
It removes the USD code-path blockers, adds new queries/mutations and integration tests for USD use-cases.
- cherry-pick https://github.com/GaloyMoney/galoy/pull/2094/commits/ff5cca9a708e4bb5c9a8c142b57ccc6e279ef52a for independent PR
- move validate functions to app layer (https://github.com/GaloyMoney/galoy/pull/2072#discussion_r1058588580)
- add hedge cases for onchain where applicable

feat: add onchain stablesats send 🎉 

---

src/graphql/admin/index.ts
src/graphql/admin/mutations.ts
src/graphql/admin/queries.ts
src/graphql/index.ts
src/graphql/main/index.ts
src/graphql/main/mutations.ts
src/graphql/main/queries.ts
src/graphql/main/subscriptions.ts
src/servers/graphql-admin-server.ts
src/servers/graphql-main-server.ts
src/servers/middlewares/wallet-id.ts

This PR organizes the graphql queries and mutation by authentication status and walletId validation before passing into the schema creation method. These same queries/mutations are then used to populate shields and middleware, instead of having to manually maintain these.

refactor: change isAuthenticated and validateWalletId to be deterministic

---

src/app/auth/index.ts
src/app/auth/logout.ts
src/domain/authentication/index.types.d.ts
src/graphql/main/mutations.ts
src/graphql/main/schema.graphql
src/graphql/root/mutation/user-logout.ts
src/services/kratos/auth-phone-no-password.ts
test/e2e/servers/ory/kratos.spec.ts

New graphql mutation for user logout. It only logs the user out of the current session. If a user is logged in on two devices the other device will remain logged in.
```gql
mutation {
userLogout( input: {
authToken: "AUTH_TOKEN"
}) { 
errors {
message
}
authToken
}
}
```

feat: kratos userLogout mutation

---

package.json
src/servers/graphql-server.ts
test/helpers/apollo-client.ts
yarn.lock

previous attempt (https://github.com/GaloyMoney/galoy/pull/1780) was trying to both upgrade the ws socket library to `graphql-ws` and also segregates the ws socket server from the main server (a recommended best practice to get apollo federation to work). 
the second part is the harder part (more code/graphql schema moving around, more to do on the infra side to keep things to map the backend code), and is the reason this PS has not been completed yet.
I instead go with this PR with [this code snippet](https://github.com/enisdenjo/graphql-ws#ws-backwards-compat) that let run both the old and new websocket protocol simultaneously. the goal of this PR is now to only upgrade the websocket library. 
the seggregation of the HTTP server and ws server can be done in another PR later.

feat: ws upgrade (attempt 4)

---

src/servers/graphql-server.ts

currently I'm using the logs when doing local development.
I don't believe we have any meaningful use of logs in prod (given we rely on honeycomb), so local dev is probably the most relevat
with `wrapSerializers: false`, the logs are very long.
really the things that matter for me is to get the body query+variables requests
this PR is reducing drastically the number of output and just show the relevant outputs

chore: make logs more meaningful

---

src/domain/payments/ln-fees.ts
test/helpers/lightning.ts
test/integration/01-setup/01-lightning-channels.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/unit/domain/payments/ln-fees.spec.ts
test/unit/payments/payment-flow-builder.spec.ts

This PR reworks our integration tests to have a node available 1 hop away from the instance node to test hop fees against.

test: add routed payment tests

---

src/services/ledger/tx-metadata.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts

The `usd` property is what we use to return the price to calculate display currencies from for a transaction in the API ([here](https://github.com/GaloyMoney/galoy/blob/7fe52544debec600232333a5bd784d20b4f75782/src/domain/wallets/tx-history.ts#L87)).
This amount has been off since we [pushed](https://github.com/GaloyMoney/galoy/commit/9141102d8ef68a9535e6c67e3b9cb3022e9b1ad2) the onchain-payment-flow-builder. This PR is to correct that for new transactions, and to apply a migration for existing transactions.
The migration here targets all onchain sends with `centsAmount` properties (only since onchain-payment-flow-builder commit). It was moved to a new PR to be deployed after the new code here deploys. The migratiion is a no-op on new code and will only affect transactions created with the …

fix: onchain send 'usd' metadata value

---

src/migrations/20230106142545-fix-onchain-send-usd.ts

**_Supports #2129_**
This migration only targets onchain sends (BTC & USD) that have the new centsAmount & centsFee properties. These would have started with the new onchain-payment-builder flow.
**This will only be merged and deployed after #2129 has been deployed.**

chore: add migration for 'usd' prop in existing onchain sends

---

dev/ory/oathkeeper.yml
docker-compose.yml

@krtk6160 ,
Today the oathkeeper codebase got a PR to fix OTEL tracing here https://github.com/ory/oathkeeper/pull/1049 . I compiled the source and tested it locally and was able to see tracing flowing thru honeycomb!
I pushed a docker image here: https://hub.docker.com/layers/ntheile/oathkeeper/v0.40.1/images/sha256-2aced8081b5fc8648bf9d48affb59fe4245c64b449ca82a81e10f93474331f14?context=explore 
@nicolasburtey  wanted to test this in staging. can you add this to the staging deployment and see if tracing work?
Thanks,

feat: otel oathkeeper tracing

---

src/services/twilio.ts

Unifies error handling across Twilio methods since we've observed common errors popping up in both.
---
**Details on new TooManyConcurrentRequests error**
"Possible causes: Your application is initiating many verifications in a short period of time for the same phone number." https://www.twilio.com/docs/api/errors/60212

refactor: unify twilio err msgs and add new one

---

src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/send-on-chain.ts
src/app/wallets/update-on-chain-receipt.ts
src/app/wallets/update-pending-invoices.ts
src/domain/payments/index.types.d.ts
src/domain/wallet-invoices/index.types.d.ts
src/domain/wallet-invoices/wallet-invoice-receiver.ts
src/domain/wallet-on-chain-addresses/wallet-address-receiver.ts
src/services/ledger/index.types.d.ts
src/services/ledger/tx-metadata.ts
test/integration/02-user-wallet/02-receive-lightning.spec.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/services/ledger/facade.spec.ts
test/integration/services/ledger/helpers.ts
test/unit/services/ledger/domain/tx-metadata.spec.ts

This PR adds the `satsAmount` set of properties to the transaction types that currently don't have it, and it adds tests for metadata on all non-admin transaction types.
The intention is to eventually rely on these and to remove the `fee`, `feeUsd` and `usd` properties from transactions.

chore: add missing amount metadata props

---

src/servers/graphql-main-server.ts

there is no reason to launch a dedicated admin server. it makes local dev more memory/cpu heavy.
this is what kratos is doing and I think this is a preferrable approach - the only downside is that if there is a crash on the admin, currently it won't affect public users. but it will with this refactoring
right now this is just a test, we have to do some work on the CI before doing a broader refactoring of the /server files.

feat: combine both admin and public endpoint in the same server

---

src/migrations/20230116132109-add-sats-amounts-onchain-payments.ts
src/migrations/20230116162612-add-sats-amounts-to-receipts.ts

This PR migrates the satsAmounts-related properties to older `invoice` and `onchain_receipt` type transactions that don't have these as yet. The migration follows the same logic as the one in #2182.
There are currently 3 states of transactions in the system for onchain receipts (receipts with fees):
1. No `satsAmount` props, wrong `usd` prop
2. Correct `satsAmount` props, wrong `usd` value
(introduced #2148)
3. Correct `satsAmount` props, correct `usd` value
(introduced #2157)
The two new states were introduced with recent changes, where new `satsAmount` properties were added and general logic across transactions was cleaned up. The following is an account of where we started from and how we moved through the 2 transitions.
- Before the `satsAmount` changes, we would record the full …

chore: migrate receipts-related sats amounts properties

---

src/app/auth/index.ts
src/services/kratos/cron.ts
src/services/kratos/identity.ts

This PR fixes a bug in kratos `listIdentities` pagination function. The  `response.headers.link` does not return the last page properly.

fix: kratos extend session cron

---

src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/send-on-chain.ts
src/services/ledger/domain/entry-builder.ts
src/services/ledger/domain/index.types.d.ts
src/services/ledger/facade.ts
src/services/ledger/index.types.d.ts
test/integration/services/ledger/helpers.ts
test/unit/services/ledger/domain/entry-builder.spec.ts

This is an split from https://github.com/GaloyMoney/galoy/pull/2190. Allow add additional metadata to receiving account in intra ledger txs (is needed because now the recipient can have a different display currency)

feat: add intraledger credit metadata

---

src/app/shared/mid-price.ts

This was originally added because at the time we would've eventually liked to switch to using the dealer exclusively. With the 'critical' level though, this error triggers our alerting system even though there is no action to be taken.
The error has been demoted to 'warn' so that when we are ready we can monitor passively how often it has been triggered to decide if/how to remove the fallback price service.

refactor: demote dealer mid-price error to 'warn'

---

src/domain/dealer-price/errors.ts

This error should maybe alert when the dealer is unreachable. An idea of how frequently this would alert: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/v7kpwDaLv4a

refactor: set 'NoConnectionToDealerError' to alert

---

test/helpers/lightning.ts
test/integration/01-setup/01-lightning-channels.spec.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

This PR moves our testing checks to higher up in the run where channel policies are actually being set. It also removes an unnecessary setChannelFee call.
This is an intermediate PR that could eventually lead to a PR that tightens up how we set fees on the channel we're targeting based on how flakily these new tests perform.

test: improve flakiness of setChannelFee call

---

src/app/admin/update-user-phone.ts

This PR adds handling for an edge case where the phone provided as an arg to the update phone function is associated with a user object, but is absent from the kratos pg, which was making the previous check for user existence fail.

fix: handle missing edge case in phone update

---

DEV.md
src/migrations/20221010162913-add-self-trade-type.ts
src/migrations/migrate-mongo-config.js

This PR is to follow #1750. It executes the migration for intraledger transactions that were self trades but did not get tagged with this new type before we implemented the self-trade code.
We should do a check of which transactions are currently on the old type and should be the new type pre-migration, and then confirm that these types change as expected post-migration. I've added a rollback migration step as well for in case anything goes wrong from this check.
I can work with Jose maybe to execute this check before we roll out.

chore: migrate remaining intraledger types to self trade

---

src/app/payments/send-lightning.ts
src/app/wallets/send-on-chain.ts
src/services/ledger/index.types.d.ts
src/services/ledger/tx-metadata.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

Add memo provided to ln send metadata:
- prioritize user memo over payment request
- store user memo in `memoPayer` property first, fallback to payment request description
- store payment request description in `memo` first, fallback to user memo

fix: add user memo to ln send metadata

---

src/app/wallets/update-on-chain-receipt.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts

Adds a test and fixes the issue.
Reported: _"have this problem with formatting in the notifications where the onchain pending notification has the right formatting but not the confirmation notification"_

fix: convert onchain receive notification display amount to major unit

---

src/app/accounts/active-accounts.ts
src/app/accounts/send-default-wallet-balance-to-users.ts
src/app/cold-storage/rebalance-to-cold-wallet.ts
src/app/prices/get-current-price.ts
src/app/shared/mid-price.ts
src/app/wallets/update-on-chain-receipt.ts
src/domain/fiat/display-currency.ts
src/domain/fiat/index.types.d.ts
src/servers/trigger.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/notifications/notification.spec.ts
test/integration/services/dealer/mid-price.spec.ts
test/mocks/get-current-price.ts

This PR removes remaining instances of `DisplayCurrencyConverter` and then removes `DisplayCurrencyConverter` implementation.

chore: remove legacy display currency converter

---

src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts

This happens when the destination misses a feature that a feature our node requires depends on.
More: https://github.com/lightningnetwork/lnd/blob/f245591e4bfc18d50326938d1f50bf8dc5fe4771/routing/payment_session.go#L63

chore: add new 'DestinationMissingDependentFeatureError'

---

src/app/payments/update-pending-payments.ts
src/domain/ledger/errors.ts
src/graphql/error-map.ts

See #2151, there are some critical assumptions that depend on there being only 1 pending payment for a payment hash at any given time:
- having only 1 ledger transaction be debited for user for a single lnd payment (failure mode is user gets over-debited)
- accounting for fees correctly if a route changes and fees increase in lnd payment out

chore: add error catch for multiple pending payments for single hash

---

src/app/payments/send-lightning.ts
src/domain/bitcoin/lightning/errors.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/domain/payments/ln-fees.ts
src/domain/shared/primitives.ts
src/graphql/error-map.ts
src/services/lnd/index.ts
test/integration/services/lnd/lnd-service.spec.ts
test/unit/domain/payments/ln-fees.spec.ts

This is to explicitly capture some of the logic around max fees when making routeless payments.
In the case of a payment without a fee probe the max fee should always be enforced as this has implications for how we calculate fee reimbursements. If a max fee at the lnd level exceeds what our fee reimbursement expects then this could be a potential attack vector.
Within the lnd service, to correctly catch this we would need to also be aware of sender wallet currencies and price ratios since the actual amount of sats being sent may be less than the actual sender currency amount being deducted (and the corresponding max fee calculation).
**_A new error and test cases were added to ensure we have this included in the lnd service._**
_Note: This shouldn't change any existing maxFee logic. It …

chore: add max-fee-check errors and tests to lnd service

---

docker-compose.yml
src/config/process.ts
src/migrations/migrate-mongo-config.js
src/services/mongodb/index.ts

compilation and test of the backend on m1/m2 breaks some months ago.
the issue with the docker image from bitnami is that they only contains amd64 binary.
so I'm moving to use the "official" images from mongo and redis as those contains arm64 that works correctly on new Mac.
the downside of using the official images is that there is less configurability. for mongodb, it seems (based on very quick search) that adding user needs some dedicated script and I didn't want to do that/maintain it. 
so I created a branch such that we don't need to have username/password in the docker-compose environement for mongodb.

tests: make build/test work on m1/m2

---

src/services/ledger/paginated-ledger.ts

Attempt to avoid overlapping transactions (with same timestamp) appearing in multiple pages

fix: add '_id' sorting to txns pagination

---

src/domain/payments/ln-fees.ts

Add details from max-fee check to help debug ([trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw?query=%7B%22time_range%22%3A86400%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22service.name%22%2C%22name%22%2C%22error.name%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22error%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3Atrue%7D%2C%7B%22column%22%3A%22error.level%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22critical%22%7D%2C%7B%22column%22%3A%22error.name%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3A%22CouldNotFindExpectedTransactionMetadataError%22%7D%2C%7B%22column%22%3A%22error.name%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22MaxFeeTooLargeForRoutelessPaymentError%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%2 …

chore: add message to MaxFee... error

---

src/app/payments/send-lightning.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts

Handles `verifyMaxFee` error as if it were a `payResult` error in send-lightning use-case.
This is to correct an issue where this error was thrown and the user's payment is stuck as pending since the "revert" code path was never executed. The pending payment also doesn't get picked up by 'updatePendingPayments' since a corresponding lnd payment is never created.
_Note: I added a new test case and jest mock for `verifyMaxFee` that I'm sure can be done in a more elegant way (edit: fixed by @dolcalmi https://github.com/GaloyMoney/galoy/pull/2364/commits/3f710ee66b8ecde8a749756295079503e359c3d9)_

fix: revert payment on verifyMaxFee error

---

src/services/price/index.ts

Fix an issue in price service when wallet currency is equal to display currency

fix: realtime price when wallet currency is equal to display currency

---

src/domain/wallets/tx-history.ts
test/unit/domain/wallets/tx-history.spec.ts

**_Merge after #2334_**
Prompted by the inconsistencies that partially resulted in recent stablesats issue, this PR is to clean up how we calculate a transaction's price by using the available metadata to calculate the price instead of trying to infer what the debit/credit of a transaction means.
_Metadata is now present on all except admin txns: `"fee" | "to_cold_storage" | "to_hot_wallet" | "escrow" | "routing_fee"`._

refactor: improve price calculations for return from API

---

src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/reimburse-failed-usd.ts
src/app/wallets/reimburse-fee.ts
src/app/wallets/send-on-chain.ts
src/services/ledger/index.types.d.ts
src/services/ledger/tx-metadata.ts
test/unit/services/ledger/domain/tx-metadata.spec.ts

This is to remove the remaining `usd` property from intraledger transactions where we no longer use that property anymore (see #2191)

refactor: remove usd from non-admin txn types

---

src/domain/price/index.types.d.ts
src/graphql/main/schema.graphql
src/graphql/types/object/currency.ts
src/services/price/index.ts
src/services/price/protos/price.proto
test/unit/app/prices/list-currencies.spec.ts

Add fraction digits to currency list query
Merge after https://github.com/GaloyMoney/price/pull/41

feat: add fraction digits to currency list

---

src/domain/fiat/display-currency.ts
src/domain/wallets/index.types.d.ts
src/domain/wallets/tx-history.ts
src/graphql/admin/schema.graphql
src/graphql/main/schema.graphql
src/graphql/root/query/realtime-price.ts
src/graphql/root/subscription/my-updates.ts
src/graphql/root/subscription/realtime-price.ts
src/graphql/types/object/business-account.ts
src/graphql/types/object/consumer-account.ts
src/graphql/types/object/transaction.ts
src/graphql/types/scalar/signed-display-amount.ts
src/services/notifications/index.ts
test/e2e/servers/graphql-main-server/queries/main.gql
test/e2e/servers/graphql-main-server/queries/transactions-by-wallet-ids.gql
test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts
test/unit/domain/wallets/tx-history.spec.ts

This PR adds two new selections to the `Transaction` object:
- `settlementDisplayAmount`
- `settlementDisplayCurrency`

feat: add settlement display amount props to gql Transation object

---

src/servers/middlewares/auth-router.ts

This PR fixes the cookie session expiration date. Before it would expire after a few hours. Now it will not expire until the kratos session expires (kratos session lifespan setting, typically 30 days/720h)

fix: cookie expiration date

---

src/domain/dealer-price/errors.ts
src/graphql/error-map.ts
src/graphql/error.ts
src/services/dealer-price/dealer-price.ts

This PR is to add a new dealer error type and to refactor error handling to use regexes.
---
This was prompted from an issue (discovered in #2398) where we received an error when we passed `0` in for `amountToSend` below which has since been fixed in stablesats to simply return `0` instead of the price error.
```
dealerFns.getSatsFromCentsForImmediateSell({
amount: BigInt(amountToSend),
currency: WalletCurrency.Usd,
})
```

chore: add new "no price from dealer" error

---

src/domain/fiat/display-currency.ts
src/domain/payments/price-ratio.ts
src/domain/wallets/tx-history.ts

Removes unnecessary `Number()` calls, and since it's a constant that's never used in division we probably don't need this to be a bigint.

refactor: change MajorExponent type from bigint to Number

---

galoy.yaml
src/config/schema.ts

checked with sam on the app/play store that version 362 is a recent stable version of the apk and ipa.

chore: update default mobile min build versions

---

src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/payments/update-pending-payments.ts
src/app/wallets/reimburse-failed-usd.ts
src/app/wallets/reimburse-fee.ts
src/app/wallets/send-on-chain.ts
src/app/wallets/update-on-chain-receipt.ts
src/app/wallets/update-pending-invoices.ts
src/domain/fiat/index.types.d.ts
src/domain/ledger/errors.ts
src/graphql/error-map.ts
src/services/ledger/domain/entry-builder.ts
src/services/ledger/domain/index.types.d.ts
src/services/ledger/facade.ts
src/services/ledger/index.types.d.ts
src/services/ledger/tx-metadata.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/services/ledger/facade.spec.ts
test/integration/services/ledger/helpers.ts
test/integration/services/ledger/helpers.type.d.ts
test/integration/services/ledger/service.spec.ts
test/unit/services/ledger/domain/entry-builder.spec.ts
test/unit/services/ledger/domain/tx-metadata.spec.ts

This PR separates display amounts across transaction entries based on different user account default display currency settings.
For context each given transaction (journal) is made up of multiple entries in our `medici_transactions` collection:
- (user) sender/recipient entry for external transactions
- (user) optional recipient/sender counter-entry for intraledger transactions
- (internal) bank owner entry for fees
- (internal) lnd entries for external transactions
- (internal) dealer entries for stablesats transactions
The approach taken in this PR is to:
- assign display properties for user-entries based on user-account default currency settings
- assign display properties for internal-entries based on second non-btc system wallet currency (currently USD)
This has meant touching code …

refactor: separate send/receive display intraledger metadata

---

src/migrations/20230319091251-add-sats-amounts-to-intraledger.ts

Add missing migration for `on_us` and `onchain_on_us` transaction for `satsAmount` related properties. This migration follows from the  migration scripts for previous migrations.
To test this locally I manually edited `on_us` and `onchain_on_us` txns in the db to remove all `satsAmount` related props and to add `usd`/`feeUsd`/`fee` properties with the appropriate pre-migration values.

chore(migration): add sats amount props to intraledger txns

---

src/domain/wallets/index.types.d.ts
src/domain/wallets/tx-history.ts
test/unit/domain/wallets/tx-history.spec.ts

This PR fixes the issue where we're adding an invalid `""` value when the value isn't present

fix: `displayCurrency` not present in ledger transaction

---

src/app/accounts/active-accounts.ts
src/app/accounts/send-default-wallet-balance-to-users.ts
src/app/cold-storage/rebalance-to-cold-wallet.ts
src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/send-on-chain.ts
src/app/wallets/update-on-chain-receipt.ts
src/domain/fiat/display-currency.ts
src/domain/shared/index.types.d.ts
src/domain/shared/primitives.ts
src/domain/wallets/tx-history.ts
src/servers/trigger.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/notifications/notification.spec.ts

This is mostly a housekeeping PR to:
- ensure we use wallet vs. display price ratio in appropriate places
- clean up the interface for `minorToMajorUnit` interface to not expose `NewDisplayAmount` internals

chore: cleanup wallet & display price ratios

---

dev/ory/oathkeeper_rules.yaml

This PR fixes the oathkeeper cookie rules. No need to check the cookie on the `/auth/login`or `logout` routes. Without this rule it falsey checks any cookie (_ga cookies) and returns 401.
See related PR comment https://github.com/GaloyMoney/galoy-deployments/pull/3292#issue-1636753015

fix: oathkeeper cookie rules

---

src/graphql/main/queries.ts
src/graphql/main/schema.graphql
src/graphql/root/query/on-chain-usd-tx-fee-query-as-sats.ts
test/integration/02-user-wallet/02-tx-onchain-fees.spec.ts

Adds the complementary fee probe query for new `onChainUsdPaymentSendAsBtcDenominated` mutation in #2491

feat: add 'onChainUsdTxFeeAsBtcDenominated' query

---

src/servers/cron.ts

Undoing these changes for now because they still don't solve the problem of if the process is interrupted (times out) and the span never gets completed/posted.

revert: refactor cron methods

---

src/domain/errors.ts
src/graphql/error-map.ts
src/servers/cron.ts
src/services/tracing.ts

This PR is a continuation of efforts from #2503 to track if a cron task has timed out via an external process kill. It consists of two parts:
- adding the `jobCompleted` attribute to the span and only setting to true when the task has either completed or errored
- adding process listeners to export the current span if the process has been killed prematurely with `activeDeadlineSeconds` from k8s. The SIGTERM listener should allow for span flush and [graceful shutdown](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace).

feat: export task span on cron process kill

---

src/app/lightning/payment-status-checker.ts
src/graphql/main/schema.graphql
src/graphql/root/query/ln-invoice-payment-status.ts
src/graphql/root/subscription/ln-invoice-payment-status.ts
src/graphql/types/scalar/invoice-payment-status.ts
test/e2e/servers/graphql-main-server/galoy-pay-testing.spec.ts

Add EXPIRED to InvoicePaymentStatus, this is required in galoy pay to give feedback to the user specially for USD invoices (when default wallet is stablesats)

feat: add expired to invoice status

---

src/domain/bitcoin/lightning/errors.ts
src/graphql/error-map.ts
src/services/lnd/index.ts

lightning library stuck when trackpayment response does not have a HTLC (lnd error). this is an issue in cron because it get stuck and is killed by timeout
ref: https://github.com/alexbosworth/lightning/issues/133

fix: add timeout to getPayment

---

src/domain/payments/ln-fees.ts
test/unit/domain/payments/ln-fees.spec.ts

This fix changes the verifyMaxFee calc to mirror how payment flow gets to a max fee from a USD sender amount.

fix: change usd internal calc verifyMaxFee

---

package.json
src/app/admin/update-user-phone.ts
src/app/payments/update-pending-payments.ts
src/app/wallets/get-balance-for-wallet.ts
src/domain/ledger/index.types.d.ts
src/graphql/types/object/btc-wallet.ts
src/graphql/types/object/usd-wallet.ts
src/servers/trigger.ts
src/services/ledger/index.ts
test/helpers/lightning.ts
test/helpers/wallet.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
yarn.lock

Remove `updatePendingPaymentsByWalletId` from getBalance
----
Pending:

refactor: remove update pending payments from get balance

---

src/app/payments/send-lightning.ts
src/domain/payments/ln-fees.ts
test/unit/domain/payments/ln-fees.spec.ts

This is to remove any potential inconsistencies from trying to calculate this from the price ratio. For context, the max fees in the verifyMaxFee function should follow how these values are calculated in payment-flow-builder. See [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/sqBQjaLEDJV).

fix: pass in usd amount to verifyFee explicitly

---

galoy.yaml
src/app/accounts/create-account.ts
src/config/schema.ts
src/config/schema.types.d.ts
src/config/types.d.ts
src/config/yaml.ts
test/helpers/user.ts
test/integration/app/users/user-wallets.spec.ts

- if userId is an even number assign BTC default wallet, otherwise assign USD
- this will be used as part of an A/B test to analyze retention and spending for different default currencies

chore: randomly assign default wallet currencies

---

src/app/payments/send-lightning.ts
src/domain/payments/ln-fees.ts
test/unit/domain/payments/ln-fees.spec.ts

This PR adds a previously unhandled edge case when a usd send's fees are calculated from a btc amount [here](https://github.com/GaloyMoney/galoy/blob/35c7516c80ec1a0e3800ce2de521ccbe2ae5e711/src/domain/payments/payment-flow-builder.ts#L171)

fix: verifyMaxFee when usd send is calculated from btc amount

---

ci/pipeline.yml

related to https://github.com/GaloyMoney/galoy/pull/2596#discussion_r1189138253
ci needs to be repiped once merged

chore: rename bria folder

---

galoy.yaml
src/app/payments/helpers.ts
src/app/payments/send-intraledger.ts
src/config/index.types.d.ts
src/config/schema.ts
src/config/schema.types.d.ts
src/config/yaml.ts
src/domain/bitcoin/lightning/index.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/domain/bitcoin/lightning/ln-invoice.ts
src/domain/payments/index.types.d.ts
src/domain/payments/payment-flow-builder.ts
test/integration/02-user-wallet/02-send-lightning.spec.ts
test/unit/payments/payment-flow-builder.spec.ts

This is to address the issue where fee probes fail to Breez when an on-the-fly channel needs to be created for the end-user. Something we noticed is that these invoices have route hints where the non-existent channel's id is `1x0x0`. This PR is to add this heuristic to our code when deciding which fee probes to skip.
Breez's LSP has a solution for handling probes [here](https://github.com/breez/lspd#probing-support) where they ask that the payment hash included in the probe is formatted in a certain way. This would also help in the case where for e.g. the mobile app is offline, but this could potentially add significant complexity to our fee-probing logic and we still wouldn't be able to make the actual payment if the app is offline.

feat!: include route channel ids in skipFeeProbe checks

---

Dockerfile
Dockerfile-debug
Dockerfile-websocket

fix issue with distroless images
nodejs 20: https://github.com/GoogleContainerTools/distroless/tree/main/nodejs
debug images: https://github.com/GoogleContainerTools/distroless#debug-images

fix: udpate distroless images

---

src/domain/users/languages.ts

It was an error on the server side
I discovered it when I added a try-catch block to the language screen, when we update the language - 
```
<ListItem
key={language}
bottomDivider
containerStyle={styles.container}
onPress={async () => { 
if (language !== languageFromServer) {
try {
const { data } = await updateLanguage({
variables: { input: { language } },
})
if (data.userUpdateLanguage.errors && data.userUpdateLanguage.errors.length > 0) {
console.log('Error updating language: ', data.userUpdateLanguage.errors)
} else {
setNewLanguage(language)
}
} catch (err) {
console.error('Error updating language: ', err)
}
}
}}
>
```
This logged: Error updating language: Invalid value for language

fix: switching to serbian language fixed

---

ci/tasks/open-bump-proto-pr.sh
ci/tasks/sync-proto.sh

The combination of tag_regex and paths seems to not be working correctly and the sync job is being triggered on each tagged commit, instead of only on the tagged commits that change the proto files.

ci: exit gracefully on no proto diff

---

src/app/wallets/create-on-chain-address.ts
src/domain/wallet-on-chain/index.types.d.ts
src/services/mongoose/wallet-on-chain-addresses.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/02-user-wallet/02-tx-display.spec.ts
test/integration/02-user-wallet/02-tx-onchain-fees.spec.ts
test/integration/app/trigger/trigger.fn.spec.ts

With the introduction of `requestId` and the usage of `createAddress` in the finally section of our add-settled use-case now, the limiter in the createAddress function was badly placed and being wrongly triggered after many expected createAddress re-runs resulting in `OnChainAddressCreateRateLimiterExceededError` errors being thrown.
This PR fixes the limiter placement to accommodate for this, and it also adds a change to prevent multiple address values from being pushed to the addresses array in persistence.

fix: shift limit check in create address function

---

src/app/wallets/update-on-chain-receipt.ts
src/domain/wallets/index.types.d.ts
src/graphql/types/object/transaction.ts
src/services/mongoose/wallet-onchain-pending-receive.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts

We derived from just `transactionHash` before which is no longer unique as we parse each vout as a unique transaction now. This PR fixes that.

fix: avoid duplicate pending tx ids by deriving from 'txHash:vout'

---

src/app/wallets/get-last-on-chain-address.ts

We call the `createOnChainAddress` function from the `lastOnChainAddress` method if no previous address was recorded. This PR makes it so that the first address that is created for a wallet has a `requestId` with the value of the wallet's `walletId` to help with idempotency of this specific call.

chore: add walletId as onchain create requestId on 1st create

---

src/app/wallets/add-settled-on-chain-transaction.ts
src/domain/ledger/index.types.d.ts
src/services/ledger/index.ts
src/services/ledger/index.types.d.ts
src/services/ledger/schema.ts
src/services/ledger/schema.types.d.ts
src/services/ledger/tx-metadata.ts

Rename `request_id` in application code to be more generic in or ledger so that it can be re-used for other transaction types like payouts.
Migration (https://github.com/GaloyMoney/galoy/pull/2711/commits/ac16a837ddd59e9f9528eeda63a6fd8deec5d017) will be added in a follow-up PR for smoother transition.

chore: rename request id in schema

---

src/migrations/20230603185541-ledger-request-id.ts
src/services/ledger/index.ts
src/services/ledger/schema.ts
src/services/ledger/schema.types.d.ts

Second part of `request_id` schema migration (see PR #2711)

chore: migrate request id in schema

---

src/app/lightning/get-balances.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/services/lnd/index.ts

return from lightning library
```
return cbk(null, {
channel_balance: Number(getSummary.local_balance.sat),
channel_balance_mtokens: getSummary.local_balance.msat,
inbound: Number(getSummary.remote_balance.sat),
inbound_mtokens: getSummary.remote_balance.msat,
pending_balance: Number(getSummary.pending_open_local_balance.sat),
pending_inbound: Number(getSummary.pending_open_remote_balance.sat),
unsettled_balance: Number(getSummary.unsettled_local_balance.sat),
unsettled_balance_mtokens: getSummary.unsettled_local_balance.msat,
});
```
so channel_balance is local balance and not channel capacity

fix: channels outbound balance

---

src/servers/middlewares/auth-router.ts
test/e2e/generated.ts
test/e2e/integration-services/device-account.spec.ts

1. removes deviceId from POST `/auth/create/device-account`
2. e2e test for deleting device account

chore: remove deviceId from create/device-account post

---

src/servers/event-handlers/bria.ts
src/services/ledger/facade/onchain-send.ts
src/services/mongoose/utils.ts

2 issues:
- Error handling was assuming `BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer` but at least in my environment it was only returning `Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer`
- LedgerFacade.setOnChainTxPayoutId without await, this returned a promise so it never was a NoTransactionToUpdateError

fix: add journalId valiation to payoutSubmittedEventHandler

---

src/app/payments/send-lightning.ts
src/domain/errors.ts

fix keybase://chat/galoymoney#incident/6029
-  call updateLightningPaymentFlow synchronously 
- Update CouldNotUpdateLightningPaymentFlowError level

fix: call sync updateLightningPaymentFlow + update error level

---

src/app/wallets/send-on-chain.ts
src/domain/wallets/index.types.d.ts
src/services/ledger/facade/tx-metadata.ts
src/services/ledger/index.types.d.ts
test/integration/02-user-wallet/02-bria-handlers.spec.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts
test/integration/02-user-wallet/02-send-onchain.spec.ts
test/integration/services/ledger/helpers.ts
test/unit/services/ledger/domain/tx-metadata.spec.ts

This PR removes the temporary transaction hash we set for onchain payments and it allows that field to be `undefined` until an actual transaction hash is available.

chore: remove temporary onchain transaction hash

---

src/domain/pubsub/index.types.d.ts
src/graphql/root/subscription/ln-invoice-payment-status.ts
src/graphql/root/subscription/my-updates.ts
src/graphql/root/subscription/price.ts
src/graphql/root/subscription/realtime-price.ts
src/services/pubsub.ts

the test is failing on galoy-pay because it uses the subscription to get the status of an invoice, and the result never comes. 
this is because the `publishImmediate` (now renamed publishDelayed) was trigger because the listener was in place.
this fix one of the many flacky issues in the current e2e test,
unfortunately the fix is still a hack but I don't see a good way to solve this issue otherwise (except a broader change of design)

tests: fix timeout 90s in galoy-pay

---

src/app/wallets/settle-payout-txn.ts
src/services/ledger/facade/onchain-send.ts

This PR accommodates ledger states where the dealer (or any non-end-user) wallet is the one sending an onchain payment.

fix: accommodate dealer onchain send events

---

src/app/wallets/get-pending-onchain-balance-for-wallet.ts
test/integration/02-user-wallet/02-receive-onchain.spec.ts

This PR handles the cases where there are no pending incoming txns for the queried wallets

fix: pending incoming balance for zero txns incoming

---

src/app/wallets/add-invoice-for-wallet.ts
src/app/wallets/index.types.d.ts
src/domain/bitcoin/lightning/invoice-expiration.ts
src/domain/errors.ts
src/domain/primitives/index.ts
src/domain/primitives/index.types.d.ts
src/domain/wallet-invoices/index.types.d.ts
src/domain/wallet-invoices/wallet-invoice-builder.ts
src/graphql/error-map.ts
src/graphql/main/schema.graphql
src/graphql/root/mutation/ln-invoice-create-on-behalf-of-recipient.ts
src/graphql/root/mutation/ln-invoice-create.ts
src/graphql/root/mutation/ln-noamount-invoice-create-on-behalf-of-recipient.ts
src/graphql/root/mutation/ln-noamount-invoice-create.ts
src/graphql/root/mutation/ln-usd-invoice-create-on-behalf-of-recipient.ts
src/graphql/root/mutation/ln-usd-invoice-create.ts
src/graphql/types/scalar/minutes.ts
test/unit/domain/bitcoin/lightning/invoice-expiration.spec.ts
test/unit/domain/wallet-invoices/wallet-invoice-builder.spec.ts

Use case from mattermost
> we want to add lightning to our list of crypto/fiat options available for customers to make payments for services/products via a generated QR code.  For a payment, a fixed amount is generated which must be paid before a set time (e.g. 10mins) elapses. If it is not paid, we invalidate it and regenerate an updated amount if the user is still interested in paying. Now because an expired payment has been invalidated, a customer will not be able to make a successful payment even if they somehow still have the initial QR code.
> 
> However, because we cannot set an expiry for an lnInvoice, a customer that still has a QR code generated from the lightning's payment request will be able to make payment way past our desired expiry time.
- Update invoice builder (including …

feat: add invoice expiration

---

src/domain/phone-provider/errors.ts
src/graphql/error-map.ts
src/services/twilio.ts

FIx twilio unhandled error https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/adXD4GaRNqL/a/frwc6qPYuTJ
There is now way to know the details through api so we can only return 1 error for expired, approved or max attemps) https://www.twilio.com/docs/verify/api/verification-check#check-a-verification

fix: add handler for invalid or approved verification error

---

src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/add-invoice-for-wallet.ts
src/app/wallets/create-on-chain-address.ts
src/app/wallets/get-last-on-chain-address.ts
src/app/wallets/send-on-chain.ts
test/integration/app/wallets/add-invoice-for-wallet.spec.ts
test/integration/app/wallets/create-on-chain-address.spec.ts
test/integration/app/wallets/get-last-on-chain-address.spec.ts
test/integration/app/wallets/send-intraledger.spec.ts
test/integration/app/wallets/send-lightning.spec.ts
test/integration/app/wallets/send-onchain.spec.ts

**_Note: This PR felt like the pre-cursor to thinking about introducing authorization in the backend_**
This PR implements various account-locked checks in different use-cases for both senders and recipients.
We now have account checks that block:

feat: implement account checks

---

test/helpers/shared.ts
test/legacy-integration/01-setup/01-connection.spec.ts

Bria gets bootstrapped on container startup. This adds a test with a wait to check for bria successful bootstrap.

test: add connects-to-bria check

---

src/services/kratos/errors.ts

this is trigger on staging because we try to remove the email, even it doesn't exist.
this action is intended in order to make sure the email is not set, as otherwise the mobile e2e test would fail.
the e2e tests assumes the email is not set and set it on its own

chore: remove a critical kratos alert

---

src/debug/gqlsubscribe.ts
test/bats/gql/real-time-price-sub.gql
test/bats/helpers/setup-and-teardown.bash
test/bats/public.bats

This PR is to remove the `no-auth-requests.spec.ts` file.

test: add missing public e2e bats checks

---

src/graphql/admin/schema.graphql
src/graphql/admin/types/object/user.ts

`phone` is now an optional user field with the introduction of device accounts. This was trigger by [these alerts](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/zA8QVC4hfva).

chore: make 'phone' nullable in admin schema

---

dev/ory/oathkeeper_rules.yaml
src/app/authentication/index.types.d.ts
src/app/authentication/login.ts
src/app/authentication/ratelimits.ts
src/domain/authentication/cookie.ts
src/domain/authentication/index.types.d.ts
src/domain/users/index.types.d.ts
src/servers/authorization/cookies.ts
src/servers/authorization/email.ts
src/services/kratos/auth-email-no-password.ts
src/services/kratos/cookie.ts
test/e2e/servers/ory/kratos.spec.ts

Enables email cookie login at this new rest endpoint `/email/login/cookie`
```
const session = await ajax.post(config.galoyAuthEndpoint + "/email/login/cookie", {
emailLoginId,
code,
})
```
TODO

feat: email cookie login

---

src/app/accounts/mark-account-for-deletion.ts

small fix to remove deleted accounts from businessMapMarkers query

fix: remove title and coordinates on account deletion

---

src/servers/event-handlers/bria.ts

I'm planning to use these to create an easily accessible honeycomb view for our event queue that looks like: https://ui.honeycomb.io/galoy/datasets/arvin-dev/result/3v7BM4QcYVz

chore: add event details to tracing

---

src/config/process.ts
src/servers/graphql-server.ts

I think this was an artefact of the websocket integrated in the main backend. not sure this is needed any more. we can deploy and see if this generate new errors regarding to timeout or websocket

chore: remove keep alive timeout

---

src/domain/accounts/index.types.d.ts
src/domain/primitives/index.types.d.ts
src/graphql/types/object/business-account.ts
src/graphql/types/object/consumer-account.ts
src/services/mongoose/accounts.ts
src/services/mongoose/schema.ts
src/services/mongoose/schema.types.d.ts
test/unit/domain/wallets/payment-input-validator.spec.ts

Add uuid to account schema before uuid migration.
- Add uuid to mongoose schema with default value (random UUID)
- Add default value to translateToAccount using `uuid-by-string`. This avoids a 3rd PR to update graphql.
- After migration the new field can be required (including field type in schema record type)

feat: add uuid to account schema

---

src/services/mongoose/schema.ts

fix index to include only documents that have uuid

fix: add sparse to uuid index

---

src/servers/graphql-server.ts

it used to be relevant when the device account initiation was done throught graphql but it has been moved to rest

chore: condition is no longer relevant

---

test/bats/oathkeeper.bats

This refactors the oathkeeper endpoint check to go in order of : env variable -> custom.yaml -> galoy.yaml (default config) (#3020 & #3022)
**This will need to be cleaned up when @nicolasburtey #3008 PR gets merged.** 
_Note: it looks like `OATHKEEPER_PORT` isn't used anywhere_

test: check env for oathkeeper endpoint before config

---

package.json
yarn.lock

Fixes `yarn audit` breakage: https://www.npmjs.com/advisories/1092873

chore: upgrade import-in-the-middle

---

test/helpers/ledger.ts
test/integration/app/wallets/send-lightning.spec.ts
test/legacy-integration/02-user-wallet/02-send-lightning.spec.ts

This is a continuation from #2999 where we are continuing to move or remove legacy integrations tests from the `send-lightning` test cases.

test: clean up legacy send ln integration test cases

---

test/bats/ln-send.bats

Is unlocked by https://github.com/GaloyMoney/galoy-deployments/pull/4614

chore: unskip test after adding 'xxd' to CI

---

Makefile

`docker compose` has shifted to streaming logs of all services back when using `up` command. Using `--attach` will restrict it to its previous behaviour.

ci: remove non-test output

---

package.json
src/servers/cron.ts
src/services/lnd/utils-bos.ts
yarn.lock

- bos has a lot of dependency. removing those dependency will just lead to a faster build
- bos has weird workaround for which I stumble upon when doing a refactoring and lost couple of hours (https://github.com/GaloyMoney/galoy/pull/3106/files#diff-5c15ecd6e3be10f7e0e38713d90df35946654db4f70840c5df95655464e0ad79L83)
- for rebalancing, we can just create an invoice and pay it with "lightning" package
- for node reconnect, I know this was an issues at time with a much older version of lnd. I don't think if it's still an issue. maybe something to monitor but I don't think it has to be part of the cron.

chore: removing bos as a dependency

---

src/app/admin/send-admin-push-notification.ts
src/domain/notifications/index.types.d.ts
src/graphql/admin/root/mutation/admin-push-notification-send.ts
src/graphql/admin/schema.graphql
src/services/notifications/index.ts

This PR allows the admin push notification mutation to accept a data payload. This data payload can be used to send to the mobile client for the deep linking use case to navigate to the circles page.
```
mutation AdminPushNotificationSend {
adminPushNotificationSend(input: {
accountId: "12345",
body: "Body",
title: "Title",
data: {
notificationType: "InnerCircleGrew",
},
}) {
errors {
code
message
}
success
}
}
```

feat: add data field to admin push notification

---

src/app/lightning/get-held-invoices.ts
src/app/lightning/index.ts
src/domain/bitcoin/lightning/index.types.d.ts
src/servers/exporter.ts
src/servers/trigger.ts
src/services/lnd/index.ts

- Add held invoices count to exporter
- Refactor listInvoices in lnd service to get only invoices in the last 24h (default value for btc invoices) -> impact in performance https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/wYkcvsJ3AyP/trace/FRQFckMZxLo?fields[]=c_name&fields[]=c_service.name&span=f60e2dd69019c170 (if it is only used in trigger start up is not a problem but in exporter can impact performance)

feat: add held invoices count to exporter

---

src/app/payments/reimburse-fee.ts
src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/add-pending-on-chain-transaction.ts
src/app/wallets/add-settled-on-chain-transaction.ts
src/app/wallets/send-on-chain.ts
src/app/wallets/update-pending-invoices.ts
src/domain/fiat/display-amounts-converter.ts
src/domain/fiat/display-currency.ts
src/domain/fiat/index.ts
src/domain/fiat/index.types.d.ts
src/domain/fiat/primitives.ts
src/domain/payments/price-ratio.ts
test/legacy-integration/02-user-wallet/02-bria-handlers.spec.ts
test/legacy-integration/02-user-wallet/02-receive-onchain.spec.ts
test/unit/domain/fiat/display-amounts-converter.spec.ts

This PR adds a new unit tested `DisplayCurrencyConverter` object and then swaps it into all use-cases that have this conversion implemented in-line.
The prompt for this was to stop explicitly integration testing this conversion for each use-case like we do now, and to instead test it once via a unit test.
It also adds a new switching decision for USD display currencies internally in the converter which will eventually allow removing this from our `Metadata` functions in a follow-on PR.

chore: refactor display amounts conversion

---

src/app/payments/get-protocol-fee.ts
src/app/payments/helpers.ts
src/app/payments/send-intraledger.ts
src/app/payments/send-lightning.ts
src/app/wallets/get-on-chain-fee.ts
src/app/wallets/send-on-chain.ts
src/app/wallets/update-pending-invoices.ts
src/domain/errors.ts
src/domain/payments/errors.ts
src/domain/payments/index.types.d.ts
src/domain/payments/onchain-payment-flow-builder.ts
src/domain/payments/payment-flow-builder.ts
src/domain/wallet-invoices/index.types.d.ts
src/domain/wallet-invoices/wallet-invoice-receiver.ts
src/graphql/error-map.ts
test/integration/app/wallets/send-intraledger.spec.ts
test/integration/app/wallets/send-lightning.spec.ts
test/integration/app/wallets/send-onchain.spec.ts
test/legacy-integration/services/dealer/hedge-price.spec.ts
test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts
test/unit/payments/onchain-payment-flow-builder.spec.ts
test/unit/payments/payment-flow-builder.spec.ts

This is the 2nd iteration on handling sub-1-cent incoming transactions to usd wallets (see #3158). The 1st iteration implemented the logic to switch recipient wallets to btc in use-cases, with integration & e2e tests. This iteration instead does this switching inside builder objects, with unit tests.
We currently return an error and don't credit the USD wallet or settle the invoice. This PR is to instead settle the sats to BTC wallet instead of returning an error in the following cases:

feat: switch to btc wallet for sub 1 cent usd receipts

---

src/graphql/public/types/object/business-account.ts
src/graphql/public/types/object/consumer-account.ts

WalletIds is a nullable field, but currently we only check if it is undefined.

fix: properly handle null walletIds

---

src/servers/trigger.ts

Uses similar strategy to setupPaymentSubscribe to avoid missing invoices when trigger is restarted/deployed

fix: trigger restart invoices issue

---

src/servers/graphql-main-server.ts
src/servers/middlewares/session.ts
src/servers/ws-server.ts

- I don't think it make sense to throw in the middleware
- I don't think it make sense to wrap the error in `mapError`
- passing the error to next when it arise.

fix: crash on error in sessionPublicContext

---

core/api/package.json

This removes a resolution that was first introduced while we waited for medici to upgrade their deps to address an upstream vulnerability.
See https://github.com/GaloyMoney/galoy/pull/2912

chore: remove mongoose resolution

---

core/api/dev/ory/kratos.yml
core/api/src/services/kratos/totp.ts
core/api/test/bats/auth.bats

adding 2fa requires privilege session.
for now, we elevate the session when we add totp (the same way we do when we remove totp).
as a follow up, eventually, we should re-authenticate the user when doing those operations. 
this PR removes an active alert everytime someone try to set up 2fa.

fix: #3311

---

core/api/src/domain/wallet-invoices/index.types.d.ts
core/api/src/domain/wallet-invoices/wallet-invoice-builder.ts
core/api/src/services/mongoose/schema.ts
core/api/src/services/mongoose/schema.types.d.ts
core/api/src/services/mongoose/wallet-invoices.ts
core/api/test/integration/app/wallets/send-lightning.spec.ts
core/api/test/integration/app/wallets/update-pending-invoices.spec.ts
core/api/test/legacy-integration/services/mongoose/wallet-invoices.spec.ts

- start recording payment requests with each wallet invoice
- this pr will be followed by a migration and then a pr to make paymentRequest mandatory

chore: record paymentRequest with WalletInvoice

---

core/api/src/services/lnd/errors.ts
core/api/src/services/lnd/index.ts

From [trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw?query=%7B%22start_time%22%3A1697489035%2C%22end_time%22%3A1697489733%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22service.name%22%2C%22name%22%2C%22error.name%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22error%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3Atrue%7D%2C%7B%22column%22%3A%22error.level%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22critical%22%7D%2C%7B%22column%22%3A%22error.name%22%2C%22op%22%3A%22!%3D%22%2C%22value%22%3A%22CouldNotFindExpectedTransactionMetadataError%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D)

chore: add 'PaymentPathfindingFailedToFindPossibleRoute' error handling

---

core/api/src/domain/users/phone-metadata-validator.ts
core/api/src/services/twilio-service.ts

To accommodate traces [like this](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/nE1MygZ55nf/trace/DYKBR5EjFYN?fields[]=c_name&fields[]=c_service.name&span=5bc454ee89c76aa2)

chore: improve twilio 'InvalidMobileNumber' regex

---

apps/consent/app/consent/page.tsx
apps/consent/app/login/page.tsx

This is the equivalent to what we had to do in the web wallet here: https://github.com/GaloyMoney/web-wallet/blob/5bb016a1adbe556ae4d09070daa3c18fb9599ce9/src/components/pages/login-email.tsx#L75 (ie pass options down to axios to forward cross site cookies)

fix: add axios option withCredentials to acceptOAuth2LoginRequest

---

core/api/src/app/admin/index.ts
core/api/src/graphql/admin/queries.ts
core/api/src/graphql/admin/root/query/account-details-by-user-id.ts
core/api/src/graphql/admin/schema.graphql
core/api/test/bats/admin-gql/account-details-by-account-id.gql
core/api/test/bats/admin-gql/account-details-by-user-id.gql
core/api/test/bats/admin.bats

subgraph that need authenticated are been returned a signed JWT that contain the subject/userId returned from oathkeeper.
so that subgraph can do operation on the account, we need to expose a way to do the mapping userId --> accountId through the admin api
this PR update expose this ability

feat: adding a fetchByUserId admin endpoint

---

core/api/src/graphql/error-map.ts
core/api/src/servers/event-handlers/bria.ts
core/api/src/services/bria/errors.ts
core/api/src/services/bria/event-handler.ts
core/api/src/services/bria/index.types.d.ts

This adds:
- a `PayoutCancelled` event type to the expected event types Bria produces
- an interim `payoutCancelled` handler to the bria event handler

feat: add payout cancelled event handler

---

core/api/src/servers/event-handlers/bria.ts
core/api/src/services/bria/event-handler.ts
core/api/src/services/bria/index.types.d.ts
core/api/src/services/ledger/facade/onchain-send.ts
core/api/test/bats/onchain-send.bats

This is to complete the implementation to handle payouts originated from the application here.

refactor: complete PayoutCancelled handler implementation

---

flake.lock
flake.nix

_Cherry-picked from: https://github.com/systeminit/si/commit/bbd13efa2543b4219303f9252a3248ae97c817a8_
This changes pins the version of Tilt back to 0.33.5 as the 0.33.6-built version emits the following error:
```
Error: running in prod mode, but JS/CSS files are not available
```
Once NixOS/nixpkgs#260712 merges then we should be able to drop the version pin.
References: tilt-dev/tilt#6214
References: NixOS/nixpkgs#260411

chore: pin to Tilt 0.33.5 until upstream Nix pkg is fixed

---

ci/apps/pipeline.yml
flake.nix

This adds a package to `nix.flake` that builds an image with the `nativeBuildInputs` as the environment.
Build with:
```bash
$ nix build .#dockerImage
```
Load with:
```bash
$ docker load < result
```
Run with:
```bash
$ docker run -it galoy-dev-env:latest
```
---
From running `$ nix flake show`:
```bash
git+file:///home/arvinda/Developer/Projects/GaloyMoney/galoy?ref=refs%2fheads%2fdocker-nix-image&rev=9808c4b59205a08786dba2fe44c9daf42ff2ee41
├───devShells
│   ├───aarch64-darwin
│   │   └───default: development environment 'nix-shell'
│   ├───aarch64-linux
│   │   └───default: development environment 'nix-shell'
│   ├───x86_64-darwin
│   │   └───default: development environment 'nix-shell'
│   └───x86_64-linux
│       └───default: development environment 'nix-shell'
├───formatter
│ …
```

build: add dockerImage dev env package to nix flake

---

flake.nix

This is to solve the issue where the `PATH` variable doesn't get properly set if entering the container through any pathway other than the default entrypoint.
Below is context added from our diagnosis process that lead us to decide to switch to `dockerTools.buildImage`.
**For image build with `dockerTools.buildNixShellImage`**
`docker run -it <image-name>` gets a shell with:
```bash
echo $SHELL
>  /nix/store/yi5aswh4a0mb82kbi0afr26j5ilsghjl-bash-interactive-5.2-p15/bin/bash
echo $PATH
>  /nix/store/yi5aswh4a0mb82kbi0afr26j5ilsghjl-bash-interactive-5.2-p15/bin:/nix/store/7snc8ip3rgjsfwrpjg42ynmh630vzx88-buildDerivation/bin:/nix/store/vc6d64vv2fbqbjl55ilq7q3a0cmpmxpz-envsubst-1.4.2/bin:/nix/store/qs5b5msb3jj13140k7ffqx39bphanghg-nodejs-20.8.0/bin:/nix/store/m94slj1lw64fn0frsr8y65nx5kc7ygha-t …
```

build: switch nix docker image to 'buildImage'

---

flake.nix

Ubuntu brings bash in at `/usr/bin/bash` but our script shebangs set the expectation for it to be at `/bin/bash`. This adds bash to `/bin` in a way that's independent of any base images we use.

fix: add bash to /bin/bash in image

---

.github/workflows/integration-test.yml

The new integration action still comes in at an average of 12 mins.

ci: reset integration action timeout to 15 mins

---

core/api/src/migrations/20231030191242-fix-earn-typo.ts

- db migration fixing typo "moneySocialAggrement" that was fixed in the domain in pr #3306

fix: typo in earn persistence

---

core/api/src/config/index.ts
core/api/src/servers/trigger.ts

there were [multiple cases](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/6PPbsaCmy2Y) not fixed manually (probably fixed by the new deployments). This PR adds a watcher to trigger that runs handleHeldInvoices (same used in cron) every 5 mins.
Please keep in mind that this will not fix edge case mentioned in the meeting so we still need to create/update the alert.
fyi: I tested the alternatives but were slower because they validated against lnds and not db like with this solution

fix(core): add watcher for pending held invoices

---

core/api/src/servers/trigger.ts

the watcher is adding [more traces](https://ui.honeycomb.io/teams/galoy/usage) than expected (above daily threshold), this will reduce this consumption and lnd grpc api usage

perf(core): run watchHeldInvoices only if held invoices count gt 0

---

core/api/dev/apollo-federation/supergraph.graphql
core/api/src/app/accounts/get-pending-onchain-transactions-for-account.ts
core/api/src/app/accounts/index.ts
core/api/src/app/wallets/get-pending-onchain-transactions-for-wallets.ts
core/api/src/app/wallets/get-pending-transactions-by-addresses.ts
core/api/src/app/wallets/index.ts
core/api/src/graphql/admin/schema.graphql
core/api/src/graphql/public/schema.graphql
core/api/src/graphql/public/types/abstract/account.ts
core/api/src/graphql/public/types/object/business-account.ts
core/api/src/graphql/public/types/object/consumer-account.ts
core/api/src/graphql/shared/types/abstract/wallet.ts
core/api/src/graphql/shared/types/object/btc-wallet.ts
core/api/src/graphql/shared/types/object/usd-wallet.ts
core/api/test/bats/gql/pending-transactions-by-address.gql
core/api/test/bats/gql/pending-transactions.gql
core/api/test/bats/onchain-receive.bats
dev/config/apollo-federation/supergraph.graphql

- add pendingTransactions to Account and Wallet GQL objects
- add pendingTransactionsByAddress to Wallet objects

feat: add pending tx queries

---

dev/BUCK
dev/tilt.bzl

This would fix the issue where someone would have to be at the top-level dir for `//dev:up` and `//dev:down` to work

refactor: change tilt buck target to be runnable from any dir

---

core/api/dev/apollo-federation/supergraph.graphql
core/api/src/graphql/admin/schema.graphql
core/api/src/graphql/public/schema.graphql
core/api/src/graphql/shared/types/abstract/invoice.ts
core/api/src/graphql/shared/types/object/ln-invoice.ts
core/api/src/graphql/shared/types/object/ln-noamount-invoice.ts
core/api/src/services/mongoose/wallet-invoices.ts
dev/config/apollo-federation/supergraph.graphql

- filter out legacy invoices during pagination that dont contain paymentRequests
- add createdAt field to gql invoice interface

fix: filter invoices without paymentRequest

---

core/api/Makefile

current cmd is not working because pnpm does not return same exit codes as yarn
FYI: needs to be rebased once the critical issue is fixed

fix: audit command

---

core/api/src/domain/accounts/limits-volume.ts
core/api/src/services/ledger/facade/volume.ts
core/api/test/helpers/ledger.ts
core/api/test/integration/services/ledger-facade.spec.ts

This fixes an issue that was discovered where a user tried to send $700 twice (and got routing errors) and then on the third attempt was hit was a `WithdrawalLimitExceeded` error since the previous 2 failed attempts were wrongly accounted for when calculating volumes.
_See pattern in [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/FjAzT7CJvnt)_

fix(api): withdrawal volumes handling for failed payments

---

core/api/src/servers/graphql-main-server.ts
core/api/src/servers/middlewares/session.ts

Avoid 500 errors for [CouldNotFindAccountFromKratosIdError](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/6XnXpZ12jLz/trace/f9RTg5P266F?fields[]=s_name&fields[]=s_serviceName&span=1aeaee98a7b2420b)

fix(core): avoid unknown exceptions in setGqlContext

---

core/api/src/servers/graphql-admin-server.ts
core/api/src/servers/graphql-main-server.ts
core/api/src/services/ledger/books.ts

this is making the app works with bun (altough it seems bun 1.0.13 is still not fully compatible with our stack)

chore: split export type

---

core/api/BUCK
core/api/Makefile
core/api/package.json
toolchains/workspace-pnpm/macros.bzl

This change would mean that to watch-compile we would now do:
```bash
$ buck2 run //core/api:watch-compile
```
cc @nicolasburtey @dolcalmi

refactor(core): move 'watch:compile' from make to buck

---

core/api/src/domain/wallet-invoices/index.types.d.ts
core/api/src/domain/wallet-invoices/wallet-invoice-builder.ts
core/api/src/services/mongoose/schema.types.d.ts
core/api/src/services/mongoose/wallet-invoices.ts
core/api/test/integration/app/wallets/send-lightning.spec.ts
core/api/test/integration/app/wallets/update-pending-invoices.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-checker.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-status-checker.spec.ts

- make processingCompleted a non-optional field in the db schema
- follow up to pr #3557 and pr #3576

chore: make processingCompleted non-optional

---

dev/Tiltfile

With auto_init, all other resources are brought up in addition to the targeted tests. With 'enabled_resources' only the tests and their dependency resources are brought up.
This is required to run the 'core' test suite for example, since that suite finishes long before the rest of server resources come up.
This will for example significantly reduce the time for the new `integration-tests` pipeline step from #3612 to execute in CI.

refactor: target tests more specifically in Tiltfile

---

core/api/src/domain/accounts/limits-volume.ts
core/api/test/unit/domain/accounts/limits-volume.spec.ts

This is to handle the edge-cases where WalletVolume calculated exceeds the limit amount (conversion inconsistencies for e.g.), which leads to negative values for `volumeRemaining`.
The volumes here are used in 2 places:
- limit checks (e.g. [here](https://github.com/GaloyMoney/galoy/blob/b695d2fb460757bd6e12e0a4026139aaa8263c8b/core/api/src/app/accounts/account-limit.ts#L55))
- remaining limits query (e.g. [here](https://github.com/GaloyMoney/galoy/blob/b695d2fb460757bd6e12e0a4026139aaa8263c8b/core/api/src/graphql/public/types/object/one-day-account-limit.ts#L51))
In the first case negative values don't matter when comparing against amount-to-be-sent, but in the 2nd case where the value is returned from a query to the client, seeing negative "volume remaining" amounts can be confusing.

chore(core): enforce non-negative 'volumeRemaining'

---

core/api/dev/apollo-federation/supergraph.graphql
core/api/src/app/payments/index.types.d.ts
core/api/src/app/payments/send-intraledger.ts
core/api/src/app/payments/send-lightning.ts
core/api/src/app/payments/send-on-chain.ts
core/api/src/app/wallets/index.types.d.ts
core/api/src/graphql/public/root/mutation/intraledger-payment-send.ts
core/api/src/graphql/public/root/mutation/intraledger-usd-payment-send.ts
core/api/src/graphql/public/root/mutation/ln-invoice-payment-send.ts
core/api/src/graphql/public/root/mutation/ln-noamount-invoice-payment-send.ts
core/api/src/graphql/public/root/mutation/ln-noamount-usd-invoice-payment-send.ts
core/api/src/graphql/public/root/mutation/onchain-payment-send-all.ts
core/api/src/graphql/public/root/mutation/onchain-payment-send.ts
core/api/src/graphql/public/root/mutation/onchain-usd-payment-send-as-sats.ts
core/api/src/graphql/public/root/mutation/onchain-usd-payment-send.ts
core/api/src/graphql/public/root/subscription/my-updates.ts
core/api/src/graphql/public/schema.graphql
core/api/src/graphql/public/types/payload/payment-send.ts
core/api/src/services/notifications/index.ts
core/api/src/services/notifications/index.types.d.ts
core/api/test/integration/app/wallets/send-intraledger.spec.ts
core/api/test/integration/app/wallets/send-lightning.spec.ts
core/api/test/integration/app/wallets/send-onchain.spec.ts
core/api/test/legacy-integration/02-user-wallet/02-tx-display.spec.ts
core/api/test/legacy-integration/app/cron/delete-payments.spec.ts
dev/config/apollo-federation/supergraph.graphql

- Add transaction to send mutations
- Add transaction to my updates
- Fix callbacks for ln/onchain settle intraledger

feat(core): add transaction to send mutations and myupdates

---

core/api/src/app/payments/update-pending-payments.ts

fix a bug with notifications for pending payments with known fee (i.e with probe)
basically this line `if (pendingPayment.feeKnownInAdvance) return true` was causing an early return so the users did not receive notifications when a pending payment is confirmed

fix: pending payments notifications

---

core/api/src/app/admin/backup.ts

We need to provide a checksum to upload to buckets with object lock enabled, otherwise the upload fails with:
```
InvalidRequest: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters
```

fix: s3 backup

---

bats/core/api/onchain-send.bats

This fixes an issue in bats tests that was exposed by an upstream change to bria in [`v0.1.77`](https://github.com/GaloyMoney/bria/releases/tag/0.1.77).
_Build that broke: [235](https://ci.galoy.io/teams/dev/pipelines/galoy-legacy-core/jobs/bats-tests/builds/235)_

test(core): correct external address to random regtest one

---

core/api/src/graphql/shared/types/abstract/settlement-via.ts

We are seeing lots of errors because we are hitting bria for every unchain transaction - but we should only hit it when its outgoing.

chore(core): only check batch inclusion when sending

---

bats/gql/transactions.gql
core/api/dev/apollo-federation/supergraph.graphql
core/api/src/graphql/public/root/query/account-default-wallet.ts
core/api/src/graphql/public/schema.graphql
core/api/src/graphql/public/types/abstract/account.ts
core/api/src/graphql/public/types/object/business-account.ts
core/api/src/graphql/public/types/object/consumer-account.ts
core/api/src/graphql/public/types/object/public-wallet.ts
core/api/test/bats/gql/account-default-wallet.gql
core/api/test/bats/gql/invoices.gql
core/api/test/bats/gql/transactions.gql
dev/config/apollo-federation/supergraph.graphql

This is to support being able to get details like an account's default wallet's currency without having to do multiple round trips

feat: add default wallet field

---

core/api/src/app/lightning/delete-ln-payments.ts
core/api/src/domain/errors.ts
core/api/src/services/mongoose/ln-payments.ts

Fix [critical alert](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/bKoLF7MvsCp) for old txs in getPaymentRequestByTransactionId

fix(core): remove critical level from CouldNotFindLnPaymentFromHashError

---

.gitignore

This should fix the failing proto syncing pipelines that were trying to upload the pnpm store dir in the bot branch put step.

chore: add pnpm store to gitignore

---

ci/apps/tasks/open-charts-pr.sh
ci/tasks/open-charts-pr.sh

This modifies the script to only create a branch on old_ref if it doesn't already exist.
It also allows empty commits in case of no src diffs, which makes it straightforward to generate diffs in deployments without having to check if that commit has a diff branch or not.

ci: fix diff branch creation logic

---

bats/core/api/onchain-send.bats
bats/helpers/trigger.bash

This adds some checks and optimizations to handle getting to a `payout_id` value more efficiently. 
If the `exteral payout` test continues to be flaky, we may need to explore lengthening the time to get to a `payout_committed` event after payout is submitted.

test(core): optimize payout_id checks in bats

---

core/api/src/domain/phone-provider/errors.ts
core/api/src/graphql/error-map.ts
core/api/src/services/twilio-service.ts

Improves visibility for [this trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/goLn2oFXeQi/trace/y31jmYHA5af?fields[]=s_name&fields[]=s_serviceName&source=query&span=cee07c2f2f2b5477)

fix: check if 'lineTypeIntelligence' property exists

---

core/api/src/app/lightning/delete-ln-payments.ts
core/api/src/domain/bitcoin/lightning/index.types.d.ts
core/api/src/services/lnd/index.ts

we have 3 cases: failures (related to empty htlcs lnd issue),  manual rebalances,  internal rebalance (cron).
This PR fix internal/manual rebalances alerts

fix(core): CouldNotFindLnPaymentFromHashError alert

---

core/api/src/services/kratos/totp.ts

Refactor to apply error pattern matching to `kratosInitiateTotp` method for these [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/6BGS3pjVeoG/trace?source=query&span=79a275403c7fb696&trace_id=14ebf970fd15578f).

chore(core): genericise kratos errors

---

apps/dashboard/app/url.ts
apps/dashboard/components/heading.tsx
apps/dashboard/components/side-bar/index.tsx
apps/dashboard/components/side-bar/navigation-links.tsx

feat(dasboard): batch payments alpha tag

---

core/api/src/domain/bitcoin/lightning/errors.ts
core/api/src/graphql/error-map.ts
core/api/src/services/lnd/errors.ts
core/api/src/services/lnd/index.ts

This is to address the `feature pair exists` error in these [traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/pNzvTkHgFbk).
_Initial attempt at addressing this in closed #3834_

chore(core): add 'feature pair exists' error to lnd handling

---

core/api/src/app/accounts/active-accounts.ts
core/api/src/domain/ledger/activity-checker.ts
core/api/src/domain/ledger/index.types.d.ts
core/api/src/services/ledger/facade/volume.ts
core/api/test/integration/services/ledger-facade.spec.ts
core/api/test/unit/domain/ledger/activity-checker.spec.ts

_Merge after #3846_
This is to codify the application of `incoming` and `outgoing` volumes directly  in the respective volume method

refactor(core): add new 'absoluteAllTxBaseVolumeAmountSince' method

---

toolchains/workspace-pnpm/run_in_dir.py

This fixes being able to handle an env that has multiline variables like `buildPhase` like this:
```env
AR_FOR_BUILD=ar
LND2_PUBKEY=039341ef13e776dc1611502cf510110d9ac5cdc252141f5997adcfd72cef34c3a7
buildPhase={ echo "------------------------------------------------------------";
echo " WARNING: the existence of this path is not guaranteed.";
echo " It is an internal implementation detail for pkgs.mkShell.";
echo "------------------------------------------------------------";
echo;
export;
} >> "$out"
REDIS_PASSWORD=
PRICE_PORT=50051
REDIS_0_PORT=6379
```

build: allow run script to handle multiline env variables

---

toolchains/workspace-pnpm/build_next_build.py
toolchains/workspace-pnpm/macros.bzl

This will allow for things like
```py
next_build(
name = "build",
srcs = [":src"],
build_env = {
"NEXT_PUBLIC_CORE_GQL_URL": "http://localhost:4455/graphql",
}
)
```

build: add 'env' variables handling to next_build rule

---

core/api/src/domain/accounts/limits-checker.ts

We have `txVolume` attributes to give us details about volumes fetched but we can't easily tell the usd value of the amount being checked against volumes for limits. This helps with that.

chore(core): add txLimit span attributes

---

core/api/src/migrations/20240201124500-location-migration-2.ts

now that main migration has been rolled out, we can remove the left over data in accounts.
note: the reason I'm running 2 migrations instead of 1 is to avoid potential api disruption. Maybe that's an overkill for maps related things, but it's good practice nonetheless

chore: follow up migration for location refactoring

---

core/api/dev/apollo-federation/supergraph.graphql

Gotten from running `buck2 run //dev:update-schemas`

chore(core): update schemas

---

.github/workflows/integration-test.yml

This re-implements a mitigation for when no integration tests exist (for labels like `notifications`) that was previously attempted here (https://github.com/GaloyMoney/galoy/commit/cc4bc86f4d2201d8895b9d8049174173f4327a6b) and reverted here (https://github.com/GaloyMoney/galoy/pull/3976/commits/bfadbe841689b48dd8abee455ca78fe59cece7b3) when it caused an issue with missed uploads for failed test runs.

ci: conditionally upload tilt log from integration if exists

---

core/notifications/locales/en.yml
core/notifications/proto/notifications.proto
core/notifications/src/grpc/server/convert.rs
core/notifications/src/messages/mod.rs
core/notifications/src/notification_event.rs

feat(notifications): add new declined reasons

---

core/api/src/app/wallets/decline-single-pending-invoice.ts
core/api/src/app/wallets/index.types.d.ts
core/api/src/app/wallets/process-pending-invoice-result.ts
core/api/src/app/wallets/update-single-pending-invoice.ts

This is an in-place refactor of the "update pending invoice" related functions where a new more expressive return type is introduced but the existing functionality is kept exactly in place.
After this PR, things to do:
- revisit all return instances and adjust for correct behaviour

refactor(core): clean up pending invoice "finally" handling

---

core/notifications/src/grpc/server/convert.rs
core/notifications/src/user_notification_settings/error.rs

This PR will now correctly return the [ABORTED](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) code when the `UserNotificationSettings` entity is concurrently modified. For better identification and processing in clients. Should probably be identified and set to non-critical in core code base.

refactor(notifications): more expressive error on ConcurrentModification

---

apps/dashboard/app/batch-payments/server-actions.ts
apps/dashboard/app/batch-payments/utils.ts
apps/dashboard/components/batch-payments/index.tsx
apps/dashboard/services/graphql/queries/get-user-wallet-id.ts

+ If the amount is 0 or null, skip the transaction instead of giving an error.
+ Process records on the client side to prevent timeouts on very large files.
+ The process button will show the number of payment attempts.

feat(dashboard): batch-payment improvement

---

core/api/src/graphql/error-map.ts
core/api/src/servers/graphql-server.ts

To improve visibility in cases like with this test failure
https://github.com/GaloyMoney/galoy/actions/runs/8065227268/attempts/2
This will not stop the error, but it should show us the original error trace instead of the obfuscated `assertUnreachable` one.

fix(core): throw unknown errors without mapping at server entrypoint

---

apps/dashboard/app/api-keys/page.tsx
apps/dashboard/components/api-keys/btc-pay-tabs.tsx
apps/dashboard/components/api-keys/create.tsx

Users can choose between BTC or USD wallet for connection string.
updated to

feat(dashboard) separate connection strings for BTCPay wallet

---

bats/core/api/public.bats

The currency rates provider we are using in pipelines and staging are currently broken. This is to unblock the pipeline temporarily until price service is fixed by adding the ability to pass a config to return mocked values.

chore(test): skip failing test until price server is fixed

---

bats/admin-gql/account-update-level.gql
bats/admin-gql/account-update-status.gql
core/api/src/graphql/error-map.ts
core/api/src/services/notifications/index.ts
core/api/src/services/notifications/push-notifications.ts

This is to remove an unnecessary `language` field from the admin tests gql query that is dependent on the `notifications` pod which we currently do not wait for before starting the tests.

test(core): fix admin tests flakiness

---

core/api/src/domain/ledger/ln-payment-state.ts
core/api/src/domain/wallets/tx-history.ts
core/api/test/unit/ledger/ln-payment-state.spec.ts

Before this fix these states would appear as `success_after_retry` and `success_with_reimbursement_after_retry` for already paid txns.

fix(core): add correct states for already-paid failed txns

---

core/api/src/app/payments/send-lightning.ts
core/api/src/app/payments/update-pending-payments.ts
core/api/src/domain/ledger/ln-payment-state.ts
core/api/src/services/ledger/facade/update-state.ts

This PR abstracts and moves the follow actions into a final return for the `send-lightning` and `update-pending-payments` use-cases:
- update ln payment state
- send notification
In doing so it fixes some inconsistencies with how we were calling  `updateLnPaymentState` in both use-cases

fix(core): move pending ln-state-update to final return

---

core/api/src/services/lock/index.ts
core/api/test/integration/services/lock-service.spec.ts

Fixes skip we introduced because of changes from https://github.com/GaloyMoney/galoy/commit/09b7fecd20170c2f85787c989f8d2c99fa4fd525

test(core): unskip redis lock test

---

core/api/src/app/payments/send-lightning.ts
core/api/src/app/payments/update-pending-payments.ts
core/api/test/integration/app/wallets/update-pending-payments.spec.ts

This is to create a separate boundary for lock steps and to explicitly pass arguments across into the lock for ln payment related use-cases.
This has the added benefit of exposing meaningful tracing attributes alongside `bundle_completion_state` attribute in same span.

refactor(core): separate payments lock steps into function

---

core/notifications/migrations/20240312083208_fix_concurrent_poll.down.sql
core/notifications/migrations/20240312083208_fix_concurrent_poll.up.sql

Uses ```SELECT FOR UPDATE ``` clause to lock the rows to prevent concurrency violation while selecting the message id's.

fix(notifications): use FOR UPDATE for locking mq rows

---

toolchains/workspace-pnpm/package_prod_tsc_build_bin.py

The issue here is that on first creation `public-sdl`/`admin-sdl` detects that there was a change in `:write-sdl` and correctly executes. On subsequent builds though, the output from `:write-sdl` does not change and so `public-sdl` or `admin-sdl` does not re-execute.
This fix adds a unique uuid to the output script of `:write-sdl` to signal that it was re-executed and that there was some build change in one of its dependencies.

chore: add unique id to write-sdl bin script

---

apps/pay/app/[username]/layout.tsx
apps/pay/app/api/auth/[...nextauth]/auth.ts
apps/pay/app/api/auth/[...nextauth]/route.ts
apps/pay/app/graphql/quries/me-query.ts
apps/pay/app/layout.tsx
apps/pay/app/ssr-client.ts
apps/pay/components/apollo-wrapper.tsx
apps/pay/components/session-provider.tsx
apps/pay/components/sidebar/index.tsx
apps/pay/env.ts
apps/pay/lib/graphql/generated.ts
apps/pay/middleware.ts
apps/pay/package.json
apps/pay/public/icons/logout.svg
dev/Tiltfile
pnpm-lock.yaml

Needs changes in 
+ [x] charts 
+ [x] deployments

feat(pay): sign in with blink

---

apps/pay/components/sidebar/index.tsx

+ Without this, we are only able to sign in properly from `NEXTAUTH_URL`, other domains are not working properly.

chore(pay): using next-auth page for signin

---

apps/pay/app/api/auth/[...nextauth]/auth.ts
apps/pay/app/error/page.tsx
apps/pay/app/graphql/queries/me-query.ts
apps/pay/app/setuppwa/page.tsx
apps/pay/components/sidebar/index.tsx
apps/pay/lib/graphql/generated.ts
apps/pay/middleware.ts
apps/pay/public/icons/log-out.svg

- Added a sign-in option on the landing page; this will work as an alternative to typing the username and currency.
- Do not allow sign-in if the user does not have a username.
- If the user signs in from the sidebar and already has a username in the URL, the sign-in username will take precedence.
- Added a logout/change username button to return to the landing page:
- If not signed in, "Change Username" will be shown.
- If signed in, "Logout" will be shown.

chore(pay): changes in sign in flow

---

dev/config/price.yml
dev/docker-compose.deps.yml

Pulls in the mock functionality introduced in https://github.com/GaloyMoney/price/pull/62

ci: add mock config for realtime price server

---

core/api/package.json
core/api/src/services/notifications/convert.ts
core/api/src/services/notifications/proto/notifications.proto
core/api/src/services/notifications/proto/notifications_pb.d.ts
core/api/src/services/notifications/proto/notifications_pb.js
core/notifications/proto/notifications.proto
core/notifications/src/grpc/server/convert.rs
core/notifications/src/notification_event/price_changed.rs
core/notifications/src/primitives.rs
core/notifications/subgraph/schema.graphql
dev/config/apollo-federation/supergraph.graphql

- add setting for `Price` notifications
- requires a follow up pr after mobile wallet is deployed with "Price" notification category

feat(core): add price notification setting

---

core/api/.envrc

For running integration tests locally we currently have the option of executing:
```
buck2 test //core/api:test-integration -- --env TEST="auth-service"
```
but this takes 40s when there is no change and > 3m when there has been a change.
This is not good for a local dev workflow.
Introducing `buck2` has achieved a lot in terms of being able to reproducibly, reliably bring up the entire system in a deterministic way as well as have easy to adapt templates for creating production builds.
But for development on a single subproject going down to the native task runner (like `pnpm` or `cargo`) seems to yield better results / faster feedback. At least how we have the `buck2` tasks setup up at the moment.
Hence adding this `.envrc` allows us to run:
```
cd core/api
TEST="auth-service" pnpm run …
```

chore(core): add .envrc for local pnpm execution

---

core/api/src/app/payments/index.types.d.ts
core/api/src/app/payments/ln-send-result.ts
core/api/src/app/payments/send-intraledger.ts
core/api/src/app/payments/send-lightning.ts
core/api/src/app/payments/send-on-chain.ts

This PR adds a new result type for ln send locks and then moves notification steps out of all payment send locks .

refactor(core): move notification steps out of payment send locks

---

core/api/src/graphql/error.ts
core/api/src/graphql/public/root/mutation/user-login-upgrade.ts

Add missing `success` fields and add a new error from missing IP issue. This is response to [this trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/9iR9XDXLTzD/trace/aPjf8ZNK7AB?fields[]=s_name&fields[]=s_serviceName&source=query&span=a1949975fd0adf9d).

fix(core): add success field to 'UserLoginUpgradeMutation' error return

---

apps/consent/app/graphql/generated.ts
apps/dashboard/services/graphql/generated.ts
apps/map/services/galoy/graphql/generated.ts
apps/pay/lib/graphql/generated.ts
bats/core/api/invoices.bats
bats/core/api/ln-receive.bats
core/api/src/graphql/public/root/mutation/ln-invoice-create-on-behalf-of-recipient.ts
core/api/src/graphql/public/root/mutation/ln-invoice-create.ts
core/api/src/graphql/public/root/mutation/ln-noamount-invoice-create-on-behalf-of-recipient.ts
core/api/src/graphql/public/root/mutation/ln-noamount-invoice-create.ts
core/api/src/graphql/public/root/mutation/ln-usd-invoice-btc-denominated-create-on-behalf-of-recipient.ts
core/api/src/graphql/public/root/mutation/ln-usd-invoice-create-on-behalf-of-recipient.ts
core/api/src/graphql/public/root/mutation/ln-usd-invoice-create.ts
core/api/src/graphql/public/schema.graphql
core/api/src/services/mongoose/schema.ts
dev/config/apollo-federation/supergraph.graphql

_Merge after #4262 &  #4286_
This is to enforce uniqueness at the persistence level for `externalId` field in invoices collection. This also then adds the param to invoice creation mutations to allow setting this variable by api users.
Before this change, the external id would only be set internally as its default value which is the unique payment hash for each invoice.
**This PR should be rolled out only after the #4286 migration**

feat(core): enforce uniqueness and add tx external id param

---

README.md

Added test account credentials in README for ease in login in dev mode.

docs: add test account credentials to README

---

core/notifications/src/app/mod.rs
core/notifications/src/email_executor/mod.rs
core/notifications/src/job/mod.rs
core/notifications/src/notification_event/circle_grew.rs
core/notifications/src/notification_event/circle_threshold_reached.rs
core/notifications/src/notification_event/identity_verification_approved.rs
core/notifications/src/notification_event/identity_verification_declined.rs
core/notifications/src/notification_event/identity_verification_review_started.rs
core/notifications/src/notification_event/link_email_reminder.rs
core/notifications/src/notification_event/marketing_notification_triggered.rs
core/notifications/src/notification_event/mod.rs
core/notifications/src/notification_event/price_changed.rs
core/notifications/src/notification_event/transaction_occurred.rs

- Make push optional for notifications

chore(notifications): make push msg optional

---

apps/dashboard/app/callback/page.tsx
apps/dashboard/components/callback/callback-input.tsx
apps/dashboard/services/graphql/generated.ts
apps/dashboard/services/graphql/queries/me-data.ts

+ Fixed : https://github.com/GaloyMoney/galoy/issues/4326

feat(dashboard): adding button for callbackPortalUrl

---

core/api/src/domain/accounts/index.ts
core/api/src/domain/merchants/index.ts
core/api/src/domain/shared/index.ts
core/api/src/domain/shared/index.types.d.ts
core/api/src/domain/shared/validation.ts
core/api/src/domain/users/index.ts
core/api/src/domain/wallets/validation.ts
core/api/src/servers/middlewares/idempotency.ts
core/api/src/services/kratos/index.ts
core/api/src/services/mongoose/schema.ts
core/api/src/services/mongoose/schema.types.d.ts
core/api/src/services/mongoose/wallet-invoices.ts

This is the 1st of 3 PRs to add `accountId` to wallet invoices and setting up a unique index on `(accountId, externalId)`:
- add accountId field for new invoices (this PR)
- migrate accountId in existing invoices
- make `accountId` required field in schema and add `externalId` index

refactor(core): add accountId field to WalletInvoice

---

core/api/src/services/ledger/schema.ts

[Admin balance queries](https://github.com/GaloyMoney/galoy/blob/main/core/api/src/services/ledger/admin-legacy.ts#L20 ) are not working properly after indexes update. This update includes specific index to support `currency` and `_id` when balance snapshot is used

fix(core): medici balance performance

---

apps/consent/cypress.config.ts
dev/Tiltfile

Reverting changes from https://github.com/GaloyMoney/galoy/pull/4346/files
This client is used to test consent standalone.

fix(consent): adding hydra test client

---

core/api/src/app/users/get-user-language.ts
core/api/src/config/index.ts
core/api/src/domain/users/index.ts
core/api/src/services/notifications/grpc-client.ts
core/api/src/services/notifications/index.ts

- use empty language when notifictions service returns an error
- add timeout to notification settings grpc call

chore(core): fallback for language query

---

core/notifications/src/job/mod.rs

Setting initial retry to 10s for all jobs to avoid duplicate job executions.

chore(notifications): always set initial_retry_delay to 10s

---

apps/dashboard/app/api-keys/page.tsx
apps/dashboard/app/api-keys/server-actions.ts
apps/dashboard/app/api/auth/[...nextauth]/route.ts
apps/dashboard/app/batch-payments/get-user-details-action.ts
apps/dashboard/app/batch-payments/server-actions.ts
apps/dashboard/app/callback/page.tsx
apps/dashboard/app/callback/server-actions.ts
apps/dashboard/app/security/2fa/server-actions.ts
apps/dashboard/app/security/email/server-actions.ts
apps/dashboard/app/security/email/verify/page.tsx
apps/dashboard/app/transactions/page.tsx
apps/dashboard/services/graphql/index.ts
apps/dashboard/services/graphql/mutations/api-keys.ts
apps/dashboard/services/graphql/mutations/callback-mutation.ts
apps/dashboard/services/graphql/mutations/email.ts
apps/dashboard/services/graphql/mutations/intra-ledger-payment-send/btc.ts
apps/dashboard/services/graphql/mutations/intra-ledger-payment-send/usd.ts
apps/dashboard/services/graphql/mutations/totp.ts
apps/dashboard/services/graphql/queries/api-keys.ts
apps/dashboard/services/graphql/queries/callback-query.ts
apps/dashboard/services/graphql/queries/get-transactions.ts
apps/dashboard/services/graphql/queries/get-user-wallet-id.ts
apps/dashboard/services/graphql/queries/me-data.ts
apps/dashboard/services/graphql/queries/realtime-price.ts

Before, we were passing the client from the core API (Blink API) function invocation to the Apollo client instance. Now, we are using `getServerSession` to directly get the token when calling the Apollo client instance.

refactor(dashboard): moving token to apollo client

---

bats/core/notifications/notifications.bats
core/notifications/notifications.yml
core/notifications/src/notification_event/transaction_occurred.rs
dev/config/notifications/notifications.yml

This PR disables transaction_occurred to be added to notification history. It also refactors notifications e2e test to use marketing notification to send notifications to users.

chore(notifications): do not persist txn notification to history

---

ci/apps/app-template.lib.yml
ci/core/template.lib.yml

Reverting back to the old builder while we figure out how to reduce kaniko build times.

revert: "ci: use kaniko builder"

---

core/api/src/domain/ledger/ln-payment-state.ts
core/api/test/unit/ledger/ln-payment-state.spec.ts

This can happen for example when geyser creates an invoice in our system and forwards to it via their own node when their lightning address is paid.

fix(core): handle external routed self payments bundle

---

bats/core/api/invoices.bats
core/api/src/domain/shared/index.types.d.ts
core/api/src/domain/wallet-invoices/index.types.d.ts
core/api/src/services/mongoose/schema.ts
core/api/test/helpers/wallet-invoices.ts
core/api/test/integration/app/transactions/get-invoice-preimage-by-hash.spec.ts
core/api/test/integration/app/wallets/update-pending-invoices.spec.ts
core/api/test/integration/services/wallet-invoices-repository.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-checker.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-status-checker.spec.ts

This is the 3rd PR of 3 (#4345) to enforce invoices externalId uniqueness at the account level

chore(core): add (externalId, accountId) invoices index

---

apps/consent/package.json
pnpm-lock.yaml

Reverting the Next.js version bump in this PR: https://github.com/GaloyMoney/blink/pull/4448, 
as it breaks the tests in consent.

chore(consent): change next.js version

---

apps/voucher/components/create/confirm-modal/confirm-modal.module.css
apps/voucher/components/create/confirm-modal/index.tsx

chore(voucher): updated confirm voucher modal

---

apps/voucher/app/create/client-side-page.tsx
apps/voucher/graphql/resolvers/mutation/create-withdraw-link.ts
apps/voucher/lib/amount-calculator.ts
apps/voucher/services/db/index.ts

Previously, we handled the sales amount like this:
Sales amount = $1.05 (paid to escrow).
Voucher created for $1.04 (platform fee = 1%).
However, when using a BTC wallet to pay for the voucher, the sales amount is converted to satoshis and paid to escrow. This can lead to discrepancies (due to conversion from cents to sats). For example, we might end up paying $1.04 instead of $1.05, resulting in no platform fee being collected.
To improve accuracy, we now use the settlement amount (the actual amount paid to escrow) as the base and deduct the platform fees from that to create the voucher.
For example, if the amount paid to escrow is $1.04, we will deduct the fees from this amount and create a voucher for $1.03.

chore(voucher): use settlement amount to get voucher price

---

core/api/src/domain/bitcoin/lightning/errors.ts
core/api/src/graphql/error-map.ts
core/api/src/services/lnd/errors.ts
core/api/src/services/lnd/index.ts

Fix UnknownLightningServiceError https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/5Ta428iNk6H?hideCompare

fix(core): add lnd FeeInsufficient error validation

---

core/api/src/domain/support/errors.ts
core/api/src/services/twilio-service.ts

Someone would need to spend time iterating on the integration to resolve all the potential errors that may be returned by OpanAI api. in the meantime, no need to raise a critical alert every time the API return an error; at worst the bot may not return an answer.

chore: demoting chatGPT error to non critical

---

bats/core/api/onchain-receive.bats

fix `# bats warning: Executed 134 instead of expected 135 tests` in e2e tests (users and wallets are created/funded in setup_file)

fix: remove unnecessary users/wallets creation/funding

---

core/api/src/app/authentication/login.ts
core/api/src/app/authentication/logout.ts
core/api/src/app/errors.ts
core/api/src/domain/kratos/errors.ts
core/api/src/domain/kratos/index.ts
core/api/src/domain/kratos/index.types.d.ts
core/api/src/graphql/error-map.ts
core/api/src/services/kratos/auth-email-no-password.ts
core/api/src/services/kratos/auth-phone-no-password.ts
core/api/src/services/kratos/auth-username-password-deviceid.ts
core/api/src/services/kratos/cron.ts
core/api/src/services/kratos/errors.ts
core/api/src/services/kratos/identity.ts
core/api/src/services/kratos/index.ts
core/api/src/services/kratos/index.types.d.ts
core/api/src/services/kratos/private.ts
core/api/src/services/kratos/tests-but-not-prod.ts
core/api/src/services/kratos/totp.ts
core/api/test/integration/services/auth-service.spec.ts

Fix unhandled errors  alerts in kratos service (initiateTotpRegistration) https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/h3e6HJTCSWC?hideCompare

refactor(core): kratos error handling

---

core/api/src/app/authentication/totp.ts

Fix https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/C1KR8g2dQJQ?hideCompare
- if kratosInitiateTotp fail user should not be logged out
- avoid race condition when session is logged out before being able to initiate totp registration

fix(core): avoid logout before initiate totp

---

core/api/src/services/mongoose/accounts.ts
core/api/src/services/mongoose/schema.ts

Avg duration is more than 1 second https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/71kKbg8xRg6?hideCompare
- Add to username index only records with a valid value
- Remove regex query (improves performance)
- Force the use of username index (I tested it directly and for some reason is not using the index without the hint)

perf(core): update username index

---

core/api/src/app/lightning/get-held-invoices.ts
core/api/src/app/wallets/add-invoice-for-wallet.ts
core/api/src/domain/bitcoin/lightning/index.ts
core/api/src/domain/bitcoin/lightning/invoice-expiration.ts
core/api/src/domain/primitives/index.ts
core/api/src/servers/trigger.ts
core/api/test/integration/app/wallets/update-pending-invoices.spec.ts
core/api/test/unit/domain/bitcoin/lightning/invoice-expiration.spec.ts
core/api/test/unit/domain/wallet-invoices/wallet-invoice-checker.spec.ts

Set default BTC invoice expiration to 1 hour. this will help to improve main lnd/trigger performance

chore(core): update default expiration for BTC invoices

---

core/api/src/services/ledger/paginated-ledger.ts

- now it is using new index correctly but the use of skip is a bad practice specially for accounts with more than 500k transactions
- improve performance removing count query
tests that cover pagination: https://github.com/GaloyMoney/blink/blob/main/core/api/test/integration/services/ledger-service.spec.ts#L59

perf(core): improve backward pagination

---

core/api/src/domain/bitcoin/lightning/invoice-expiration.ts

Increase default timeout to avoid issues with lnp2pbot invoice expiration window https://github.com/lnp2pBot/bot/blob/main/.env-sample#L26

chore(core): update default btc invoice expiration to 2 hours

---

core/api/src/domain/users/index.ts

Fix https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/C15uWKBN8Gk?hideCompare
I could not find any update in firebase documentation but we can use this info as base:
iOS (APNS): 64 characters
Android: 140-200 characters (variable length)
Firebase: 142  according to error message

fix(core): update notifications device token validation length

---

core/api/src/debug/settle-pending-onchain-payments.ts
core/api/src/domain/bitcoin/onchain/index.types.d.ts
core/api/src/domain/ledger/index.types.d.ts
core/api/src/services/bria/grpc-client.ts
core/api/src/services/bria/index.ts
core/api/src/services/ledger/index.ts
typos.toml

- this script does not update bank owner earnings according to proportional fee (like with the event)
- the use of `Wallets.settlePayout` will send a notification + callbacks

chore: add settle pending onchain payments script

---

core/api/src/domain/bitcoin/index.ts
core/api/src/domain/payments/ln-fees.ts
core/api/test/integration/services/lnd-service.spec.ts
core/api/test/unit/domain/payments/ln-fees.spec.ts

Fix https://github.com/GaloyMoney/blink-mobile/issues/3353

fix(core): allow micro payments

---

core/api/src/graphql/error.ts
prelude/decls/erlang_rules.bzl
prelude/java/java_library.bzl
prelude/kotlin/kotlin_library.bzl

chore: fix some comments

---

core/api-keys/src/identity/mod.rs

Fix performance issue authenticating expired keys https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/xPmzcadaYSV?hideCompare=
search by encrypted_key is not necessary because active keys are already populated

perf(api-keys): avoid db scan in find_subject_by_key

---

apps/pay/app/lnurlp/[username]/route.ts

it is not implemented in the callback and adding to the memo will modify description hash. Implement this would require additional metadata to be added to a payment

fix(pay): disable comment in lnurl pay

---

apps/pay/app/api/lnurl-proxy/route.ts
apps/pay/components/parse-pos-payment/nfc.tsx

The Blink POS system experiences CORS errors when trying to use BTCPayServer-issued bolt cards. This happens because the system attempts to make direct browser-to-LNURL-server requests, which fail due to CORS restrictions.
Other POS systems (LNbits TPOS, BTCPay) don't have this issue because they handle LNURL requests server-side.
Implemented a server-side proxy approach to avoid CORS restrictions:
1. Created a server-side proxy endpoint for LNURL requests
2. Modified the NFC component to send requests through the proxy instead of directly using js-lnurl
3. Fixed a typo in the UI ("Bold card" → "Bolt card")
- When a bolt card is tapped, the NFC component sends both the LNURL and payment request to our server-side proxy
- The proxy handles all communication with the LNURL server, avoiding …

fix(pay): make server side LNURL request to avoid CORS issue
