GaloyMoney/blink

INSTALLATION.md
added link for minikube tutorial as well
I also used `nvm` to manage `node`, should that be added as well?
=> Added caveat when running locally on mac, link

default.yaml, src/rateLimit.ts, src/text.ts
this is a first step. need to do a fibonacci backoff eventually
=> ip rate limiting for code request.

.envrc, .github/workflows/integration-test.yml
Run docker-compose based integration tests as a GitHub-action for every push and PR.
=> Add github workflow to run integration test

src/__tests__/01a-price.ts, src/__tests__/03-create-channels.ts, src/lndAuth.ts, src/userWallet.ts
those warning which are showing up for every PR review should no longer be present
=> fix github warning related to typescript

src/Lightning.ts, src/lndUtils.ts
the previous comment was misleading. it was expected that there is a mismatch between lnd and mongodb for the invoice after activating the auto invoice deleting on lnd. this PR should fix the issue.
=> fix current log issue related to cancelled invoice

package.json, src/entrypoint/graphql.ts, yarn.lock
=> add helmet for increase security

package.json, yarn.lock
This should fix the helmet type problem
=> Downgrade @types/node to 14

charts/galoy/templates/deployment.yaml
@bodymindarts @krtk6160 I'll inject the secret manually. curious how to think about this in the context of an automated deployment
=> injecting apollo studio env

.envrc
fix https://github.com/GaloyMoney/galoy/issues/303
=> fix Issue #303 docker ps filter

Dockerfile-debug
Must fix Directory /app/test in the roots[0] option was not found.
I dont have access to run CircleCI so would be great if runs before merge PR
=> Fix Dockerfile-debug issue with CI

src/Lightning.ts
It seems there are different states of deletion for an invoice:
- first state is the invoice is written as "cancelled" but the reference is still present in the bbolt database.
- second state is that the invoice is being pruned and the reference is no longer present in the bbolt database.
we were currently not managing the second case correctly. this PR should fix it. I'm not sure how we can test this programmatically.
I'm not sure what make the invoice transition from 1 to 2. maybe a lnd restart with db compaction?
(is that correct @alexbosworth?)
=> del InvoiceUser entry when unable to locate the invoice

src/Lightning.ts
this is related to https://github.com/GaloyMoney/lnpage/issues/57
=> fix invoiceUser not existant issue

prettier.config.js
Something I noticed while working on mirroring the mobile repo to the backend.
=> Remove duplication

src/entrypoint/graphql.ts
Ref: https://github.com/GaloyMoney/galoy/issues/336
=> Add http server to startApolloServer. fix #336

src/phone-provider.ts, src/text.ts, test/integration/01-setup/01-funds-bitcoind-lnds.spec.ts, test/integration/01-setup/01-lightning-channels.spec.ts, test/integration/02-user-wallet/02-fees-onchain.spec.ts, test/integration/02-user-wallet/02-index.spec.ts, test/integration/02-user-wallet/02-invoice.spec.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/02-user-wallet/02-receive-rewards.spec.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts, test/mocks/phone-provider.ts
this should remove some of the log pollution when doing the tests
=> removing some warning related to twilio not having the credentials

src/OnChain.ts, src/SpecterWallet.ts, src/bitcoind.ts, src/utils.ts, test/helpers/bitcoinCore.ts, test/helpers/lightning.ts, test/integration/01-setup/01-funds-bitcoind-lnds.spec.ts, test/integration/02-user-wallet/02-fees-onchain.spec.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts, test/integration/specter-wallet.spec.ts
PR for https://github.com/GaloyMoney/galoy/issues/353.
It should be ready to get merged, but some adjustments could still be done.
=> Split default wallet

.github/workflows/unit-test.yml, package.json, test/unit/specter-wallet.spec.ts
- Mock lnds config
- Add unit test to github actions to prevent this issue in the future
- Add LogLevel in test:unit command
Ref: [Issue 387](https://github.com/GaloyMoney/galoy/issues/387)
=> Fix issue #387 - Unit tests shouldn't need environment setup

src/config.ts, src/rateLimit.ts, src/types.d.ts
This PR removes `yamlConfig` references from the `rateLimit.ts`file.
=> Refactor 'rateLimit' types/config placement

src/entrypoint/graphql-core-server.ts
Note: This is a temporary change as that's all being removed in the new admin schema
=> Fix admin-panel lookup by username problem

src/Lightning.ts, src/LightningTypes.d.ts, src/OnChain.ts, src/config.ts, src/lndAuth.ts, src/lndAuthTypes.d.ts, src/lndUtils.ts, test/helpers/lightning.ts
This PR removes `yamlConfig` references from the `Lightning.ts` and `lndUtils.ts` files.
=> Refactor 'Lightning' types/config placement

src/services/lnd/utils.ts, src/services/mongodb/index.ts, test/integration/services/lnd/utils.spec.ts
- Fix deleteExpiredInvoiceUser query but maybe will not run because `updateUsersPendingPayment` hang in cron
- Fix log security warnings
=> Fix delete expired invoices

src/core/balance-sheet.ts, src/core/ledger/query.ts
- Solves performance queries for lightning transactions (invoices and payments)
- Adds minor performance query filter for Onchain transactions
- Onchain refactor will be in its own PR
REF: https://github.com/GaloyMoney/galoy/issues/229
=> Fix cronjob - update pending lightning transactions

Makefile, src/domain/errors.ts, src/domain/invoice-expiration.ts, src/domain/invoice-expiration.types.d.ts, src/domain/lightning-service.types.d.ts, src/domain/ln-invoice.ts, src/domain/ln-invoice.types.d.ts, src/domain/primitives/btc.ts, src/domain/primitives/btc.types.d.ts, src/domain/primitives/tx_denomination_currency.types.d.ts, src/services/lnd/index.ts, test/jest-unit.config.js, test/unit/domain/invoice-expiration.spec.ts
This adds the same functionality as https://github.com/GaloyMoney/galoy/pull/426 but uses the patterns introduced in https://github.com/GaloyMoney/galoy/pull/385
=> Lightning service no result

src/core/lightning/index.ts, src/core/lightning/payment-status-checker.ts, src/domain/errors.ts, src/domain/errors.types.d.ts, src/domain/invoices.types.d.ts, src/domain/primitives/crypto.types.d.ts, src/services/mongoose/invoices.ts, test/integration/services/mongoose/invoices.spec.ts
Introduces the same functionality introduces in https://github.com/GaloyMoney/galoy/pull/429 but uses the patterns introduced in https://github.com/GaloyMoney/galoy/pull/385
=> Invoices repo no result

default.yaml, src/config/app.ts, src/core/balance-sheet.ts, src/core/ledger/transaction.ts, src/core/on-chain/index.ts, src/core/types.d.ts, src/core/utils.ts, src/servers/trigger.ts, src/services/lnd/auth.ts, src/services/lnd/utils.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/servers/trigger.spec.ts
- Change cron workers for updateOnchainReceipt from 10 to 3
- Add new handler to subscribeToBlocks
- Fix query issues in onchainTransactionEventHandler
=> Process only users from block transactions

src/config/app.ts, src/core/error.ts, src/core/text.ts, src/core/types.d.ts, src/core/utils.ts, src/servers/graphql-server.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts, test/integration/servers/graphql-main-server.spec.ts
This PR refactors various IP-related configs.
_This is the last PR to round out the "inject configs" issue (#343)_
=> Refactor 'IP' types/config

default.yaml, src/config/app.ts, src/core/types.d.ts, src/servers/graphql-server.ts
We need this to `true` in staging
=> Use a configuration value to control helmet content policy

.envrc, Makefile, docker-compose.yml
- Add price server to dev environment (docker compose)
- Add trigger to Make file
- Update .envrc with price env variables
=> Add price server to docker compose

src/core/lightning/index.ts, src/core/lightning/wallet.ts, src/core/on-chain/index.ts, src/core/types.d.ts, src/core/user-wallet.ts, src/core/user-wallet.types.d.ts, src/services/mongoose/schema.types.d.ts
_Moved from #424_
Small PR to clean up the constructor args in the following classes:
- `UserWallet`
- `LightningMixin`
- `OnChainMixin`
- `LightningUserWallet`
=> Refactor 'UserWallet' class/subclass constructor args typing

src/servers/graphql-server.ts
This reverts commit 25142b106f27352995275f7039aafd3f84f1b033.
=> Revert "Put body logging into `req` structure"

charts/ingress-nginx-values.yaml
for debug reasons I have added the headers and request to the nginx log but this is no longer needed
=> more log cleanup

package.json, src/services/lnd/auth.ts, src/services/lnd/health.ts, src/services/lnd/unauth.ts, test/integration/services/ledger/transaction.spec.ts, test/integration/services/lnd/health.spec.ts
Upgrade lightning package to 0.13.1 and update health checks to use getWalletStatus instead of getWalletInfo.
NOTE:  dev/lnd/lnd.conf required changes to get this branch to compile.
=> Feature upgrade lnd to 0.13.1

src/services/lnd/health.ts, test/integration/services/lnd/health.spec.ts
- before deploy please test running `make trigger` and check initialization in test env
- I added additional expects to validate the use of auth lnd in lndStatusEvent
=> Fix lndStatusEvent auth lnd issue

package.json, src/core/utils.ts, src/graphql/admin/index.ts, src/graphql/main/index.ts, src/servers/graphql-server.ts
Updated with local test values for APOLLO env vars
=> Error visibility

src/graphql/main/mutations.ts, src/graphql/main/schema.graphql, src/graphql/root/mutation/user-quiz-questions-update-completed.ts, src/graphql/types/payload/user-quiz-questions-update-completed.ts, src/servers/graphql-main-server.ts
=> Implement the userQuizQuestionsUpdateCompleted mutation

src/core/lightning/index.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/services/lnd/index.ts, src/services/lnd/utils.ts
Add two new needed lightning service methods to codebase:
- `isLocal`
- `deleteUnpaidInvoice`
=> Add `isLocal` & `delete..` lightning service methods

src/app/wallets/get-transactions-for-wallet.ts, src/domain/ledger/index.ts, src/domain/ledger/index.types.d.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/services/ledger/index.ts, test/unit/domain/wallets/tx-history.spec.ts
Prerequisite for `Add admin support queries` PR
=> Add walletId to LedgerTransaction and WalletTransaction types

README.md
=> Whitespace temp

README.md
=> Revert "Whitespace temp"

src/core/on-chain/index.ts, src/domain/ledger/index.ts, src/domain/ledger/index.types.d.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/graphql/admin/schema.graphql, src/graphql/main/schema.graphql, src/graphql/types/object/onchain-transaction.ts, src/servers/graphql-old-server.ts, src/services/ledger/index.ts, test/helpers/redis.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts, test/integration/servers/trigger.spec.ts, test/unit/domain/wallets/tx-history.spec.ts
- this PR only modify read/translation methods and tests
- this PR does not modify schema or insert/update operations
- txId refactor will be done in another PR https://github.com/GaloyMoney/galoy/pull/657
=> Refactor addresses for onchain txs

src/core/user-wallet.ts, src/graphql/admin/types/object/user.ts, src/graphql/main/mutations.ts, src/graphql/main/schema.graphql, src/graphql/root/mutation/user-update-language.ts, src/graphql/root/mutation/user-update-username.ts, src/graphql/types/object/user.ts, src/graphql/types/payload/user-update-language.ts, src/graphql/types/payload/user-update-username.ts
Includes switching the updateLanguageMutation to use the new app use-case
=> Implement the updateUsername mutation

DEV.md
this follows a question we got from slack
cc @trigger67
=> improve DEV.md

docker-compose.yml
(last version for the v4 branch)
=> upgrade last mongodb version docker-compose

package.json, src/core/utils.ts, test/helpers/index.ts, test/helpers/price.ts, test/integration/01-setup/01-funds-bitcoind-lnds.spec.ts, test/integration/01-setup/01-lightning-channels.spec.ts, test/integration/01-setup/01-price-history.spec.ts, test/integration/02-user-wallet/02-index.spec.ts, test/integration/02-user-wallet/02-invoice.spec.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/02-user-wallet/02-receive-rewards.spec.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts, test/integration/02-user-wallet/02-tx-onchain-fees.spec.ts, test/integration/notifications/notification.spec.ts, test/integration/servers/graphql-main-server/auth-requests.spec.ts, test/integration/servers/graphql-main-server/no-auth-requests.spec.ts, test/integration/servers/graphql-old-server.spec.ts, test/integration/servers/trigger.spec.ts, test/integration/services/ledger/transaction.spec.ts, test/integration/services/mongoose/schema.spec.ts, test/integration/services/mongoose/wallet-invoices.spec.ts, test/unit/services/lnd/onchain-service.spec.ts, yarn.lock
- Remove price mock
- Fix tests open handles (writeSDLFile and httpServers)
- Add price history (1 year)
This is the 2nd split of Price refactor https://github.com/GaloyMoney/galoy/pull/662
=> Remove price mock + Price history setup

DEV.md, default.yaml
so there is no need for dirty state on dev. this is override in prod with helm.
=> better default (IMO)

package.json, src/graphql/admin/schema.graphql, src/graphql/main/schema.graphql, src/graphql/types/abstract/transaction.ts, src/graphql/types/object/globals.ts, src/graphql/types/object/intraledger-transaction.ts, src/graphql/types/object/user.ts, src/graphql/types/object/wallet-contact.ts, src/graphql/types/scalar/safe-int.ts
Myself and @nicolasburtey added some docs for the graphql.  A long way to go but it's a start.  There are some questions we had while writing the docs which I have marked with `TODO`.
=> Added documentation

src/graphql/types/scalar/safe-int.ts
fix issue with dedent and SafeInt description
=> Fix dedent comment in SafeInt

src/app/wallets/ln-send-payment.ts, src/app/wallets/update-pending-invoices.ts, src/domain/notifications/index.types.d.ts, src/services/notifications/index.ts
Fix notification error when a ln invoice is paid via intra ledger
=> Fix ln-intraledger notification

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/index.types.d.ts, src/app/wallets/ln-send-payment.ts, src/graphql/main/schema.graphql, src/graphql/root/mutation/ln-invoice-create.ts, src/graphql/root/mutation/ln-invoice-payment-send.ts, src/graphql/root/mutation/ln-noamount-invoice-create.ts, src/graphql/root/mutation/ln-noamount-invoice-payment-send.ts, src/servers/graphql-middlewares/wallet-id.ts, test/integration/servers/graphql-main-server/auth-requests.spec.ts, test/integration/servers/graphql-main-server/queries/me.gql
Add lnInvoiceCreate, lnNoAmountInvoiceCreate, lnInvoicePaymentSend, lnNoAmountInvoicePaymentSend to wallet id middleware
=> Add lightning mutations to wallet id middleware

src/services/ledger/index.ts, test/integration/services/ledger/transaction.spec.ts
Fix issue https://github.com/GaloyMoney/galoy/issues/749
=> Fix intra ledger tx type

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/index.types.d.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/graphql/main/schema.graphql, src/graphql/root/mutation/ln-invoice-create-on-behalf-of-recipient.ts, src/graphql/types/scalar/hex32bytes.ts, src/services/lnd/index.ts
Required for lnurl-pay and lightning-address support.
=> support creating invoices on behalf of others with description_hash.

default.yaml, src/app/users/login.ts, src/app/users/request-phone-code.ts, src/config/app.ts, src/domain/primitives/index.types.d.ts, src/domain/rate-limit/index.ts, src/domain/rate-limit/index.types.d.ts, test/integration/servers/graphql-old-server.spec.ts
msBeforeNext was from yaml was not passed correctly
also improve label for default.yaml
=> fix msBeforeNext

.envrc, .github/workflows/integration-test.yml, DEV.md, Makefile, README.md, ci/image/Dockerfile, ci/tasks/test-integration.sh
Due to high demand for compatibility with docker compose v2 I think its time we upgraded our scripts.
=> chore: update all scripts for docker compose v2

src/graphql/admin/index.ts, src/graphql/admin/schema.graphql, src/graphql/main/index.ts, src/graphql/main/schema.graphql
by computing another generated file which is lexicographic based
to remove the non deterministic aspect of the .graphql file creation
still keeping the standard schema.graphql as this is the one
that make most sense for an API user
=> chore: make it easier to understand the diff of a .graphql

src/app/wallets/update-on-chain-receipt.ts, src/domain/bitcoin/onchain/index.ts, src/domain/bitcoin/onchain/index.types.d.ts, src/domain/bitcoin/onchain/tx-filter.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/services/lnd/onchain-service.ts, test/unit/domain/bitcoin/onchain/tx-filter.spec.ts, test/unit/domain/wallets/tx-history.spec.ts
rename requested here https://github.com/GaloyMoney/galoy/pull/785#discussion_r763022228
=> refactor: rename SubmittedTransaction to IncomingOnChainTransaction

src/core/utils.ts, src/graphql/error-map.ts, src/graphql/error.ts, src/services/lnd/index.ts, test/integration/servers/graphql-main-server/no-auth-requests.spec.ts, test/unit/utils.spec.ts
This PR is to:
- fix a small leak where domain errors were getting through to the app layer for unhandled errors in our error map (see **Screenshot**)
- to introduce a pattern for parsing and handling known errors from the lnd service library
---
=> Add ln service error switch

src/servers/cron.ts
Add fault tolerance to cron's tasks
- Run `TEST="01|02" make reset-integration`
- Run `. ./.envrc && yarn build && node lib/servers/cron.js | yarn pino-pretty -c -l`
=> fix: add cron tasks fault tolerance

test/jest.setup.js
Fix an issue in integration tests reported by @daviroo
=> fix: mongodb integration test sync issue

.envrc, docker-compose.yml
Update docker compose config in regards to charts update https://github.com/GaloyMoney/charts/commit/3269702267ab1592e5ddddb6003b542072a1b518
Please test locally before approve (I have only tested it on linux)
=> chore: update docker compose lnd version

src/domain/accounts/api-keys.types.d.ts, src/domain/accounts/index.types.d.ts, src/domain/bitcoin/index.types.d.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/domain/bitcoin/onchain/index.types.d.ts, src/domain/ipfetcher/index.types.d.ts, src/domain/ledger/index.types.d.ts, src/domain/lock/index.types.d.ts, src/domain/primitives/index.types.d.ts, src/domain/routes/index.types.d.ts, src/domain/twoFA/index.types.d.ts, src/domain/users/index.types.d.ts, src/domain/wallets/index.types.d.ts
more context can be read here: https://github.com/GaloyMoney/galoy/pull/851
=> chore: simplyfing brand type declaration

test/helpers/user.ts
Fixes business user creation helper to avoid local development issues
=> fix: add default coordinates to default business map users

src/app/accounts/add-earn.ts, src/domain/errors.ts, src/graphql/error-map.ts, src/graphql/error.ts
the balance calculation for the funder can take some time so not calculating it twice
=> chore: removing this extra check for funder

package.json, yarn.lock
not sure if this would improve the situation with the grpc errors `1 CANCELLED: Cancelled on client` but it's worth a try
=> chore: using last version of ln-service

.envrc, src/config/app.ts, src/services/twilio.ts
Reverts GaloyMoney/galoy#872
Required to unblock `galoy-staging-galoy` pipeline, needs secret adition and when it's complete, will recreate this.
=> Revert "chore!: modify twilio to use auth token"

.envrc, src/config/app.ts, src/services/twilio.ts
Duplicate of GaloyMoney/galoy#872 since it was reverted at GaloyMoney/galoy#876 as credentials were unavailable on Staging.
=> chore!: modify twilio to use auth token

src/servers/exporter.ts
Temporal fix testflight initialization
=> fix: disable lnd check in exporter server

src/app/users/delete-2fa.ts, src/app/users/generate-2fa.ts, src/app/users/index.ts, src/app/users/save-2fa.ts, src/core/user-wallet.ts, src/domain/twoFA/errors.ts, src/domain/twoFA/index.ts, src/domain/twoFA/index.types.d.ts, src/graphql/error-map.ts, src/graphql/root/mutation/twofa-delete.ts, src/graphql/root/mutation/twofa-generate.ts, src/graphql/root/mutation/twofa-save.ts
the tests has been updated here: https://github.com/GaloyMoney/galoy/pull/881/commits/3563fc8ab52db0df84a455a30fa7f0bd2828543e
=> chore: moving 2fa use cases to app/

src/domain/accounts/index.types.d.ts, src/graphql/admin/root/query/transaction-by-id.ts, src/services/ledger/schema.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts, test/helpers/user.ts, test/integration/02-user-wallet/02-index.spec.ts, test/integration/services/ledger/transaction.__spec__.ts
this code will be reimplemented in a subsequent PR
=> chore: remove some code related to multi currency

src/app/wallets/get-on-chain-fee.ts, src/app/wallets/pay-on-chain.ts, src/app/wallets/update-on-chain-receipt.ts, src/domain/accounts/index.types.d.ts, src/domain/wallets/index.types.d.ts, src/services/mongoose/accounts.ts, src/services/mongoose/wallets.ts, test/integration/02-user-wallet/02-tx-onchain-fees.spec.ts
this PR will make segregating `Wallet` to a new collection easier, for the multi wallet architecture.
=> chore: move fees to the account level

src/app/users/index.ts, src/app/users/index.types.d.ts, src/app/users/update-language.ts, src/core/user-wallet.ts, src/domain/errors.ts, src/domain/users/index.ts, src/graphql/error-map.ts, src/graphql/root/mutation/user-update-language.ts, src/servers/graphql-old-server.ts, test/integration/app/users/update-language.spec.ts, test/unit/domain/users/checked-to-language.spec.ts
- Move update language from core to app layer
- Add integration and unit tests
=> refactor: update language

test/integration/servers/graphql-main-server/auth-requests.spec.ts, test/integration/servers/graphql-main-server/no-auth-requests.spec.ts, test/integration/servers/graphql-main-server/queries/main.gql
Add main query test to `auth-requests` and `no-auth-requests`
=> chore: add main query test

src/app/users/login.ts, src/app/users/request-phone-code.ts, src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/create-on-chain-address.ts, src/domain/rate-limit/errors.ts, src/domain/rate-limit/index.ts, src/domain/rate-limit/index.types.d.ts, src/graphql/error-map.ts, src/services/rate-limit/index.ts, test/helpers/rate-limit.ts, test/integration/02-user-wallet/02-invoice.spec.ts, test/integration/servers/graphql-main-server/index.types.d.ts, test/integration/servers/graphql-main-server/no-auth-requests.spec.ts
- Standardise the way that we consume limiters
- Add better error reporting granularity for limiters consumed via a single config
=> refactor: create helper method for limiter functions

src/graphql/admin/schema.graphql, src/graphql/admin/types/object/lightning-invoice.ts, src/graphql/admin/types/object/lightning-payment.ts
Fix admin regression related to secret fields update
=> fix(admin): secret regression in invoice and payment lookup

.github/workflows/spelling.yml, ARCHITECTURE.md, README.md, spectaql/TUTORIAL.md, src/app/accounts/update-contact-alias.ts, src/config/app.ts, src/core/specter-wallet.ts, src/core/user-wallet.ts, src/domain/errors.ts, src/graphql/error-map.ts, src/graphql/error.ts, src/graphql/main/schema.graphql, src/graphql/root/mutation/user-contact-update-alias.ts, src/graphql/types/scalar/ln-pubkey.ts, src/graphql/types/scalar/payment-error-code.ts, src/migrations/migrate-mongo-config.js, src/servers/trigger.ts, src/services/bitcoind/index.ts, src/services/geetest.ts, src/services/jwt.ts, src/services/ledger/README.md, src/services/lnd/utils.ts, src/services/mongodb/index.ts, src/services/mongoose/schema.ts, src/services/notifications/notification.types.d.ts, src/services/pubsub.ts, test/integration/02-user-wallet/02-index.spec.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/core/lock.spec.ts, typos.toml
Found a project using https://github.com/crate-ci/typos and decided to run it - as the diff isn't very big I thought we may as well incorporate it.
=> chore: add spell checking via typos

.eslintrc.json, src/app/utils.ts, src/servers/trigger.ts, src/utils/index.ts, test/integration/core/lock.spec.ts, test/postman/newman.ts
settings this as a eslint-rule
=> chore: we have moved on using arrow functions

test/helpers/integration-server.ts
tested directly updating code in concourse container
=> fix: update kill signal for spawned process

src/servers/cron.ts, src/services/tracing.ts
- Remove cron main span
- Remove return on catch
- Move rebalance as last task
=> refactor: remove cron main span

src/services/tracing.ts
Tracing wrappers should not modify wrapped methods behavior. This is not a problem with our return model but for other methods that throw exceptions we should keep the same behavior
=> fix: error handling in tracing wrappers

docker-compose.yml, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/servers/graphql-main-server/auth-requests.spec.ts, test/integration/servers/graphql-main-server/galoy-pay-testing.spec.ts, test/integration/servers/graphql-main-server/no-auth-requests.spec.ts
- update docker-compose
- fix some test
=> refactor: - some error throw fix

ci/tasks/open-charts-pr.sh
Update PR title to use conventional commits spec
=> chore: update ci pr title

src/app/wallets/index.ts, src/graphql/types/object/consumer-account.ts
We had an n+1 issue in the resolver this PR fixes it.
Not sure about wether to return or throw on error
=> fix: n+1 in account.wallets gql resolver

ci/tasks/bump-image-digest.sh
Fix charts commit to support conventional commits
=> fix: charts commit message

src/migrations/20220118183759-remove-wallet-id-index.ts
we need this try/catch to make it pass in staging
=> fix: add try/catch to index removal to pass staging

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/create-on-chain-address.ts, src/app/wallets/index.types.d.ts, src/core/wallets.ts, src/servers/graphql-old-server.ts, src/services/rate-limit/index.ts, test/helpers/bitcoin-core.ts, test/helpers/rate-limit.ts, test/integration/02-user-wallet/02-invoice.spec.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/02-user-wallet/02-receive-rewards.spec.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/servers/trigger.spec.ts, test/integration/services/mongoose/wallet-invoices.spec.ts
this will allow for better ddos protection, in case someone wanted to create too many wallets
=> feat: make checkSelfWalletIdRateLimits at account level

src/app/wallets/ln-send-payment.ts, src/app/wallets/update-pending-invoices.ts, src/domain/wallet-invoices/index.types.d.ts, src/services/mongoose/wallet-invoices.ts, test/integration/services/mongoose/wallet-invoices.spec.ts
I don't think that's a good idea to expose the other field on the update. they should be immutable.
=> fix: only paid should be mutable

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/index.types.d.ts
reviewing https://github.com/GaloyMoney/galoy/pull/974 I noticed there were some functions being exported that aren't used anywhere so I removed some redundant code.
=> refactor: remove unused exports from add-invoice-for-wallet

src/app/lightning/update-ln-payments.ts
_Builds on #848_
This PR introduces changes to break the 'while' loop whenever an inconsistent pagination token comes back from lnd in the `updateLnPayments` method. This inconsistency can happen in two places here, and in its current state we don't handle this inconsistency well and can potentially end up with an infinite loop if `lnd` misbehaves.
I found this when testing some inconsistencies in the `lightning` package (see https://github.com/alexbosworth/lightning/pull/55).
=> fix: continue-token error handling in updateLnPayment

src/domain/ledger/index.types.d.ts, src/servers/trigger.ts, src/services/ledger/index.ts, src/services/ledger/transaction.ts
Move `settleOnchainPayment` to LedgerService
=> refactor: move settleOnchainPayment to LedgerService

test/integration/notifications/notification.spec.ts
Problem: `call.user.defaultWalletId` does not exist, user only has `defaultAccountId`
Test was passing because `getRecentlyActiveAccounts` was returning zero and this was because mock and `userActivenessMonthlyVolumeThreshold` were setup with 1000 sats (validation is greater than)
=> fix: send balance notification test

src/servers/exporter.ts
The second time that /metrics is requested (exporter) we got `"A metric with the name galoy_bitcoind_specter_XXX has already been registered."` error. 
This can be checked in production logs or running exporter in local env (`TEST="01|02|app/cold-storage/" make reset-integration` and then `make exporter`)
=> fix: cold wallet balance gauge already registered

src/graphql/root/mutation/onchain-payment-send-all.ts, src/graphql/root/mutation/onchain-payment-send.ts
fix type issues of https://github.com/GaloyMoney/galoy/pull/998
=> fix: on chain payment send types

src/domain/admin-users/index.ts, src/migrations/20220203152515-bootstrap_accounts.ts, src/servers/exporter.ts, src/services/ledger/caching.ts, src/services/ledger/index.ts, src/services/ledger/index.types.d.ts, src/services/mongodb/index.ts, test/helpers/user.ts
important note: they are under the same account. the dealer would programaticaly get the balance of both throught the normal graphql api
=> feat: create 2 wallets for the dealer

src/app/wallets/intraledger-send-payment.ts
the check that matters now is if this is from/to the same wallet
=> feat: remove account to account check

src/servers/exporter.ts
This should help us get insight regarding the wallet balance in honeycomb so we can better trigger alerts (for example when unchain wallet gets depleted).
=> fix: add span attributes for wallet balance

package.json, src/graphql/root/subscription/my-updates.ts, src/graphql/root/subscription/price.ts
Currently all users receive eachothers price subscription publishes. This fix scopes immediatePublishes to a single user.
=> fix: user specific price subscriptions

ci/pipeline.yml
Replaces https://github.com/GaloyMoney/galoy/pull/1067
=> ci: simplify resource flow in pipeline

src/app/wallets/reimburse-fee.ts, src/app/wallets/update-pending-payments.ts, src/services/ledger/index.types.d.ts, src/services/ledger/intraledger.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts
Cleanup PR, some things I came across while working on #1037
- removing some `null` & `void` values
- fixing one of our tests
=> chore: remove nulls and voids

docker-compose.yml
https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.14.2.md
it is already updated in charts https://github.com/GaloyMoney/charts/blame/main/charts/lnd/values.yaml#L9
=> build: update lnd version to v0.14.2

src/servers/trigger.ts, test/e2e/servers/graphql-main-server/galoy-pay-testing.spec.ts, test/e2e/servers/graphql-main-server/no-auth-requests.spec.ts, test/helpers/bitcoin-core.ts, test/helpers/lightning.ts, test/helpers/redis.ts, test/helpers/state-setup.ts
- Change limiter testing logic to reset all limiters not being testing
- Improve logging in state-setup
- Publish current price while subscribing to price updates
=> test: improve reliability

src/servers/trigger.ts, test/helpers/lightning.ts, test/helpers/redis.ts, test/helpers/state-setup.ts
Address post merge feedback of [PR #1074 ](https://github.com/GaloyMoney/galoy/pull/1074)
=> refactor: clean up test logging

Dockerfile, package.json, yarn.lock
=> fix: add google-protobuf to dependencies

src/domain/accounts/limits-checker.ts, src/services/ledger/index.types.d.ts, src/services/ledger/volume.ts
Add span attributes to improve visibility into limits checks.
=> chore: instrument tx volume checks

src/app/lightning/update-ln-payments.ts, src/app/users/get-user.ts, src/services/cold-storage/index.ts, src/services/ledger/index.ts, src/services/lnd/index.ts, src/services/lnd/onchain-service.ts, src/services/tracing.ts, src/services/twilio.ts
- Update missing params in asyncRunInSpan implementations
- Add tracing wrappers to main services (lnd offchain, lnd onchain, ledger and phone provider)
=> Add services tracing wrappers

src/app/wallets/send-lightning.ts, src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/domain/bitcoin/lightning/ln-invoice.ts, src/graphql/error-map.ts, src/services/lnd/index.ts, test/unit/domain/bitcoin/lightning/ln-invoice.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-factory.spec.ts
Includes two change around handling expired invoices:
1. Handle failing to delete an already expired invoice
2. Handle failing to pay an expired invoice
=> feat: handle expired invoices

src/domain/phone-provider/errors.ts, src/graphql/error-map.ts, src/services/twilio.ts
- Fix issue with phone numbers that are not mobile numbers https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/e87kJV34kYd/trace/tos9SreTB9d?span=e369056ecff9f12c
- Fix issue with phones from restricted regions https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/e87kJV34kYd/trace/J9H9NmNF3PJ?span=fbab50c27c6742a2
=> fix: twilio unkown exceptions

src/services/mongoose/wallets.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts
- Fix https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/k3psRSkCssd/trace/C7dUF9Wh4cV?span=22ee5be24a693e55
- Enable onchain tests (not sure why were disabled)
=> fix: onchain addresses null exception

src/debug/create-custom-invoices.ts, src/debug/migrate-ln-payments-listpayments.ts, src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/onchain/errors.ts, src/graphql/error-map.ts, src/graphql/root/query/globals.ts, src/services/lnd/index.ts, src/services/lnd/onchain-service.ts, src/services/lnd/utils.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/services/lnd/parse-errors.spec.ts
Fix lnd destructure issue detected here https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/bSeExQrTde8/trace/pGgx2roFG3D?span=4b1af4f5d2a54c2d 
This only happen when kube monkey attackt lnds but we should not return an exception
=> fix: lnd cannot destructure property lnd

src/servers/graphql-main-server.ts, src/servers/graphql-server.ts
Should fix current TestFlight failure
=> fix: only enabled Apollo usage reporting for main server

src/app/wallets/get-lightning-fee.ts, src/app/wallets/send-lightning.ts, src/graphql/root/mutation/ln-invoice-fee-probe.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts
Fix was to make sure the usd balance was converted to sats before comparing to payment amount in fee probe.
=> fix: convert usd balance to sats in feeProbe

src/graphql/types/object/usd-wallet.ts
- round down to the nearest cent in usd wallet api calls
=> fix: round usd balance

src/debug/create-wallets.ts, src/domain/errors.ts, src/domain/users/index.ts, src/graphql/error-map.ts, test/unit/domain/users/checked-to-accountlevel.spec.ts
This script has already been run on a live environment and works as expected
=> feat: add account generation script

default.yaml, package.json, src/config/error.ts, src/config/index.ts, src/config/schema.ts, src/config/yaml.ts, test/unit/config.spec.ts, yarn.lock
- validate yml config using json schema
=> refactor: validate config

src/services/ledger/domain/entry-builder.ts, src/services/ledger/send.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts
- Fix feeBuffer tests
- Fix missing currency property
- Fix currency destructure override
=> fix: ledger currency set

default.yaml, src/config/schema.ts
TestFlight is failing because the types don't match dev (see https://github.com/GaloyMoney/charts/blob/main/ci/testflight/galoy/testflight-values.yml#L9-L25).
=> fix: in prod test_account.code is number

default.yaml, src/config/schema.ts
This reverts commit e65d50e20de5d1a1e2eec90250610f524a8f0ae4.
=> revert: "fix: in prod test_account.code is number (#1159)"

src/services/ledger/domain/entry-builder.ts, src/services/ledger/domain/index.types.d.ts, src/services/ledger/intraledger.ts, src/services/ledger/receive.ts, src/services/ledger/send.ts, test/unit/services/ledger/domain/entry-builder.spec.ts
Continuing from #1152, this is WIP for swapping into receive ledger use-cases.
=> refactor: implement ln receive-side methods within entry builder

src/services/dealer-price/index.ts
- Revert rounding in dealer changes made in PR #1165
=> fix: remove rounding in dealer

.env.ci
my setup was timeout with 45s timeout time. works with 90s. 
what is your experience @dolcalmi ?
=> chore: better default settings?

src/app/errors.ts, src/domain/accounts/errors.ts, src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/onchain/errors.ts, src/domain/cache/errors.ts, src/domain/captcha/error.ts, src/domain/cold-storage/errors.ts, src/domain/dealer-price/errors.ts, src/domain/errors.ts, src/domain/errors.types.d.ts, src/domain/ipfetcher/errors.ts, src/domain/ledger/errors.ts, src/domain/lock/errors.ts, src/domain/notifications/errors.ts, src/domain/phone-provider/errors.ts, src/domain/price/errors.ts, src/domain/rate-limit/errors.ts, src/domain/shared/errors.ts, src/domain/shared/index.ts, src/domain/shared/index.types.d.ts, src/domain/twoFA/errors.ts, src/services/tracing.ts
This is a preparatory refactoring as a step towards implementing the ledger facade.
=> refactor: move DomainError to shared

src/app/wallets/get-on-chain-fee.ts, src/app/wallets/send-on-chain.ts, src/domain/errors.ts, src/graphql/error-map.ts, src/services/ledger/index.ts, src/services/tracing.ts
This builds from debugging the issue for PR #1153
=> chore: add instrumentation for balance and onchain fees

ARCHITECTURE.md, architecture.iuml
adding a diagrams make by an contributor on our slack (Zoop)
Diagram can be seen here formatted on this page: https://github.com/GaloyMoney/galoy/blob/c972116d7edda21d0b5ce3b9936de2fd1b978e64/ARCHITECTURE.md
=> chore: add iuml files

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/get-balance-for-wallet.ts, src/app/wallets/update-pending-invoices.ts, src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/lightning/index.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/domain/wallet-invoices/index.types.d.ts, src/domain/wallet-invoices/wallet-invoice-factory.ts, src/domain/wallet-invoices/wallet-invoice-factory.types.d.ts, src/graphql/error-map.ts, src/servers/cron.ts, src/servers/trigger.ts, src/services/lnd/index.ts, src/services/mongoose/schema.ts, src/services/mongoose/wallet-invoices.ts, test/e2e/servers/trigger.spec.ts, test/helpers/bitcoin-core.ts, test/helpers/check-is-balanced.ts, test/helpers/lightning.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/services/mongoose/wallet-invoices.spec.ts, test/jest-e2e.setup.js, test/unit/domain/wallet-invoices/wallet-invoice-factory.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts
the goal is to make sure whenever the lnd receive a payment, this is beein accounted in the ledger.
a follow up commit will decline the settlement of the invoices that have been missed by trigger
=> feat: use hodlInvoice

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/get-balance-for-wallet.ts, src/app/wallets/update-pending-invoices.ts, src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/lightning/index.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/domain/wallet-invoices/index.types.d.ts, src/domain/wallet-invoices/wallet-invoice-factory.ts, src/domain/wallet-invoices/wallet-invoice-factory.types.d.ts, src/graphql/error-map.ts, src/servers/cron.ts, src/servers/trigger.ts, src/services/lnd/index.ts, src/services/mongoose/schema.ts, src/services/mongoose/wallet-invoices.ts, test/e2e/servers/trigger.spec.ts, test/helpers/bitcoin-core.ts, test/helpers/check-is-balanced.ts, test/helpers/lightning.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/services/mongoose/wallet-invoices.spec.ts, test/jest-e2e.setup.js, test/unit/domain/wallet-invoices/wallet-invoice-factory.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts
This reverts commit 5f62c65248f55b6eac207e3ffbc7812c5f657939.
=> Revert "feat: use hodlInvoice (#1080)"

package.json, src/domain/ipfetcher/index.types.d.ts, src/services/ipfetcher/index.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts, test/unit/services/ipfetcher/fetch-ip-info.spec.ts, yarn.lock
these new fields are required to add new ip validations
=> feat: add asn and proxy to ip info

test/integration/02-user-wallet/02-send-lightning.spec.ts
Separate our integration tests that involve usd wallets into distinct sections
=> test: organise usd-send-lighting integration tests

default.yaml, src/app/accounts/add-earn.ts, src/config/schema.ts, src/config/yaml.ts, src/domain/errors.ts, src/domain/users/index.types.d.ts, src/domain/users/phone-metadata-validator.ts, src/domain/wallets/index.ts, src/graphql/error-map.ts, test/integration/02-user-wallet/02-receive-rewards.spec.ts, test/unit/app/prices/get-current-price.spec.ts, test/unit/app/prices/get-price-history.spec.ts, test/unit/domain/users/phone-metadata-validator.spec.ts, test/unit/services/lnd/onchain-service.spec.ts
Add whitelisted countries config/validation for rewards
=> feat: add rewards configuration

src/domain/shared/primitives.ts, src/services/ledger/domain/entry-builder.ts, src/services/ledger/domain/index.types.d.ts, src/services/ledger/facade.ts, src/services/ledger/index.types.d.ts, test/integration/services/ledger/facade.spec.ts, test/unit/services/ledger/domain/entry-builder.spec.ts
- improve ledger facade naming to clarify amount values to pass in
- change protocolFee to bankFee in EntryBuilder
=> refactor: improve naming in ledger facade

src/debug/void-payment.ts
This update will allow to fix error reported in support channel with a pending (ledger) failed (lnd) txs
=> fix: update void payment script to allow fix failed payments with pending ledger txs

default.yaml, src/app/accounts/add-earn.ts, src/config/schema.ts, src/config/yaml.ts, src/domain/errors.ts, src/domain/ipfetcher/index.types.d.ts, src/domain/users-ips/index.types.d.ts, src/domain/users-ips/ip-metadata-validator.ts, src/domain/users/index.types.d.ts, src/domain/users/phone-metadata-validator.ts, src/graphql/error-map.ts, src/services/ipfetcher/index.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts, test/helpers/user.ts, test/integration/02-user-wallet/02-receive-rewards.spec.ts, test/unit/domain/users-ips/ip-metadata-validator.spec.ts, test/unit/services/ipfetcher/fetch-ip-info.spec.ts
Add ip country and asn validation to rewards
=> feat: add rewards ip config

src/graphql/root/subscription/ln-invoice-payment-status.ts, src/services/tracing.ts
Adds error handling and undefined tracing parameters in response to https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/Gkh6DxJtBFj/trace/sXh5UNxkeRr?span=5b7f32ebb9bac57a
=> feat: subscription payment request input validation

package.json, src/debug/migrate-ln-payments-listpayments.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/services/lnd/index.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, yarn.lock
This is to update our internal `pending payments` and other lightning methods to reflect the changes in `lightning` introduced/uncovered in https://github.com/alexbosworth/lightning/pull/63
=> refactor: use new lnd pending payments library method

docker-compose.yml
update lnd according to https://github.com/GaloyMoney/charts/pull/872
=> build: update lnd version in docker compose

src/app/errors.ts, src/config/index.ts, src/domain/bitcoin/lightning/index.ts, src/domain/notifications/index.ts, src/domain/pubsub/errors.ts, src/domain/pubsub/index.ts, src/domain/pubsub/index.types.d.ts, src/graphql/error-map.ts, src/graphql/root/subscription/ln-invoice-payment-status.ts, src/graphql/root/subscription/my-updates.ts, src/graphql/root/subscription/price.ts, src/services/notifications/index.ts, src/services/pubsub.ts
Notification service refactor was bigger than expected so I decided to split it in 3 PRs.
This is the 1st PR that includes pubsub service refactor (pending task for a long time)
=> refactor: pubsub service

src/services/ledger/index.ts
This fixes a block from testing in staging where some wallets have float balances.
=> fix: handle float balances until db is corrected

src/app/payments/send-intraledger.ts, src/app/payments/send-lightning.ts, src/services/notifications/index.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts
Fix intraledger notifications amount
Note: this is a temporal fix because in the next PR the notifications interface will change (to receive display currency and display amount)
=> fix: intraledger notification usd amount

src/config/process.ts, src/services/lnd/health.ts
Add env variable for lnd health refresh time
Increase default refresh time from 10 to 20 seconds (reduce lnd load)
=> refactor: add env variable for lnd health refresh time

package.json, yarn.lock
=> chore(deps): update lodash merge dev-dependencies

package.json, src/config/utils.ts, src/config/yaml.ts, test/unit/config.spec.ts, test/unit/helpers/merge.ts, yarn.lock
Revert lodash merge changes until we change the yaml files in our infra to use the new merging.
=> Revert swap lodash merge

src/app/lightning/get-balances.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/domain/bitcoin/onchain/index.types.d.ts, src/servers/exporter.ts, src/services/lnd/index.ts, src/services/lnd/onchain-service.ts
Add all lnds balances to exporter
=> fix: add exporter support for multiple lnds

docker-compose.yml, test/integration/services/lnd/parse-errors.spec.ts
Please merge when chart is updated
=> chore: update lnd docker images to v0.15.0-beta

src/app/admin/backup.ts
This PR will change the destination of the lnd scb from the root of the bucket to a pseudo directory (`/lnd_scb`) within the same
=> chore: move lnd scb to subpath

src/app/accounts/send-default-wallet-balance-to-users.ts
Add early return when user does not have device tokens. This will "filter" bank accounts too
=> perf(daily-balance-notification): add early return when user does not have device tokens

src/graphql/types/scalar/sat-amount.ts
it is a warn to avoid unnecessary on-call alerts
=> chore: add alert for float in SatAmount input

src/app/wallets/update-pending-invoices.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts
Fix issue https://github.com/GaloyMoney/galoy/issues/1414
=> fix: update display amount to tx amount for usd txs

src/servers/trigger.ts, src/services/tracing.ts, test/e2e/servers/trigger.spec.ts
Fix missing root span in trigger event handlers
Old:
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/rABMv5pg86u/trace/jVeeJURF8vg?fields[]=c_name&fields[]=c_service.name&span=4d730af4cb6ea0e0
New
https://ui.honeycomb.io/galoy/datasets/jp-dev/result/ywVGn93bvBk
=> fix: missing root spans in trigger

src/services/lnd/index.ts
Handle the lnd error from [this trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/H4GaaJcBmDS/trace/C8E8E6BGx8C?fields[]=c_name&fields[]=c_service.name&span=9e2747e18a17cdcb)
```
[404,"UnknownPaymentHash",{"failures":[[404,"UnknownPaymentHash",{"height":744182,"index":2,"policy":null}]]}]
```
=> feat(err): add new Lnd error message

src/app/lightning/delete-ln-payments.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/services/lnd/index.ts
Help debug issue where all valid payments are not being deleted in the deletion loop in cronjob
=> chore: add temporary loggin to help debug delete-payments cronjob

src/app/lightning/delete-ln-payments.ts
=> chore: extend temporary logging to help debug delete-payments cronjob

src/app/lightning/delete-ln-payments.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/services/lnd/index.ts
Issues with deleting payments were addressed in PR #1437. This PR is to remove the temporary logging added to support that debugging.
=> chore: revert temporary debug logging commits

Makefile, src/app/index.ts, src/domain/wallets/tx-history.ts, src/graphql/main/mutations.ts, src/graphql/main/queries.ts, src/graphql/root/query/on-chain-tx-fee-query.ts, src/graphql/root/subscription/ln-invoice-payment-status.ts, src/graphql/root/subscription/my-updates.ts, src/graphql/root/subscription/price.ts, src/graphql/types/scalar/price-graph-range.ts, src/servers/graphql-server.ts, src/servers/middlewares/wallet-id.ts, src/services/dealer-price/dealer-price.ts, src/services/ledger/helpers.ts, src/services/ledger/index.ts, src/services/lnd/index.ts, src/services/lnd/utils.ts, src/services/tracing.ts
@dolcalmi if you want some Typescript types challenges: open this PR and see if you can remove my typescript directives and get the correct types :) 
this is the last PR that would activate no-implicity-any in the main codebase
=> chore: type improvement 6

src/app/wallets/add-invoice-for-wallet.ts, src/app/wallets/get-balance-for-wallet.ts, src/app/wallets/update-pending-invoices.ts, src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/lightning/index.ts, src/domain/bitcoin/lightning/index.types.d.ts, src/domain/wallet-invoices/errors.ts, src/domain/wallet-invoices/index.types.d.ts, src/domain/wallet-invoices/wallet-invoice-builder.ts, src/graphql/error-map.ts, src/servers/cron.ts, src/servers/trigger.ts, src/services/lnd/index.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts, src/services/mongoose/wallet-invoices.ts, test/e2e/servers/trigger.spec.ts, test/helpers/bitcoin-core.ts, test/helpers/check-is-balanced.ts, test/helpers/lightning.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/services/mongoose/wallet-invoices.spec.ts, test/jest-e2e.setup.js, test/unit/domain/wallet-invoices/wallet-invoice-builder.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts
This PR re-applies the same changes from #1188 on top of our new WalletInvoiceBuilder abstraction.
=> feat: hodl invoice (on WalletInvoiceBuilder)

dev/lnd/lnd.conf, src/services/lnd/utils.ts
=> feat: support anchor commitments in tests

src/app/lightning/delete-ln-payments.ts, src/app/lightning/update-ln-payments.ts, src/services/tracing.ts, test/integration/02-user-wallet/02-receive-rewards.spec.ts
Minor improvements from debugging delete-payments methods.
=> chore: fix tracing and improve code structure in delete-payments

src/app/shared/mid-price.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/services/dealer/mid-price.spec.ts
Fixes bug where we missed returning the mid-price-ratio dealer from dealer and were always falling back to previous non-dealer price server.
=> fix: add missing midPriceRatio return from dealer

src/debug/create-usd-wallets.ts
Fix issue with app dependencies that we first discovered [here](https://github.com/GaloyMoney/galoy/pull/1488/commits/be687e113b39b3f93471696524884889988ea287) in PR #1488, introduced by [this change](https://github.com/GaloyMoney/galoy/pull/1488/commits/8e202e075b6c2195bcc634c74daac96c4af16e41).
=> fix: 'app' dependency issue with 'allFunctions' construction

src/domain/accounts/account-validator.ts, src/domain/bitcoin/lightning/ln-invoice.ts, src/domain/fiat/display-currency.ts, src/domain/fiat/index.ts, src/services/mongoose/accounts.ts, src/services/mongoose/users.ts, test/helpers/bitcoin-core.ts
This PR cleans up some places where we introduced circular deps by importing from package-level `index.ts` files.
=> refactor: cleanup some circular index imports

src/graphql/types/object/business-account.ts, src/graphql/types/object/consumer-account.ts
fixes https://github.com/GaloyMoney/galoy/issues/1638
Looks like @samerbuna [was already aware of the issue](https://github.com/GaloyMoney/galoy/blob/main/src/graphql/connections.ts#L10-L18) but forgot to use the work around everywhere.
=> fix: use internal definition of connectionFromArray

src/domain/bitcoin/onchain/errors.ts, src/graphql/error-map.ts, src/graphql/error.ts, src/services/lnd/onchain-service.ts
Maps a new unknown onchain service error from lnd for CPFP ancestors limit when sending payments ([issue details](https://github.com/GaloyMoney/bitcoinbeach-support/issues/14#issuecomment-1237344520)).
=> chore: map unknown CPFPAncestor onchain error

dev/stablesats.yml
- disables hedging and user-trades
=> chore(stablesats): disable hedging and user-trades

ci/tasks/open-charts-pr.sh
So that charts PR title is proper
=> ci: use proper git ref

default.yaml, src/app/users/create-user.ts, src/app/users/login.ts, src/config/schema.ts, src/config/schema.types.d.ts, src/config/types.d.ts, src/config/yaml.ts, src/services/mongoose/schema.ts, test/helpers/user.ts, test/integration/app/accounts/multiple-wallet-account.spec.ts, test/integration/app/users/user-wallets.spec.ts, test/unit/domain/accounts/new-account.ts
This PR adds a config option that allows an instance owner to toggle whether USD wallets are also added for each new user created.
=> feat: add option to enable usd wallets globally

src/app/accounts/create-account.ts, src/app/accounts/index.ts, src/app/users/index.ts, src/app/users/login.ts, src/debug/create-wallets.ts, src/domain/accounts/index.ts, src/domain/accounts/index.types.d.ts, src/domain/errors.ts, src/domain/users/index.ts, src/domain/users/index.types.d.ts, src/graphql/error-map.ts, src/services/jwt.ts, src/services/mongoose/accounts.ts, src/services/mongoose/users.ts, test/helpers/user.ts, test/integration/app/accounts/multiple-wallet-account.spec.ts, test/integration/app/users/user-wallets.spec.ts
This PR move kratosUserId creation to Account and move some function calls from User to Account.
The idea is to continue deprecating current User domain as we're moving it to Kratos. This PR is in preparation of the kratos integration.
=> chore: move kratosUserId creation to Account

Makefile
follow up from https://github.com/GaloyMoney/galoy/commit/040eaafbd80a9a392ad9a34eb66b9d22712c9ccb
=> chore: remove now unecessary docker compose preflight command

src/domain/accounts/index.types.d.ts, src/domain/users/index.types.d.ts, src/graphql/root/query/me.ts, src/services/mongoose/accounts.ts, src/services/mongoose/users.ts, test/unit/domain/wallets/payment-input-validator.spec.ts
- for now. this is one of the last field that will not be migrated to kratos.
it should eventually be it's own collection but this can be done when a migration out of the main codebase is done with an apollo federation
=> chore: move quiz from domain user to account

src/app/payments/get-protocol-fee.ts
Related to: https://github.com/GaloyMoney/galoy/pull/1709#discussion_r982301045
=> chore(revert): changed dealer method inject in LPFB in get-protocol-fee

src/domain/bitcoin/lightning/errors.ts, src/domain/bitcoin/lightning/ln-invoice.ts, src/graphql/error-map.ts
Traces: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/ihXEPwA4KsQ
=> chore: map invalid checksum error for lninvoice decode

src/graphql/root/query/btc-price-list.ts
This fixes a [missing-code alert](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/kkPpGTnmoDH) that popped up a few days ago.
=> fix: missing codes for errors from 'BtcPriceList' query

src/domain/bitcoin/lightning/errors.ts, src/graphql/error-map.ts, src/services/lnd/index.ts
Traces: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/cndkT248te4
=> chore: map new 'TemporaryChannelFailureError' lightning error

src/app/accounts/create-account.ts, src/app/payments/send-intraledger.ts, src/domain/accounts/index.types.d.ts, src/migrations/20220922030802-update-contact-enabled.ts, src/services/mongoose/accounts.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts, test/helpers/user.ts, test/unit/domain/wallets/payment-input-validator.spec.ts
Split PR according to https://github.com/GaloyMoney/galoy/pull/1691#issuecomment-1254949049
=> feat: add contact enabled setting

test/integration/01-setup/01-connection.spec.ts
there is no need to setup the connection again (this was actually misleading me)
=> chore: connection in jest.setup.js already

src/domain/dealer-price/errors.ts, src/graphql/error-map.ts, src/services/dealer-price/dealer-price.ts
Map dealer stale price error ([traces](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/eFdejpwXryH?hideMarkers))
=> chore: map dealer stale price error

src/config/schema.ts
another fallout from my refactoring
=> chore: fix main with default config, 3

galoy.yaml, src/config/schema.ts, src/config/schema.types.d.ts, src/config/yaml.ts, src/domain/wallets/tx-history.ts, test/unit/domain/wallets/tx-history.spec.ts
updated code from https://github.com/GaloyMoney/galoy/pull/1084
=> fix: add usd wallets memo filter

src/config/schema.ts, src/config/yaml.ts
also: revert new default added yesterday
=> chore: doing deep copy for default config again

src/app/users/login.ts
Adding new login span attr in order to do further investigation on this https://github.com/GaloyMoney/galoy/pull/1755
=> chore: add new account attribute to login methods

docker-compose.yml
hot fix for the LND wire parsing bug https://github.com/lightningnetwork/lnd/pull/7004
=> chore: update lnd docker images to v0.15.2-beta

src/servers/graphql-server.ts, src/servers/index.files.d.ts
=> chore: Revert "chore: improve error message when no token is present"

src/servers/graphql-server.ts
Fix invalid validation for unauthorized txs - https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/A4uUT5MhckH/a/hWwDryEwE7n
How to test:
```
query me {
me {
id
}
}
```
=> fix: update isAuthenticated validation

src/servers/graphql-server.ts, src/servers/index.files.d.ts
=> chore: Revert "chore: Revert "chore: improve error message when no token is present""

src/servers/graphql-main-server.ts, src/servers/graphql-server.ts
I don't think we use it anymore?
=> chore: remove apollo usage reporting

src/servers/graphql-server.ts
seems a potential description of our issue here: https://github.com/nodejs/node/issues/44228
=> chore: new attempt node18

docs/swap.md, src/app/swap/swap-listener.ts, src/app/swap/swap-out.ts, src/domain/swap/errors.ts, src/domain/swap/index.types.d.ts, src/domain/swap/swap-out-checker.ts, src/servers/trigger.ts, src/services/loopd/loop-service.ts, test/integration/app/swap/swap-listener.spec.ts, test/integration/app/swap/swap-out.spec.ts, test/unit/domain/swap/swap-out-checker.spec.ts
This PR adds better Honeycomb tracing for swaps. It also adds logic to not start the swapListener if swaps are not enabled in the default.yaml
=> feat: add better swap tracing

src/domain/bitcoin/lightning/errors.ts, src/graphql/error-map.ts, src/services/lnd/index.ts
- Maps `UnknownNextPeer` errors ([trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/z9mrLRw5nAM/a/kkvfU5XbWbH))
=> feat: map `UnknownNextPeer` lnd error

test/e2e/trigger.fn.spec.ts
Price rounding can sometimes cause this notification check to fail because of subtle differences in the price between function call and comparison value call in the test. For e.g., for the following error message:
```
galoy-e2e-e2e-tests-1  |     expect(received).toBe(expected) // Object.is equality
galoy-e2e-e2e-tests-1  | 
galoy-e2e-e2e-tests-1  |     Expected: "+$0.09 | 500 sats"
galoy-e2e-e2e-tests-1  |     Received: "+$0.1 | 500 sats"
galoy-e2e-e2e-tests-1  | 
galoy-e2e-e2e-tests-1  |       241 |     expect(sendNotification.mock.calls.length).toBe(1)
galoy-e2e-e2e-tests-1  |       242 |     expect(sendNotification.mock.calls[0][0].title).toBe(title)
galoy-e2e-e2e-tests-1  |     > 243 |     expect(sendNotification.mock.calls[0][0].body).toBe(body)
galoy-e2e-e2e-tests-1  |           | …
```
=> test(fix): accommodate for price rounding in notif comparison

src/app/auth/index.ts
also, throw if we are not able to get the list of users, so that it get logged correctly on opentelemetry
=> chore: adding more opentelemetry for cron/extendSession

src/debug/migrate-users-to-kratos.ts, src/services/kratos/identity.ts, test/integration/services/kratos/index.spec.ts
bug filed here: https://github.com/ory/kratos/issues/2834
=> chore: some pagination fix for kratos

src/app/prices/get-current-price.ts, src/app/prices/get-price-history.ts, src/domain/cache/index.types.d.ts, src/servers/middlewares/update-token.ts, src/servers/trigger.ts, src/services/cache/local-cache.ts, src/services/cache/redis-cache.ts, src/services/lnd/onchain-service.ts, test/unit/app/prices/get-current-price.spec.ts, test/unit/app/prices/get-price-history.spec.ts
- refactor ICacheService interface so that named arguments can be redacted from telemetry
=> chore: enable cache span redaction

spectaql/TUTORIAL.md
Tried downloading the postman collection, but the link was broken. Updating to the correct link.
=> docs: fixing postman collection link in TUTORIAL.md

src/app/cold-storage/rebalance-to-cold-wallet.ts
Update offchain balance method to include lnd1 and lnd2 balances
=> fix: coldstorage offchain balance

src/graphql/types/object/graphql-user.ts
Fix missing error code for contactByUsername
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/6HsaAJy7xVz/a/eUPdVkxwrXL
=> fix: handle missing error code alert for contactByUsername

Makefile, docker-compose.yml, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/02-user-wallet/02-send-lightning-limits.spec.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts, test/integration/app/wallets/invoice.spec.ts, test/integration/notifications/notification.spec.ts, test/integration/services/dealer/mid-price.spec.ts, test/jest-integration.setup.js
working on reducing the number of dependancies for the integration tests
=> tests: remove price from integration tests

test/helpers/user.ts, test/integration/02-user-wallet/02-send-lightning-limits.spec.ts, test/integration/02-user-wallet/02-z-arbitrage.spec.ts, test/integration/services/dealer/hedge-price.spec.ts
This PR is to start adding a set of test cases to ensure our use-cases are configured properly with the dealer conversion functions they use for different pathways.
=> test: add cases for hedge-price usage

src/app/wallets/get-transactions-by-addresses.ts, src/app/wallets/get-transactions-for-wallet.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/servers/trigger.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/unit/domain/wallets/tx-history.spec.ts
Split from https://github.com/GaloyMoney/galoy/pull/1916 that includes only onchain pending receipt amount fix
=> fix: onchain pending receipt amount

src/migrations/2022113010370802-users-migration-1.ts, src/migrations/2022120510370802-fix-migration.ts, test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts
@nicolasburtey could you please check this version of https://github.com/GaloyMoney/galoy/pull/1978
=> fix: update user kratos migration

src/services/notifications/index.ts
it seems not awaiting for notification may leak to memory leaks
=> chore: await for notification

src/app/accounts/update-account-ip.ts
so !proxy is not such a good idea!
=> fix: proxy value can be false

src/services/twilio.ts
Change to switch and add new cases to handle these unknown errors: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/gu6iWKxazW7?hideMarkers
=> refactor: change twilio error handling to switch

src/app/prices/index.ts, src/app/prices/list-currencies.ts, src/domain/cache/index.ts, src/domain/price/errors.ts, src/domain/price/index.types.d.ts, src/graphql/error-map.ts, src/graphql/main/queries.ts, src/graphql/root/query/currency-list.ts, src/graphql/types/object/currency.ts, src/services/price/index.ts, src/services/price/protos/price.proto, test/unit/app/prices/get-current-price.spec.ts, test/unit/app/prices/get-price-history.spec.ts, test/unit/app/prices/list-currencies.spec.ts
- Add currency list query
- Update price service
https://github.com/GaloyMoney/price/pull/34 is required before merge
How to test:
- Run `make start-deps`
- Run `make start-main-fast`
- Open http://localhost:4002/graphql or use postman to run:
```graphql
query CurrencyList {
currencyList {
code
symbol
name
flag
}
}
```
=> feat: add currencyList public query

galoy.yaml
Fix unit test error https://ci.galoy.io/teams/dev/pipelines/galoy-app/jobs/test-unit/builds/1383
=> fix: update galoy yaml

test/helpers/account-creation-e2e.ts
null is considered toBeDefined!
=> fix: test for account creation

src/app/errors.ts, src/graphql/error-map.ts
Kratos errors are not handled properly. Found it testing logout in staging https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/5CSFNuGLcyT/a/dUuddMZB6pN
=> fix: handle properly kratos errors

src/domain/accounts/limits-checker.ts, test/integration/02-user-wallet/02-send-lightning-limits.spec.ts
Changes the limits error message to return dollars instead of cents.
=> refactor: change limits message usd format

src/domain/phone-provider/errors.ts, src/graphql/error-map.ts, src/services/twilio.ts
Map new recently detected twilio errors (see [trace)](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/bFvmKkSqcXb)
=> chore: add new twilio error msgs

package.json, src/domain/routes/index.types.d.ts, src/graphql/root/query/btc-price-list.ts, src/services/lnd/index.ts, yarn.lock
fix an issue https://github.com/alexbosworth/lightning/issues/121 generated by new types in lightning library
related PR: https://github.com/GaloyMoney/galoy/pull/2156
=> fix: update fee probe with new lightning types

src/services/kratos/cron.ts
Add exception handling to avoid session extender crash (cron)
=> chore: add exception handling to extendSession

src/services/dealer-price/dealer-price.ts, src/services/tracing.ts
This attribute will be used to create an alerting SLO that can check what percentage of these calls come back with an error.
=> feat: add 'slo.dealerCalled' attribute to all dealer method spans

src/app/admin/update-user-phone.ts
`slowFindByPhone` does not return all the results. I couldn't find exactly how many, but the cli tool with the same api returns 250 results. Hence, I'm now using the user collection for obtaining the kratosUserId instead.
=> refactor: remove use of slowFindByPhone

src/graphql/admin/schema.graphql
=> chore: add updated admin schema

src/services/twilio.ts
Trace: [link](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/cVqfHtLWBFD/trace/8mFGP6wPPWJ?fields[]=c_name&fields[]=c_service.name&span=3173ead06736557b)
=> chore: add new twilio restricted region error

package.json, src/app/index.ts, src/app/transactions/get-transactions-metadata-by-ids.ts, src/app/transactions/index.ts, src/domain/ledger/errors.ts, src/domain/ledger/index.types.d.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/graphql/error-map.ts, src/graphql/types/abstract/settlement-via.ts, src/graphql/types/object/transaction.ts, src/servers/graphql-server.ts, src/servers/index.files.d.ts, src/services/ledger/domain/index.types.d.ts, src/services/ledger/services/transactions-metadata.ts, src/utils/index.ts, test/unit/domain/wallets/tx-history.spec.ts, yarn.lock
This reverts commit d41a554497c20316602bd52689b326565127196a.
=> revert: resolve txn metadata with dataloader (#2252)

src/graphql/types/object/transaction.ts, src/services/ledger/services/transactions-metadata.ts
This PR fixes 2 issues with txnMetadata dataloader and removes the debug attributes added in #2300
=> fix: ordering & error-handling issues with dataloader

src/graphql/main/schema.graphql, src/graphql/root/query/currency-list.ts
Update currencyList query to return a mandatory list. This helps to work with cache in mobile app
=> fix: update currency list return to be mandatory

src/domain/notifications/errors.ts, src/graphql/error-map.ts, src/services/notifications/index.ts, src/services/notifications/push-notifications.ts
Add new error for [trace](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/7E7LheBHoYN/trace/AzV9tew4cD5?fields[]=c_name&fields[]=c_service.name&span=b88845950e12d57a)
=> chore: add new notifications bad gateway error

src/services/twilio.ts
Fix unhandled error`Invalid parameter: Code` in twilio service
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/AtDHUrsHL5u/a/4y2Jxse2xNp
=> fix: twilio invalid code parameter unknown error

src/app/wallets/create-on-chain-address.ts, src/app/wallets/get-last-on-chain-address.ts, src/app/wallets/update-on-chain-receipt.ts, src/graphql/root/mutation/on-chain-address-current.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/app/trigger/trigger.fn.spec.ts
Create new onchain address after using the current address
=> feat: create new onchain address after use current address

.github/workflows/audit.yml, .github/workflows/e2e-test.yml, .github/workflows/generate-graphql-docs.yml, .github/workflows/integration-test.yml, .github/workflows/mongodb-migrate.yml, .github/workflows/nodejs-check-code.yml, .github/workflows/unit-test.yml
@dolcalmi it seems we could speed up our test quite a bit with the cache. assigning it to you in case you want to have a deeper look.
=> chore: test using cache

src/services/ledger/paginated-ledger.ts, src/services/ledger/schema.ts
reverts https://github.com/GaloyMoney/galoy/pull/2359 + add new index
=> fix: remove allowDiskUse + add new index to support _id sort

src/graphql/main/schema.graphql, src/graphql/types/object/currency.ts
Update currencyList query to use id instead of code
=> fix: add id to currencyList

src/graphql/types/object/graphql-user.ts
Fix non null issue https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/whekWQ6HrdM/trace/eMaE4mAYKcY?fields[]=c_name&fields[]=c_service.name&span=e11d50a40e5cb0b5
=> fix: resolve language from user context

src/graphql/root/subscription/my-updates.ts, src/services/notifications/index.ts
Trigger price event only when display currency is USD
=> fix: trigger price event only when display currency is usd

src/services/ledger/schema.ts
Merge before https://github.com/GaloyMoney/galoy/pull/2383
=> fix: remove enum from ledger tx display currency

src/app/payments/send-intraledger.ts, src/app/payments/send-lightning.ts, src/app/payments/update-pending-payments.ts, src/app/wallets/reimburse-fee.ts, src/app/wallets/send-on-chain.ts, src/domain/fiat/display-currency.ts, src/domain/fiat/index.types.d.ts, src/domain/shared/primitives.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts, test/integration/02-user-wallet/02-send-onchain.spec.ts
This PR swaps out the `NewDisplayCurrencyConverter` for `DisplayPriceRatio` for conversions.
=> refactor: swap out NewDisplayCurrencyConverter

src/config/locales/en.json, src/config/locales/es.json, src/config/yaml.ts, src/services/notifications/create-push-notification-content.ts, test/unit/services/notifications/transactions.ts
- Remove currency symbol/name dependency from locale files
- Use default behavior from Intl.NumberFormat
=> refactor: update createPushNotificationContent to use Intl.NumberFormat

src/app/accounts/send-default-wallet-balance-to-users.ts, src/app/payments/send-lightning.ts, src/app/prices/get-current-price.ts, src/app/wallets/get-transactions-by-addresses.ts, src/app/wallets/get-transactions-for-wallet.ts, src/app/wallets/send-on-chain.ts, src/app/wallets/update-on-chain-receipt.ts, src/app/wallets/update-pending-invoices.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/graphql/root/subscription/price.ts, src/servers/trigger.ts, test/helpers/bitcoin-core.ts, test/helpers/lightning.ts, test/integration/02-user-wallet/02-receive-lightning.spec.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/02-user-wallet/02-tx-display.spec.ts, test/integration/app/cold-storage/rebalance-to-cold-wallet.spec.ts, test/integration/notifications/notification.spec.ts, test/jest-integration.setup.js, test/mocks/get-current-price.ts, test/mocks/price.ts, test/unit/domain/wallets/tx-history.spec.ts
This PR is to remove hardcoded display currency values and to pass through the configured display currency on users' accounts in our different use-cases.
=> refactor: remove hardcoded display currency values in codebase

yarn.lock
@dolcalmi 
Do you think this will fix ci error? 
```
Unpacking nodejs deps... 
Extracting deps has created a diff - deps are not in sync
diff --git a/yarn.lock b/yarn.lock
```
I pulled down main and did a yarn install and this yarn.lock was the diff
=> chore: sync yarn lock

src/graphql/root/subscription/price.ts
Fix: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/nv84r9REiin/a/4y2Jxse2xNp
How to test:
In staging https://api.staging.galoy.io/graphql use the next subscription and wait for the second message.
```graphql
subscription {
price(input:{amount:1, amountCurrencyUnit:BTCSAT, priceCurrencyUnit: USDCENT}) {
errors {
message
}
price {
base
offset
currencyUnit
formattedAmount
}
}
}
```
=> fix: no price info error in deprecated price subscription

src/app/payments/get-protocol-fee.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts
This PR fixes the issue where a 1-sat payment results in an internal PaymentFlow price ratio of `1` which causes the limit check to consider the sats volume it is passed as equivalent to a cents volume. 
The fix is to use a higher precision mid-price ratio as we do in other send-payment flows instead of the internal PaymentFlow ratio.
=> fix: 1-sat amount limits check fails

src/servers/cron.ts
Adds a `jobCompleted` attribute to the top-level cronjob span that only gets set to `true` after each cronjob completes. This is to determine if a job times out silently.
=> chore: add cron span attribute to track job completion

src/servers/cron.ts
Adds back `task` function names that were inadvertently removed in #2497
=> chore: add back task name to anonymous cronjob function

src/services/lnd/health.ts
reduce log noise in cron and probably in gcloud logs
=> chore: update lnd pulse log level

src/servers/cron.ts
=> chore: add back task name via wrapped function arg

src/app/auth/index.ts, src/servers/cron.ts
Adds more logging for cronjob tasks to help track their end as well.
=> chore: add cronjob-finished logging

docker-compose.yml
=> chore: update lnd to 0.16

.prettierignore
ignore the ci yamls in prettier
=> ci: ignore ci yamls in prettier

src/app/payments/helpers.ts, src/app/payments/send-intraledger.ts, src/app/payments/send-lightning.ts, src/domain/accounts/index.types.d.ts, test/integration/02-user-wallet/02-send-lightning.spec.ts
Save contacts After making lightning payment between two bbw users
=> feat:save contacts after making intra ledger payment

docker-compose.yml
related update in charts: https://github.com/GaloyMoney/charts/pull/2874
=> chore: update lnd images to v0.16.1

src/app/auth/login.ts, src/app/auth/logout.ts, src/domain/authentication/index.types.d.ts, src/services/kratos/auth-email-no-password.ts, src/services/kratos/auth-phone-no-password.ts, test/e2e/servers/ory/kratos.spec.ts
- Refactor kratos auth services to use interfaces
- Move code that throw to try/catch blocks
- Update func params to support redaction https://github.com/GaloyMoney/charts/pull/2964
- Add tracing
ps: probably will need a full refactor (another PR), specially for functions in kratos service index file
=> refactor: update kratos auth services

dev/ory/oathkeeper.yml, dev/ory/oathkeeper_rules.yaml, docker-compose.yml
can one of you take this ticket and make sure this header in our chart/deployment is removed? we no longer use/need it
=> chore: deprecate legacy header

docker-compose.yml
related to https://github.com/GaloyMoney/charts/pull/3006 and https://github.com/GaloyMoney/charts/pull/2995
=> chore: update lnd version to v0.16.2-beta

src/graphql/connections.ts, test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts
Fix issue https://github.com/GaloyMoney/galoy/issues/2607
=> fix: add cursor validation at graphql layer

src/app/wallets/update-on-chain-receipt.ts, src/domain/bitcoin/onchain/index.types.d.ts, src/domain/bitcoin/onchain/tx-decoder.ts, src/domain/ledger/index.types.d.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/tx-history.ts, src/graphql/admin/schema.graphql, src/graphql/main/schema.graphql, src/graphql/types/abstract/settlement-via.ts, src/services/ledger/domain/index.types.d.ts, src/services/ledger/index.ts, src/services/ledger/index.types.d.ts, src/services/ledger/schema.ts, src/services/ledger/schema.types.d.ts, src/services/ledger/tx-metadata.ts, test/integration/services/cache/index.spec.ts, test/integration/services/ledger/helpers.ts, test/unit/domain/bitcoin/onchain/incoming-tx-handler.spec.ts, test/unit/domain/bitcoin/onchain/tx-decoder.spec.ts, test/unit/domain/bitcoin/onchain/tx-filter.spec.ts, test/unit/domain/wallets/tx-history.spec.ts, test/unit/services/ledger/domain/tx-metadata.spec.ts
required for bria integration. check https://github.com/GaloyMoney/galoy/pull/2622#discussion_r1192947785 and https://github.com/GaloyMoney/galoy/pull/2610
=> feat: add vout to onchain receipt

.github/workflows/audit.yml, .github/workflows/check-code.yml, .github/workflows/e2e-test.yml, .github/workflows/generate-graphql-docs.yml, .github/workflows/integration-test.yml, .github/workflows/mongodb-migrate.yml, .github/workflows/unit-test.yml, .github/workflows/vendor/nodejs-audit.yml, .github/workflows/vendor/nodejs-check-code.yml, docker-compose.yml, package.json, src/app/payments/update-pending-payments.ts
=> chore: update node test

.gitignore, Dockerfile, Dockerfile-debug, Dockerfile-migrate, Dockerfile-websocket, docker-compose.yml, package.json, test/e2e/generated.ts, test/jest-e2e.config.js, test/jest-e2e.setup.js, test/jest-integration.config.js, test/jest-integration.setup.js, test/jest-unit.config.js, test/swc-config.json, yarn.lock
had to hardcode `@apollo/client` because it has a bug
=> feat!: update to nodejs 20

Makefile, ci/tasks/test-e2e.sh, ci/tasks/test-integration.sh
Fix permission issue with .swc folder (is created from containers)
=> ci: use sudo to remove .swc folder

src/services/cold-storage/index.ts
Temporary fix to reduce alerts noise while this PR is finished https://github.com/GaloyMoney/galoy/pull/2653
=> fix: temp fix for coldstorage getbalance

src/app/wallets/update-on-chain-receipt.ts, src/servers/trigger.ts, test/integration/app/trigger/trigger.fn.spec.ts
Merge after https://github.com/GaloyMoney/galoy/pull/2708
Changes https://github.com/GaloyMoney/galoy/compare/fix-debounce-block-handler...fix-subscribe-block-bria-race-condition
=> fix: dont process bria txs in onchainBlockEventHandler

src/graphql/error-map.ts, src/services/kratos/errors.ts, src/services/kratos/index.ts
I'll make a revert PR on main so we can integrate proper tests for this function
=> chore: remove unused revoke kratos token

src/services/bria/index.ts, src/utils/grpc-stream-client/index.types.d.ts, src/utils/grpc-stream-client/stream-builder.ts, src/utils/grpc-stream-client/stream.ts
- Update on error handler to get sequence from db and not from memory
- Add request type to all events
=> fix: update bria sequence from db on error

ci/pipeline.yml
=> ci: use test_on_docker_host

src/app/wallets/add-pending-on-chain-transaction.ts, src/app/wallets/add-settled-on-chain-transaction.ts, src/servers/event-handlers/bria.ts, test/integration/02-user-wallet/02-bria-handlers.spec.ts
- Remove pending utxo before address creation
- Add validation of tx (exists in ledger) in pending handler to handle properly reprocessing of the bria events
- Add dust validation in pending and settled handlers
=> fix: pending utxo removal + dust amount validation

src/app/accounts/mark-account-for-deletion.ts, src/domain/users/index.types.d.ts, src/services/mongoose/users.ts
it's not used for authentication
=> chore: no need to rename deviceId anymore

test/integration/02-user-wallet/02-send-onchain.spec.ts
This line would solve almost all recent concourse issues.
=> test: tmp comment flaky assertion

package.json, yarn.lock
removing some resolutions which seems to no longer be necessary
=> chore: update yarn

CONTRIBUTING.md, galoy.yaml, src/app/wallets/add-pending-on-chain-transaction.ts, src/app/wallets/add-settled-on-chain-transaction.ts, src/config/schema.ts, src/config/schema.types.d.ts, src/config/yaml.ts, src/domain/accounts/index.types.d.ts, src/domain/payments/index.types.d.ts, src/domain/wallets/deposit-fee-calculator.ts, src/domain/wallets/index.types.d.ts, src/services/mongoose/accounts.ts, src/services/mongoose/schema.ts, test/helpers/index.ts, test/integration/02-user-wallet/02-receive-onchain.spec.ts, test/integration/app/trigger/trigger.fn.spec.ts, test/unit/domain/wallets/deposit-fee-calculator.spec.ts, test/unit/domain/wallets/payment-input-validator.spec.ts
Update onchain fee receive logic according to ACE 24
=> feat: update deposit fee structure

src/graphql/main/schema.graphql, src/graphql/root/query/globals.ts, src/graphql/types/object/fees-information.ts, src/graphql/types/object/globals.ts, test/e2e/generated.ts, test/e2e/servers/graphql-main-server/no-auth-requests.spec.ts, test/e2e/servers/graphql-main-server/with-auth-requests.spec.ts, test/unit/domain/wallets/deposit-fee-calculator.spec.ts
Merge after https://github.com/GaloyMoney/galoy/pull/2784
=> feat: add fees information to global query

src/migrations/20230621225319-remove-deposit-fee-ratio.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts
Merge after https://github.com/GaloyMoney/galoy/pull/2784
=> chore: remove depositFeeRatio from accounts collection

ci/pipeline.yml
This has already been applied to concourse
=> ci: add ws img to release job

galoy.yaml, src/app/auth/login.ts, src/app/auth/request-phone-code.ts, src/config/schema.ts, src/config/schema.types.d.ts, src/config/yaml.ts, src/domain/rate-limit/errors.ts, src/domain/rate-limit/index.ts, src/graphql/error-map.ts, test/e2e/servers/graphql-main-server/no-auth-requests.spec.ts, test/helpers/rate-limit.ts
first PR in preparation for reviewing https://github.com/GaloyMoney/galoy/pull/2713 (aiming at reducing the diff)
=> chore: request change renaming

docker-compose.yml
2/6 failed... still not perfect but much better
=> test(e2e): fix bria dev wallet not found

src/servers/graphql-main-server.ts, src/servers/graphql-server.ts
some TODO:
- we should make sure we nudge mobile user to update to the last version (last mobile release ~1 month point to new independant websocket endpoint)
- see if this only make a degraded experience for older mobile, and not a crash
=> chore!: remove websocket from main server

test/bats/gql/ln-invoice-payment-status.gql, test/bats/helpers/ln.bash, test/bats/ln-receive.bats, test/bats/public-ln-receive.bats, test/bats/public.bats
This test requires alice to be logged in and lnds to be initialized. Instead of adding these to 'public.bats' we instead can move the tests to a file where these are already being initialized.
=> test: move public invoice-creation to ln-receive tests

test/legacy-integration/02-user-wallet/02-tx-onchain-fees.spec.ts
Fixes a flaky issue that came in at some point: [ci build](https://ci.galoy.io/teams/dev/pipelines/galoy-app/jobs/integration-tests/builds/281)
=> test: move walletIdUsdA funding higher up

docker-compose.yml, test/bats/oathkeeper.bats
Attempt at cleaning up `OATHKEEPER_ENDPOINT` in tests based on https://github.com/GaloyMoney/galoy/pull/3030#discussion_r1288524123
=> test: set OATHKEEPER_ENDPOINT from env variables only

src/migrations/2022113010370802-users-migration-1.ts, src/migrations/2022121620560802-remove-phone-code.ts, src/migrations/20230807205306-add-uuid-to-accounts.ts, src/services/mongoose/accounts.ts, src/services/mongoose/schema.ts, src/services/mongoose/schema.types.d.ts
Please dont merge until e2e is fixed in CI. this PR needs to be deployed after code update
=> chore: add account UUID migration

quickstart/dev/svix/README.md, quickstart/docker-compose.yml, quickstart/galoy/.envrc, quickstart/galoy/dev/svix/README.md, quickstart/galoy/docker-compose.override.yml, quickstart/galoy/docker-compose.yml, quickstart/galoy/test/bats/gql/intraledger-usd-payment-send.gql, quickstart/vendir.lock.yml
Quickstart needs re-rendering after https://github.com/GaloyMoney/galoy/pull/3043 as it is not yet automated in concourse.
=> chore: re-render quickstart

test/helpers/user.ts, test/integration/app/accounts/get-transactions-for-accounts.spec.ts, test/integration/app/wallets/add-invoice-for-wallet.spec.ts, test/integration/app/wallets/create-on-chain-address.spec.ts, test/integration/app/wallets/get-last-on-chain-address.spec.ts, test/integration/app/wallets/send-intraledger.spec.ts, test/integration/app/wallets/send-lightning.spec.ts, test/integration/app/wallets/send-onchain.spec.ts, test/legacy-integration/02-user-wallet/02-bria-handlers.spec.ts, test/legacy-integration/02-user-wallet/02-receive-onchain.spec.ts
=> test: add 'fails to send less-than-1-cent' integration tests

src/config/env.ts
Temp fix. Todo we can revert it after the charts fix
=> fix: lnd2 as default primary

src/config/env.ts
=> Revert "fix: lnd2 as default primary"

src/app/index.ts, src/graphql/public/root/mutation/user-email-delete.ts, src/graphql/public/root/mutation/user-email-registration-initiate.ts, src/graphql/public/root/mutation/user-email-registration-validate.ts, src/graphql/public/root/mutation/user-login-upgrade.ts, src/graphql/public/root/mutation/user-phone-delete.ts, src/graphql/public/root/mutation/user-phone-registration-initiate.ts, src/graphql/public/root/mutation/user-phone-registration-validate.ts, src/graphql/public/root/mutation/user-totp-delete.ts, src/graphql/public/root/mutation/user-totp-registration-initiate.ts, src/graphql/public/root/mutation/user-totp-registration-validate.ts, src/graphql/shared/root/mutation/captcha-request-auth-code.ts, src/graphql/shared/root/mutation/user-login.ts, src/graphql/shared/root/mutation/user-request-auth-code.ts, src/servers/authorization/cookies.ts, src/servers/authorization/device-account.ts
to remove confusion with auth that could also mean authorization
=> chore: renaming auth to authentication

test/bats/ln-send.bats, test/legacy-integration/02-user-wallet/02-send-lightning.spec.ts.skip
=> test: move probe vs. no-probe ln send tests to bats

quickstart/bin/helpers.sh, quickstart/bin/init-lightning.sh, quickstart/bin/init-onchain.sh, quickstart/bin/quickstart.sh, quickstart/galoy/test/bats/gql/contacts.gql, test/bats/gql/wallets-for-account.gql
Some refactoring of the Quickstart scripts to make it simpler to use individual steps in dependant projects.
=> refactor: decompose quickstart script

test/helpers/user.ts, test/legacy-integration/02-user-wallet/02-send-lightning-limits.spec.ts
This removes the helper functions that contained a lot of code re-use and conditional paths to execute tests against.
=> test: refactor limits tests to remove overloaded helpers

src/servers/graphql-admin-server.ts, src/servers/graphql-main-server.ts
Fix not authorized missing error code
- Alert https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/vNjxmH95gzk
- Fixed trace (test): https://ui.honeycomb.io/galoy/datasets/jp-dev/result/fcmZLnUDB6b
=> fix: add authorization error code to shield plugin

src/domain/errors.ts, src/graphql/error-map.ts, src/services/mongoose/accounts.ts
Fix unknown (CouldNotFindAccountError) error https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/CE42VvXhMqi
=> fix: unkown invalid account id error

src/servers/graphql-main-server.ts, src/servers/graphql-server.ts, src/servers/middlewares/session.ts
- adding the attributes in the span in place instead of 2
=> chore: refactor public context

src/app/wallets/add-pending-on-chain-transaction.ts, src/app/wallets/update-pending-invoices.ts, src/domain/payments/onchain-payment-flow-builder.ts, src/domain/payments/payment-flow-builder.ts, src/domain/wallet-invoices/wallet-invoice-builder.ts, src/servers/cron.ts, src/servers/trigger.ts, src/services/lnd/utils.ts, src/services/price/index.ts, test/helpers/ledger.ts, test/helpers/price.ts, test/legacy-integration/02-user-wallet/02-receive-lightning.spec.ts, test/legacy-integration/02-user-wallet/02-receive-onchain.spec.ts, test/legacy-integration/app/cron/delete-payments.spec.ts, test/legacy-integration/services/cache/index.spec.ts, test/legacy-integration/services/lnd/utils.spec.ts, test/legacy-integration/services/mongoose/wallet-onchain-pending-receive.spec.ts, test/mocks/get-current-price.ts, test/unit/app/prices/get-current-price.spec.ts, test/unit/domain/ledger/index.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-validator.spec.ts, test/unit/domain/wallets/settlement-amounts.spec.ts, test/unit/domain/wallets/tx-history.spec.ts
- update trigger and cron usd invoices handler
- refactor `new Date(Date.now())` to `new Date()` 
- update/add tests to support new usd invoices behavior
=> refactor: update cron/trigger usd invoices handler

dev/apollo-federation/supergraph.graphql, src/app/authentication/logout.ts, src/domain/authentication/index.types.d.ts, src/graphql/error-map.ts, src/graphql/public/root/mutation/user-logout.ts, src/graphql/public/schema.graphql, src/servers/index.files.d.ts, src/servers/middlewares/session.ts, src/services/kratos/auth-phone-no-password.ts, src/services/kratos/errors.ts
this is a breaking change but this API was not used before so the breaking change will not have no impact on existing clients
=> chore: remove the necessity to pass authToken to logout

dev/apollo-federation/supergraph.graphql, src/app/authentication/logout.ts, src/graphql/public/root/mutation/user-logout.ts, src/graphql/public/schema.graphql
=> chore: optionally pass a deviceToken argument when logging out

src/app/payments/helpers.ts, src/app/payments/send-intraledger.ts, src/app/wallets/get-on-chain-fee.ts, src/app/wallets/send-on-chain.ts, src/app/wallets/update-pending-invoices.ts, src/domain/errors.ts, src/domain/payments/index.types.d.ts, src/domain/payments/onchain-payment-flow-builder.ts, src/domain/payments/payment-flow-builder.ts, src/domain/wallet-invoices/index.types.d.ts, src/domain/wallet-invoices/wallet-invoice-receiver.ts, src/domain/wallets/index.types.d.ts, src/domain/wallets/primitives.ts, src/graphql/error-map.ts, src/services/mongoose/wallets.ts, test/helpers/user.ts, test/integration/services/wallets-repository.spec.ts, test/legacy-integration/services/dealer/hedge-price.spec.ts, test/unit/domain/wallet-invoices/wallet-invoice-receiver.spec.ts, test/unit/payments/onchain-payment-flow-builder.spec.ts, test/unit/payments/payment-flow-builder.spec.ts
This PR simplifies the `withRecipientWallet` interface to remove redundancy and improve type safety.
=> refactor: simplify with-recipient interface

src/servers/event-handlers/kratos.ts
we are not returning the error so we need to register it manually
=> chore: add record exception to registration endpoint

README.md
... and highlighting new bria issues
=> doc: update to new repo

core/api/src/domain/users/phone-metadata-authorizer.ts
Fix for https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/zrhkEzdW98r
=> fix: phone metadata null validation

BUCK, apps/consent/BUCK, apps/consent/Dockerfile, apps/consent/app/components/button/primary-button-component.tsx, apps/consent/app/components/button/secondary-button-component.tsx, apps/consent/next.config.js, apps/dashboard/BUCK, flake.nix, pnpm-lock.yaml, pnpm-workspace.yaml, toolchains/workspace-pnpm/BUCK, toolchains/workspace-pnpm/build_next_build.py, toolchains/workspace-pnpm/compile_typescript.py, toolchains/workspace-pnpm/macros.bzl, toolchains/workspace-pnpm/package_next_bin.py, toolchains/workspace-pnpm/toolchain.bzl
To verify run `nix build .#consent`
=> build: add production build for apps/consent

core/api/src/app/lightning/get-held-invoices.ts, core/api/src/debug/add-payment-request-all-wallet-invoice.ts, core/api/src/domain/bitcoin/lightning/index.types.d.ts, core/api/src/servers/trigger.ts, core/api/src/services/lnd/index.ts
- iterates over all invoices in lnd nodes and adds payment requests to their respective wallet invoices
Steps for test testing:
1. Populate the db with invoices
```
make reset-deps
bats -t test/bats/ln-receive
```
2. Go into mongo db and remove the payment request field from a document in `invoiceusers` collection
3. Run the debug script
```
. ./.envrc && yarn ts-node \                                       
--files \
-r tsconfig-paths/register \
-r src/services/tracing.ts \
./src/debug/add-payment-request-all-wallet-invoice.ts
```
=> chore: add payment request to invoice debug script

core/api/src/services/ipfetcher/index.ts
Fix alerts related to proxycheck timeout https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/4LU8eJ2t7wP
=> fix: proxycheck timeout

core/api/BUCK, core/api/package.json, core/api/src/debug/websocket/package.json, toolchains/workspace-pnpm/macros.bzl, toolchains/workspace-pnpm/package_runnable_tsc_build_bin.py
=> build: add tsc check buck rule

core/api/package.json, core/api/yarn.lock, pnpm-lock.yaml
Details: https://www.npmjs.com/advisories/1094349
=> fix: bump @babel/core to fix vulnerability

core/api/src/services/lnd/index.ts
This is to fix lightning error parsing that is currently broken at [Ln1179](https://github.com/GaloyMoney/galoy/pull/3402/files#diff-40dbf1fa2873b74522801fa03f1febf5742ade4285c5dba2c825232082129b4dR1168)
=> fix: parsing lnd errors for error message

core/api/src/debug/clean-kratos-identities.ts, core/api/src/domain/authentication/index.types.d.ts, core/api/src/services/kratos/identity.ts, core/api/test/e2e/servers/kratos.spec.ts, typos.toml
Debug script to fix mismatch between accounts and kratos identities (trigger [this issue](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/cuNVBfeeJ8L))
=> chore: add debug script to clean kratos identities

core/api/dev/apollo-federation/supergraph.graphql, core/api/src/graphql/public/root/mutation/onchain-payment-send-all.ts, core/api/src/graphql/public/root/mutation/onchain-payment-send.ts, core/api/src/graphql/public/root/mutation/onchain-usd-payment-send-as-sats.ts, core/api/src/graphql/public/root/mutation/onchain-usd-payment-send.ts, core/api/src/graphql/public/root/query/on-chain-tx-fee-query.ts, core/api/src/graphql/public/root/query/on-chain-usd-tx-fee-query-as-sats.ts, core/api/src/graphql/public/root/query/on-chain-usd-tx-fee-query.ts, core/api/src/graphql/public/schema.graphql
Fix [UnknownOnChainServiceError](https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/75wZQdD7iu1)
it is not a breaking change because default value will handle null or speed not present(tested locally but will need test on staging)
=> fix: speed null in onchain queries/mutations

CONTRIBUTING.md, README.md
This PR fixes some typos and grammatical errors in the contributing file.
=> Fixed typos in the contributing file.

README.md, docs/BUCK2.md, docs/DEVELOPMENT_ENVIRONMENT.md, docs/LEGACY_DEV.md, docs/hydra.md, docs/swap.md
=> fix: typos

apps/dashboard/app/api-keys/server-actions.ts, apps/dashboard/components/api-keys/create.tsx, apps/dashboard/components/api-keys/list.tsx, apps/dashboard/services/graphql/mutations/api-keys.ts
=> chore(dashboard): create api key expires in ui

.github/stale.yml
=> ci: close stale issue after 1y and 30 days if not reply

apps/consent/app/components/button/primary-button-component.tsx, apps/consent/app/components/button/secondary-button-component.tsx, apps/consent/app/components/phone-auth/index.tsx, apps/consent/app/components/phone-auth/phone-auth-form.tsx, apps/consent/app/login/email-login-form.tsx, apps/consent/app/login/email-login-server-action.ts, apps/consent/app/login/phone/server-actions.ts, apps/consent/app/login/verification/form.tsx, apps/consent/app/login/verification/server-actions.ts, apps/consent/app/login/verification/verification.types.ts, apps/consent/app/types/index.types.ts, apps/consent/cypress/e2e/email-sign-in/login-email.cy.ts, apps/consent/cypress/e2e/phone-sign-in/login-phone.cy.ts, apps/consent/next.config.js, apps/consent/package.json, pnpm-lock.yaml
- Updated to Next.js 14: https://nextjs.org/blog/next-14
- Changed experimental packages to stable.
- Added types now that experimental modules support types.
=> chore(consent): nextjs update consent

core/api/src/services/kratos/auth-email-no-password.ts
add id to try to fix [unknown error](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/BtTE6U8rS98)
=> chore(core): add kratos message id for unkown errors

ARCHITECTURE.md, CONTRIBUTING.md, README.md, docs/DEVELOPMENT_ENVIRONMENT.md
Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.
=> fix: several typos in the docs

core/api/src/graphql/public/types/scalar/endpoint-url.ts, core/api/src/services/svix/index.ts
Fix svix [unkown error](https://ui.honeycomb.io/galoy/datasets/galoy-staging/result/2TW32zCTsi1)
=> fix(core): add callback protocol validation

core/api/src/domain/authentication/errors.ts, core/api/src/graphql/error-map.ts, core/api/src/services/kratos/auth-email-no-password.ts
fix [unknown kratos error](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/x4dUQocwHtk)
=> fix(core): handle email code expired kratos error

apps/dashboard/app/api-keys/server-actions.ts, apps/dashboard/components/api-keys/api-card.tsx, apps/dashboard/components/api-keys/create.tsx, apps/dashboard/components/api-keys/list.tsx, apps/dashboard/components/api-keys/utils.ts, apps/dashboard/services/graphql/generated.ts, apps/dashboard/services/graphql/mutations/api-keys.ts, apps/dashboard/services/graphql/queries/api-keys.ts
=> feat(dasboard): added api key scope in dashboard

core/api/src/services/mongoose/schema.ts
- index on processingCompleted
=> chore: add index to WalletInvoice

core/api/src/app/payments/send-intraledger.ts, core/api/src/app/payments/send-lightning.ts, core/api/src/app/payments/send-on-chain.ts, core/api/src/app/wallets/add-pending-on-chain-transaction.ts, core/api/src/app/wallets/add-settled-on-chain-transaction.ts, core/api/src/app/wallets/settle-payout-txn.ts, core/api/src/app/wallets/update-pending-invoices.ts, core/api/src/config/locales/en.json, core/api/src/config/locales/es.json, core/api/src/domain/notifications/index.types.d.ts, core/api/src/services/notifications/create-push-notification-content.ts, core/api/src/services/notifications/index.ts, core/api/src/services/svix/index.ts, core/api/test/legacy-integration/notifications/notification.spec.ts, core/api/test/unit/services/notifications/transactions.ts
=> refactor: callback notifications

core/api/galoy.yaml, core/api/src/app/authentication/login.ts, core/api/src/app/authentication/request-code.ts, core/api/src/config/schema.ts, core/api/src/config/schema.types.d.ts, core/api/src/config/yaml.ts, core/api/src/domain/rate-limit/errors.ts, core/api/src/domain/rate-limit/index.ts, core/api/src/graphql/error-map.ts, core/api/src/servers/authentication/index.ts
this endpoint will serve as an alternative from the captcha endpoint
=> feat: request code can use appcheckjti

core/api/package.json, core/api/src/services/twilio-service.ts, core/api/test/unit/services/twilio/is-disposable-phone-number.spec.ts, pnpm-lock.yaml
it is not realtime and adds additional 2.5 MB to the image but I think is a good option before using paid services
=> chore(core): add disposable phone validation

core/api/dev/apollo-federation/supergraph.graphql, core/api/src/app/payments/send-intraledger.ts, core/api/src/app/payments/send-lightning.ts, core/api/src/app/payments/update-pending-payments.ts, core/api/src/domain/callback/index.ts, core/api/src/domain/notifications/index.ts, core/api/src/graphql/public/schema.graphql, core/api/src/graphql/public/types/scalar/tx-notification-type.ts, core/api/src/services/notifications/index.ts, core/api/test/unit/services/notifications/transactions.ts, dev/config/apollo-federation/supergraph.graphql
=> feat(core): add missing callbacks

apps/pay/app/lnurlp/[username]/callback/route.ts, apps/pay/app/lnurlp/[username]/route.ts, apps/pay/env.ts, apps/pay/package.json, apps/pay/pages/[username]/print.tsx, apps/pay/utils/utils.ts, bats/helpers/ledger.bash, dev/Tiltfile, pnpm-lock.yaml
- use the url of the req to populate ln address
=> fix(pay): use req url for ln address

core/api/galoy.yaml, core/api/src/app/payments/add-earn.ts, core/api/src/config/schema.ts, core/api/src/config/schema.types.d.ts, core/api/src/config/yaml.ts, core/api/src/domain/rate-limit/errors.ts, core/api/src/domain/rate-limit/index.ts, core/api/src/graphql/error-map.ts, core/api/src/graphql/public/root/mutation/quiz-completed.ts, core/api/test/integration/app/payments/add-earn.spec.ts
Add limiter by ip for add earn, it will [reduce farmers requests](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/gfSX5pTXptR)
=> feat(core): add addEarn limiter

core/api/BUCK, core/api/package.json
Runs with: `$ buck2 test //core/api:dev-check-code`
=> chore(core): add dev-check-code buck rules

ci/apps/app-template.lib.yml, ci/apps/tasks/open-charts-pr.sh
This PR will make the source code diffs generated in the charts repo PRs to be more precise, showing the diffs only for files that are reported by buck2 to be relevant for an app.
=> ci: revamp src diffs

apps/pay/pages/[username]/print.tsx
- fixes 500 error on `print` page caused by the url not being fully qualified
=> fix(pay): print paycode page

core/api/src/services/lnd/rebalancing.ts
Add additional attributes to debug [cron alert](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/t1BSL1nsspr/a/H62Er4oyvST?utm_content=view_graph&utm_medium=Trigger&utm_source=pagerduty)
=> chore(core): add additional span attrs to rebalance

bats/core/api/auth.bats, core/api/src/app/authentication/totp.ts, core/api/src/domain/authentication/index.types.d.ts, core/api/src/domain/shared/error-parsers.ts, core/api/src/services/kratos/auth-email-no-password.ts, core/api/src/services/kratos/identity.ts, core/api/src/services/kratos/private.ts, core/api/tsconfig.json
This is to more correctly place this method and to handle errors explicitly
=> chore(core): move getIdentityIdFromFlowId to repository

apps/dashboard/app/batch-payments/utils.ts, apps/dashboard/components/batch-payments/index.tsx, apps/dashboard/components/upload-button.tsx
+ loading indicator on csv upload 
+ drag drop fix 
+ split record in chunks
=> feat(dashboard): batch payment improvements/fixes

ci/apps/tasks/open-charts-pr.sh, ci/core/tasks/open-charts-pr.sh, ci/core/tasks/open-core-bundle-charts-pr.sh
- ci: initialize array
- ci: initialize relevant commits array
=> ci: fix empty relevant commits handling

ci/apps/pipeline.yml, ci/apps/tasks/bump-image-digest.sh, ci/core/tasks/bump-image-digest.sh
- ci: handle buck target in metadata
- ci: fix metadata syntax
- ci: handle buck target in metadata
=> ci: handle buck target in metadata

core/notifications/proto/notifications.proto, core/notifications/src/grpc/server/convert.rs, core/notifications/src/grpc/server/mod.rs
- adds notification use cases to the grpc server
=> feat(notifications): add grpc notification endpoints

core/api/src/app/on-chain/rebalance-to-cold-wallet.ts
update offChainBalance amount to use getTotalBalance which includes lnds onchain, offchain and pending channels balances
=> fix(core): update coldstorage offchain balance to use Ln getTotalBalance

bats/core/api/account.bats, bats/core/api/device-account.bats, bats/gql/account-limits.gql, core/api/src/app/accounts/account-limit.ts, core/api/src/domain/accounts/index.types.d.ts, core/api/src/domain/accounts/limits-volume.ts, core/api/src/services/ledger/facade/volume.ts, core/api/test/integration/services/ledger-facade.spec.ts, core/api/test/unit/domain/accounts/limits-volume.spec.ts
_Merge after #3867_
This is to codify the application of `incoming` and `outgoing` volumes directly  in the respective volume method
=> refactor(core): limits related volume methods

core/api/src/app/payments/send-on-chain.ts, core/api/src/app/wallets/get-on-chain-fee.ts, core/api/src/domain/ledger/imbalance-calculator.ts, core/api/src/domain/ledger/index.types.d.ts, core/api/src/domain/payments/index.types.d.ts, core/api/src/domain/payments/onchain-payment-flow-builder.ts, core/api/src/services/ledger/facade/volume.ts, core/api/test/integration/services/ledger-facade.spec.ts, core/api/test/unit/domain/ledger/activity-checker.spec.ts, core/api/test/unit/domain/ledger/imbalance-calculator.spec.ts, core/api/test/unit/payments/onchain-payment-flow-builder.spec.ts
_Merge after #3868_
This is to codify the application of `incoming` and `outgoing` volumes directly  in the respective volume method
=> refactor(core): netIn onchain/ln volume methods

core/api/src/services/ledger/facade/index.types.d.ts, core/api/src/services/ledger/facade/volume.ts, core/api/test/unit/services/ledger/domain/volume-calculator.spec.ts
=> feat(core): add volume calculator

core/api/src/migrations/20240130210000-location-migration-1.ts
=> fix: migration for location

apps/admin-panel/BUCK, apps/consent/BUCK, apps/consent/app/graphql/generated.ts, apps/dashboard/BUCK, apps/dashboard/services/graphql/generated.ts, apps/pay/BUCK, core/api/Makefile, dev/BUCK, dev/bin/codegen.sh
Run all with `buck2 run //dev/codegen`
=> chore: add dev codegen rules to all `apps` projects

apps/dashboard/app/api-keys/page.tsx
=> feat(dashboard): added api key warning

core/api/src/app/wallets/update-single-pending-invoice.ts
- reorganize code so we have as close as possible lnd settle, mark as paid and ledger record
- early return ln lnd service connection issues
=> fix(trigger): early return on lnd connection issues

apps/dashboard/cypress/e2e/batch-payments/batch-payments.cy.ts, apps/dashboard/cypress/support/test-data.ts
+ Separating BTC payments and USD wallet payments in batch payments test.
+ Remove redundant field from BTC payment test data.
=> test(dashboard): refactor batch payment test

core/api/src/servers/exporter.ts
those are much better data related query. they don't need the real time aspect provided by grafana
=> chore: remove some exporter values

apps/dashboard/app/api-keys/page.tsx, apps/dashboard/components/api-keys/create.tsx
=> feat(dashboard): btc-pay copy btn

Cargo.lock, Cargo.toml, core/notifications/BUCK, core/notifications/Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Closes https://github.com/GaloyMoney/galoy/pull/4024, https://github.com/GaloyMoney/galoy/pull/4023, https://github.com/GaloyMoney/galoy/pull/3988, https://github.com/GaloyMoney/galoy/pull/3987, https://github.com/GaloyMoney/galoy/pull/3986
=> chore(notifications): bump rust deps

apps/map/components/map/index.tsx
+ update marker for better performance.
+ zoom out on start.
=> chore(map): update marker

core/notifications/locales/en.yml, core/notifications/locales/es.yml, core/notifications/locales/sw.yml, core/notifications/proto/notifications.proto, core/notifications/src/grpc/server/mod.rs, core/notifications/src/messages/mod.rs, core/notifications/src/notification_event/identity_verification_review_started.rs, core/notifications/src/notification_event/mod.rs
- rename IdentityReviewPending to IndentityReviewStarted
=> chore(notifications): rename identity review pending

dev/Tiltfile, dev/config/notifications/notifications.yml
- moves notifications config dependency to be contained with dev folder
- this will fix notifications in quickstart which is currently looking for a config file that does not exist
=> chore(notifications): fix dev config setup

core/api/galoy.yaml, core/api/src/config/schema.ts
@krtk6160 I don't think it's overrided in prod but maybe something to check
=> chore: increasing limits for invoices creation

quickstart/docker-compose.tmpl.yml
- add notifications-pg as dep to notifications
=> fix: notifications quickstart

apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/sidebar/index.tsx, apps/pay/components/switch/index.tsx, apps/pay/package.json, pnpm-lock.yaml
=> chore(pay): make memo button optional

core/api/src/domain/notifications/errors.ts, core/api/src/graphql/error-map.ts, core/api/src/services/notifications/errors.ts, core/api/src/services/notifications/index.ts, core/api/src/services/notifications/push-notifications.ts
Add error handler for `UserNotificationSettingsError - ConcurrentModification` https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/G4wxpoa5Exb
=> fix(core): handle concurrent modification notification service error

apps/pay/app/sats-currency-metadata.ts, apps/pay/components/currency/currency-dropdown.tsx, apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/parse-pos-payment/receive-invoice.tsx, apps/pay/components/payment-outcome/index.tsx, apps/pay/components/payment-outcome/receipt.tsx
+ sat currency in dropdown.
+ sat only works with BTC wallet.
=> feat(pay): sats currency

core/api/src/app/payments/update-pending-payments.ts
Add mitigation notes related to issue https://github.com/lightningnetwork/lnd/issues/7697 which should be resolved with lnd `v0.18.0`.
=> chore(core): add tracing attributes to handle htlc bug edge case

core/notifications/proto/notifications.proto, core/notifications/src/app/mod.rs, core/notifications/src/grpc/server/convert.rs, core/notifications/src/grpc/server/mod.rs, core/notifications/src/job/mod.rs, core/notifications/src/messages/mod.rs, core/notifications/src/notification_event/marketing_notification_triggered.rs, core/notifications/src/notification_event/mod.rs, core/notifications/src/primitives.rs, core/notifications/subgraph/schema.graphql, dev/config/apollo-federation/supergraph.graphql
- add the MarketingNotificationTriggered event
=> feat(notifications): marketing notification triggered

apps/pay/app/[username]/print/page.tsx
updated to what we have in sidebar : https://github.com/GaloyMoney/galoy/blob/6960e0f3701e59de86cb091436df1e203046d51c/apps/pay/components/sidebar/index.tsx#L42 
Fixed: https://pay.blink.sv/nicolas/print --> this should be [nicolas@blink.sv](mailto:nicolas@blink.sv), not [nicolas@pay.blink.sv](mailto:nicolas@pay.blink.sv)
=> chore(pay): update print page userHeader

apps/pay/app/[username]/page.tsx, apps/pay/app/[username]/print/page.tsx, apps/pay/app/[username]/username.module.css, apps/pay/components/layouts/app-layout.module.css, apps/pay/components/layouts/username-layout.tsx, apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/parse-pos-payment/parse-payment.module.css
+ Fixed: make digits better pressable (area around digits is too small currently)
+ Fixed: scale properly on different screen size. [currently sometime only use 50% of the screen ](https://chat.galoy.io/galoy/pl/yy7dbifndjbn9py35ck6raq5ww)while at other time [we use almost too much](https://chat.galoy.io/galoy/pl/x9zii3e6kfnfbjayz9unhp1cte) (no space around the digits and the border of the screen) 
+ Fixed: title should be between blink logo and settings button, instead of below
=> feat(pay): responsive layout changes

apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/parse-pos-payment/parse-payment.module.css, apps/pay/components/parse-pos-payment/receive-invoice.tsx, apps/pay/public/icons/caret-left.svg
+ updated create new invoice to secondary btn.
+ removed timer-bar.
=> chore(pay): QR page changes

apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/sidebar/index.tsx
+ added 'enter' to create invoice + added backspace to get back from QR page. 
+ remove focus from currency drop-down when sidebar is opened.
=> chore(pay): updated keyboard funcitons, sidebar fix

apps/pay/app/[username]/transaction/page.tsx, apps/pay/app/globals.css, apps/pay/components/sidebar/index.tsx, apps/pay/lib/graphql/generated.ts, apps/pay/utils/date-util.ts
Base branch : https://github.com/GaloyMoney/galoy/pull/4149 (build on top of "sign in" branch)
=> feat(pay): transactions list in pay

apps/pay/app/setuppwa/page.tsx, apps/pay/components/parse-pos-payment/parse-payment.module.css
+ also a small fix, remove border on digit buttons when not touched/focus.
=> chore(pay): loading screen on session loading

apps/pay/components/payment-outcome/index.tsx, apps/pay/lib/graphql/generated.ts
Receipt:
Auto print out on payment success.
=> feat(pay): transaction printout from pos

core/api/src/domain/notifications/errors.ts, core/api/src/domain/notifications/index.ts, core/api/src/domain/notifications/index.types.d.ts, core/api/src/domain/primitives/index.types.d.ts, core/api/src/graphql/error-map.ts, core/api/src/services/notifications/convert.ts, core/api/src/services/notifications/index.ts, core/api/src/services/notifications/push-notifications.ts, core/api/test/unit/domain/notifications/index.spec.ts
- validate the notification category values
=> chore(core): validate NotificationCategory

apps/dashboard/components/transaction-details/index.types.ts, apps/dashboard/components/transaction-details/transaction-details-table.tsx
=> chore(dashboard): added sats/cents in transaction table.

apps/pay/.gitignore, apps/pay/app/manifest.ts, apps/pay/components/payment-outcome/index.tsx
If POS companion app is installed, we will use POS printer.
=> chore(pay): detect pos companion app

apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/parse-pos-payment/nfc.tsx, apps/pay/components/sidebar/index.tsx
=> chore(pay): move boldcard to sidebar

core/api/package.json, core/api/src/domain/fiat/display-currency.ts, core/api/test/unit/domain/fiat/major-to-minor-unit.spec.ts, pnpm-lock.yaml
if you have a better alternative we need to pass tests in `core/api/test/unit/domain/fiat/major-to-minor-unit.spec.ts`
=> fix(core): add bignumber to solve js math issues

core/notifications/locales/ca.yml, core/notifications/locales/en.yml, core/notifications/locales/es.yml, core/notifications/locales/ro.yml, core/notifications/src/notification_event/price_changed.rs
=> feat(notifications): bitcoin price down notification

apps/pay/app/globals.css, apps/pay/app/setuppwa/setuppwa.module.css, apps/pay/components/layouts/app-layout.module.css, apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/parse-pos-payment/parse-payment.module.css, apps/pay/components/parse-pos-payment/receive-invoice.tsx, apps/pay/components/sheet/index.tsx, apps/pay/components/sidebar/index.tsx
+ made settings menu to use full screen
+ made font larger on setting screen
+ removed extra space that occurs due to browser tabs if the app is used from a browser.
=> chore(pay): layout changes

apps/pay/components/parse-pos-payment/nfc.tsx
+ Adding loader when payment is processed by nfc
+ added bold card not supported message.
=> chore(pay): adding loader for nfc

dev/Tiltfile
Allow parser to handle lines like:
```bash
SECRET="my-secret" # this is a secret
```
=> refactor(toolchain): add env file inline comment handling to parser

apps/pay/app/setuppwa/setuppwa.module.css, apps/pay/components/parse-pos-payment/nfc.tsx
+ nfc loader should take full screen.
+ nfc button should be disable if not supported. 
+ Also have a small fix for setuppwa to take full screen height.
=> fix(pay): nfc loader full screen, disable nfc if not supported

apps/voucher/instrumentation.node.ts, apps/voucher/instrumentation.ts, apps/voucher/package.json, apps/voucher/services/db/migrations/20240406102113_create_withdraw_links.ts, apps/voucher/services/db/schema.ts, dev/Tiltfile, pnpm-lock.yaml
+ Adding otel.
+ Moved table creating to instrumentation.
=> chore(voucher): adding otel

core/notifications/src/app/mod.rs, core/notifications/src/grpc/server/mod.rs, core/notifications/src/job/mod.rs, core/notifications/src/primitives.rs
=> refactor(notifications): de-duplicate user ids during marketing notification

apps/consent/components/phone-auth/phone-auth-form.tsx, apps/consent/components/select.tsx, apps/consent/components/varification-components/two-fa-verification-code-form.tsx, apps/consent/components/varification-components/verification-code-form.tsx
+ Fixed https://github.com/GaloyMoney/galoy/issues/4344
+ Fixed https://github.com/GaloyMoney/galoy/issues/4334
=> chore(consent): auto focues on verification and default value for channel to SMS

.github/workflows/integration-test.yml, dev/Tiltfile
Separate build and run steps for integration tests to help with debugging and reliability
=> ci: separate build steps in integration tests

core/notifications/src/notification_event/price_changed.rs
This PR updates the category for price notifications
=> fix(notifications): correct category for price changed event

apps/map/app/api/health/route.ts, dev/Tiltfile
+ Fixes log coming for Merchant Map API in core.
=> chore(map): adding health endpoint

apps/consent/BUCK, apps/consent/package.json, apps/dashboard/BUCK, apps/dashboard/package.json, apps/map/BUCK, apps/map/package.json, apps/pay/BUCK, apps/pay/app/[username]/page.tsx, apps/pay/components/parse-pos-payment/index.tsx, apps/pay/components/payment-outcome/index.tsx, apps/pay/package.json, apps/voucher/BUCK, apps/voucher/app/voucher/page.tsx, apps/voucher/package.json
Fail the lint check if there are warnings in apps.
=> chore(apps): fail on warning

core/api/src/domain/bitcoin/lightning/errors.ts, core/api/src/graphql/error-map.ts, core/api/src/services/lnd/errors.ts, core/api/src/services/lnd/index.ts
handle [this](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/tDRnPwxvJFV) alert (unkown error)
=> fix(core): handle invoice amount unknown error

core/api/src/services/ledger/admin-legacy.ts, core/api/src/services/ledger/books.ts
Reduce balanceSnapshotSec for admin balance queries
=> fix(core): update admin queries balanceSnapshotSec

ci/apps/tasks/open-charts-pr.sh
Has been tested and it does fix the problem.
Old PR with wrong diff - https://github.com/GaloyMoney/charts/pull/6379
New PR - https://github.com/GaloyMoney/charts/pull/6388
=> ci: fix partial diffs

apps/pay/cypress/support/commands.ts, apps/pay/tsconfig.json
Fix build issues. To test run `pnpm build` (apps/pay) in main branch
=> fix(pay): force react types path

apps/voucher/components/nav-bar/navigation.tsx, apps/voucher/context/currency-context.tsx
Updated CurrencyProvider to fetch currency list once and ensure only valid currencies are used.
=> chore(voucher): integrate currency list fetching and validation in currency context

apps/voucher/app/create/client-side-page.tsx, apps/voucher/components/create/confirm-modal/index.tsx, apps/voucher/graphql/resolvers.ts, apps/voucher/graphql/schema.ts, apps/voucher/lib/graphql/generated/index.ts
Using salesAmount/voucherPrice as input instead of voucherAmount, as we are using voucherPrice for calculations on the frontend and now doing the same on the backend.
=> chore(voucher): adding voucher price as input

apps/voucher/app/create/client-side-page.tsx, apps/voucher/app/page.tsx, apps/voucher/app/redeem/page.tsx, apps/voucher/app/user/links/page.tsx, apps/voucher/app/withdraw/[voucher-secret]/onchain/page.tsx, apps/voucher/components/create/confirm-modal/index.tsx, apps/voucher/components/create/create-page-amount/index.tsx, apps/voucher/components/create/create-page-percentage/index.tsx, apps/voucher/components/nav-bar/navigation.tsx, apps/voucher/components/num-pad/index.tsx, apps/voucher/hooks/use-currency-exchange-rate.tsx, apps/voucher/lib/utils.ts
+ Rename variables for better understanding.
+ Split components on create screen.
+ Use `code` display type for currency.
=> refactor(voucher): frontend refactor and misc fixes.

apps/voucher/app/withdraw/[voucher-secret]/lnurl/lnurl.tsx, apps/voucher/components/user-links/index.tsx, apps/voucher/lib/print-companion.ts
Rename 
+ Voucher Amount to Voucher Value
+ Sales Amount to Voucher Price
=> chore(voucher): rename details in user link

core/api/test/integration/services/lnd-service.spec.ts, dev/docker-compose.deps.yml
- Update lnd to v0.18.0-beta
- Update bitcoind to v27.0
=> chore: update lnd

core/api/package.json, core/api/src/app/quiz/claim.ts, core/api/src/services/notifications/grpc-client.ts, core/api/src/services/notifications/index.ts, pnpm-lock.yaml
- Fix rateLimitConfig for checkAddQuizAttemptPerPhoneLimits
- Add disposable validation to checkAddQuizAttemptPerPhoneLimits
- Validate  checkAddQuizAttemptPerPhoneLimits for every phone related to the user
=> fix(core): update quiz phone limits validation

bats/core/api/onchain-receive.bats, bats/helpers/onchain.bash, dev/config/lnd/lnd.conf
Ref: https://github.com/GaloyMoney/charts/pull/7086
=> chore: remove deprecated bitcoin.active setting

dev/docker-compose.deps.yml, quickstart/docker-compose.yml
This PR syncs the postgresql versions for the docker-compose files as per the current infrastructure/
=> fix(deps): PG version sync

core/api/src/services/lnd/errors.ts, core/api/src/services/lnd/index.ts
fix [this alert](https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/ESV3DXNjavN/trace/r1UKbKfHapj?source=query&span=eac31bb369f98da5)
=> fix(core): handle unknown error for unsupported payment feature

core/api/src/servers/exporter.ts
Exporter still having some timeouts and `assets vs liabilities` issues. This new settings should guarantee consistency
ps: non-critical because it only affects exporter
=> fix(core): update exporter db connection settings

core/api/package.json, core/api/src/app/comm/submit-feedback.ts, pnpm-lock.yaml
adding msg will enable keybase and mattermost webhooks
=> chore(core): update feedback webhook content

apps/consent/components/phone-auth/index.tsx, apps/consent/components/phone-auth/phone-auth-form.tsx
=> fix(consent): show channels available per country

core/api/src/app/authentication/request-code.ts, core/api/src/domain/errors.ts, core/api/src/domain/phone-provider/index.ts, core/api/src/graphql/error-map.ts, core/api/src/graphql/public/root/mutation/captcha-request-auth-code.ts, core/api/src/graphql/public/root/mutation/user-phone-registration-initiate.ts, core/api/src/servers/authentication/index.ts, core/api/test/unit/domain/phone-provider/checked-to-channel.spec.ts
Fix `UnknownPhoneProviderServiceError` when unsupported channel for country is used
=> fix(core): add channel validation
